<?php
declare(strict_types=1);

namespace app\service;

final class CtripProfileFieldMetaService
{
    private const CTRIP_BUSINESS_REPORT_PAGE_URL = 'https://ebooking.ctrip.com/datacenter/inland/businessreport/outline?microJump=true';
    private const CTRIP_FLOW_TRANSFORM_PAGE_URL = 'https://ebooking.ctrip.com/datacenter/inland/businessreport/flowdata?microJump=true';
    private const CTRIP_PSI_PAGE_URL = 'https://ebooking.ctrip.com/psi/index?microJump=true';
    private const CTRIP_PSI_REQUEST_URL = 'https://ebooking.ctrip.com/psi/api/getHotelPsiV2';
    private const CTRIP_ADS_PAGE_URL = 'https://ebooking.ctrip.com/toolcenter/cpc/pyramid?microJump=true';
    private const CTRIP_ADS_REQUEST_URL = 'https://ebooking.ctrip.com/toolcenter/api/cpc/queryCampaignReportList?hostType=HE';

    public static function base(string $fieldKey): array
    {
        $businessPage = self::CTRIP_BUSINESS_REPORT_PAGE_URL;
        $selfRule = '本店口径：masterHotelId/hotelId 必须等于当前携程酒店ID；stat_date/data_date 使用业务日期，不使用采集时间。';
        $competitorRule = '竞品口径：仅作为竞争圈或竞品指标，不写入本店经营额、间夜或订单数。';
        $rankRule = '榜单名次口径：字段值均为第几名，只保留 ranking/data_value/raw_data.rank_metrics；即使接口字段名包含 amount、quantity、bookOrderNum、score、rate、Num，也不写入订单量、金额、间夜、评分、访客量或转化率。';
        $realtimeUrl = 'https://ebooking.ctrip.com/datacenter/api/dataCenter/report/getDayReportRealTimeDate';
        $marketUrl = 'https://ebooking.ctrip.com/datacenter/api/dataCenter/sale/fetchMarketOverViewV2';
        $visitorTitleUrl = 'https://ebooking.ctrip.com/datacenter/api/dataCenter/current/fetchVisitorTitleV2';
        $capacityUrl = 'https://ebooking.ctrip.com/datacenter/api/dataCenter/current/fetchCapacityOverViewV4';
        $seqRankUrl = 'https://ebooking.ctrip.com/datacenter/api/dataCenter/current/fetchCurrentHotelSeqInfoV1';
        $flowCompeteUrl = 'https://ebooking.ctrip.com/datacenter/api/dataCenter/report/getDayReportFlowCompete';
        $serverQuantityUrl = 'https://ebooking.ctrip.com/datacenter/api/dataCenter/report/getDayReportServerQuantity';
        $userBehaviorPage = 'https://ebooking.ctrip.com/datacenter/inland/userbehavior/user?microJump=true';
        $userBehaviorImPage = 'https://ebooking.ctrip.com/datacenter/inland/userbehavior/user?goto=im';
        $userBehaviorApi = 'https://ebooking.ctrip.com/datacenter/api/dataCenter/userbehavior/';
        $commentPage = 'https://ebooking.ctrip.com/comment/commentList?microJump=true';
        $commentSummaryUrl = 'https://ebooking.ctrip.com/restapi/soa2/26353/getCommentNumV2';
        $commentListUrl = 'https://ebooking.ctrip.com/comment/api/getCommentList';
        $hotelRatingUrl = 'https://ebooking.ctrip.com/restapi/soa2/26353/getHotelRating';

        return [
            'last_visitor_total' => [
                'page_url' => $businessPage,
                'request_url' => $realtimeUrl,
                'json_path' => 'data.lastVisitorTotal',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=last_visitor_total',
                'source_interface' => 'getDayReportRealTimeDate',
                'source_keys' => 'lastVisitorTotal',
                'target_value' => 'lastVisitorTotal',
                'value_meaning' => '昨日携程 OTA 访客数',
                'notes' => '严格固定口径；不再从 UV、visitorTotal 或长文本中猜字段。',
            ],
            'visitor_count' => [
                'page_url' => $businessPage,
                'request_url' => $visitorTitleUrl,
                'json_path' => 'data.visitorTotal',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=visitor_count',
                'source_interface' => 'fetchVisitorTitleV2',
                'source_keys' => 'visitorTotal',
                'target_value' => 'visitorTotal',
                'value_meaning' => '经营报告概要日报：实时访客量',
                'notes' => '严格固定取 data.visitorTotal；lastVisitorTotal 在该接口是上周同期。',
            ],
            'visitor_rank' => [
                'page_url' => $businessPage,
                'request_url' => $visitorTitleUrl,
                'json_path' => 'data.visitorRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.visitor_rank',
                'source_interface' => 'fetchVisitorTitleV2',
                'source_keys' => 'visitorRank',
                'target_value' => 'visitorRank',
                'value_meaning' => '实时访客量竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入访客量。',
            ],
            'visitor_count_last_week' => [
                'page_url' => $businessPage,
                'request_url' => $visitorTitleUrl,
                'json_path' => 'data.lastVisitorTotal',
                'ownership_rule' => '上周同期对比值：仅作对比维度，不覆盖本期实时访客量。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=visitor_count_last_week',
                'source_interface' => 'fetchVisitorTitleV2',
                'source_keys' => 'lastVisitorTotal',
                'target_value' => 'lastVisitorTotal',
                'value_meaning' => '实时访客量上周同期',
                'notes' => '严格固定取 data.lastVisitorTotal。',
            ],
            'competitor_avg_visitor' => [
                'page_url' => $businessPage,
                'request_url' => $visitorTitleUrl,
                'json_path' => 'data.competitorAvgNumber',
                'ownership_rule' => $competitorRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=competitor_avg_visitor',
                'source_interface' => 'fetchVisitorTitleV2',
                'source_keys' => 'competitorAvgNumber',
                'target_value' => 'competitorAvgNumber',
                'value_meaning' => '携程竞对平均访客数',
                'notes' => '竞对平均值单独保留，不覆盖本店实时访客量。',
            ],
            'qunar_visitor_count' => [
                'page_url' => $businessPage,
                'request_url' => $visitorTitleUrl,
                'json_path' => 'data.qunarVisitorTotal',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=qunar_visitor_count',
                'source_interface' => 'fetchVisitorTitleV2',
                'source_keys' => 'qunarVisitorTotal',
                'target_value' => 'qunarVisitorTotal',
                'value_meaning' => '去哪儿实时访客量',
                'notes' => '去哪儿渠道单独保留，不覆盖携程 visitor_count。',
            ],
            'qunar_visitor_rank' => [
                'page_url' => $businessPage,
                'request_url' => $visitorTitleUrl,
                'json_path' => 'data.qunarCompetitorRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.qunar_visitor_rank',
                'source_interface' => 'fetchVisitorTitleV2',
                'source_keys' => 'qunarCompetitorRank',
                'target_value' => 'qunarCompetitorRank',
                'value_meaning' => '去哪儿实时访客量竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入访客量。',
            ],
            'qunar_visitor_count_last_week' => [
                'page_url' => $businessPage,
                'request_url' => $visitorTitleUrl,
                'json_path' => 'data.lastQunarVisitorTotal',
                'ownership_rule' => '上周同期对比值：仅作对比维度，不覆盖本期去哪儿实时访客量。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=qunar_visitor_count_last_week',
                'source_interface' => 'fetchVisitorTitleV2',
                'source_keys' => 'lastQunarVisitorTotal',
                'target_value' => 'lastQunarVisitorTotal',
                'value_meaning' => '去哪儿实时访客量上周同期',
                'notes' => '严格固定取 data.lastQunarVisitorTotal。',
            ],
            'qunar_competitor_avg_visitor' => [
                'page_url' => $businessPage,
                'request_url' => $visitorTitleUrl,
                'json_path' => 'data.qunarCompetitorAvgNumber',
                'ownership_rule' => $competitorRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=qunar_competitor_avg_visitor',
                'source_interface' => 'fetchVisitorTitleV2',
                'source_keys' => 'qunarCompetitorAvgNumber',
                'target_value' => 'qunarCompetitorAvgNumber',
                'value_meaning' => '去哪儿竞对平均访客数',
                'notes' => '竞对平均值单独保留，不覆盖去哪儿实时访客量。',
            ],
            'order_count' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.orderQuantity',
                'ownership_rule' => $selfRule,
                'storage_field' => 'online_daily_data.book_order_num',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'orderQuantity',
                'target_value' => 'orderQuantity',
                'value_meaning' => '经营报告概要日报：总订单量',
                'notes' => '严格固定取 data.orderQuantity；渠道订单量另用 ctrip/qunar/elong 字段。',
            ],
            'order_count_sync' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.synchronizationOrderQuantity',
                'ownership_rule' => '同步后对比值：仅作对比维度，不覆盖总订单量。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=order_count_sync',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'synchronizationOrderQuantity',
                'target_value' => 'synchronizationOrderQuantity',
                'value_meaning' => '同步后总订单量',
                'notes' => '严格固定取 data.synchronizationOrderQuantity。',
            ],
            'order_count_rank' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.rankOfOrderQuantity',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.order_count_rank',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'rankOfOrderQuantity',
                'target_value' => 'rankOfOrderQuantity',
                'value_meaning' => '订单量竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入订单量。',
            ],
            'competitor_avg_orders' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.competitorsAverageOrderQuantity',
                'ownership_rule' => $competitorRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=competitor_avg_orders',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'competitorsAverageOrderQuantity',
                'target_value' => 'competitorsAverageOrderQuantity',
                'value_meaning' => '竞对平均订单量',
                'notes' => '竞对平均值单独保留，不覆盖本店订单量。',
            ],
            'ctrip_order_count' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.ctripOrderQuantity',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=ctrip_order_count',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'ctripOrderQuantity',
                'target_value' => 'ctripOrderQuantity',
                'value_meaning' => '携程订单量',
                'notes' => '携程渠道订单量，不覆盖总订单量。',
            ],
            'ctrip_order_count_sync' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.ctripSynchronizationOrderQuantity',
                'ownership_rule' => '同步后对比值：仅作对比维度，不覆盖携程订单量。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=ctrip_order_count_sync',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'ctripSynchronizationOrderQuantity',
                'target_value' => 'ctripSynchronizationOrderQuantity',
                'value_meaning' => '携程同步后订单量',
                'notes' => '严格固定取 data.ctripSynchronizationOrderQuantity。',
            ],
            'ctrip_order_count_rank' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.ctripRankOfOrderQuantity',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.ctrip_order_count_rank',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'ctripRankOfOrderQuantity',
                'target_value' => 'ctripRankOfOrderQuantity',
                'value_meaning' => '携程订单量竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入订单量。',
            ],
            'qunar_order_count' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.qunarOrderQuantity',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=qunar_order_count',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'qunarOrderQuantity',
                'target_value' => 'qunarOrderQuantity',
                'value_meaning' => '去哪儿订单量',
                'notes' => '去哪儿渠道订单量，不覆盖总订单量。',
            ],
            'qunar_order_count_sync' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.qunarSynchronizationOrderQuantity',
                'ownership_rule' => '同步后对比值：仅作对比维度，不覆盖去哪儿订单量。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=qunar_order_count_sync',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'qunarSynchronizationOrderQuantity',
                'target_value' => 'qunarSynchronizationOrderQuantity',
                'value_meaning' => '去哪儿同步后订单量',
                'notes' => '严格固定取 data.qunarSynchronizationOrderQuantity。',
            ],
            'qunar_order_count_rank' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.qunarRankOfOrderQuantity',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.qunar_order_count_rank',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'qunarRankOfOrderQuantity',
                'target_value' => 'qunarRankOfOrderQuantity',
                'value_meaning' => '去哪儿订单量竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入订单量。',
            ],
            'elong_order_count' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.elongOrderQuantity',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=elong_order_count',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'elongOrderQuantity',
                'target_value' => 'elongOrderQuantity',
                'value_meaning' => '艺龙订单量',
                'notes' => '艺龙渠道订单量，不覆盖总订单量。',
            ],
            'elong_order_count_sync' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.elongSynchronizationOrderQuantity',
                'ownership_rule' => '同步后对比值：仅作对比维度，不覆盖艺龙订单量。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=elong_order_count_sync',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'elongSynchronizationOrderQuantity',
                'target_value' => 'elongSynchronizationOrderQuantity',
                'value_meaning' => '艺龙同步后订单量',
                'notes' => '严格固定取 data.elongSynchronizationOrderQuantity。',
            ],
            'elong_order_count_rank' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.elongRankOfOrderQuantity',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.elong_order_count_rank',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'elongRankOfOrderQuantity',
                'target_value' => 'elongRankOfOrderQuantity',
                'value_meaning' => '艺龙订单量竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入订单量。',
            ],
            'self_order_count' => [
                'page_url' => $businessPage,
                'request_url' => $realtimeUrl,
                'json_path' => 'data.synchronizationOrderQuantity',
                'ownership_rule' => $selfRule,
                'storage_field' => 'online_daily_data.book_order_num',
                'source_interface' => 'getDayReportRealTimeDate',
                'source_keys' => 'synchronizationOrderQuantity',
                'target_value' => 'synchronizationOrderQuantity',
                'value_meaning' => '本店订单兼容字段',
                'status' => 'paused',
                'enabled' => false,
                'notes' => '与 order_count 口径重复，默认停用；保留配置便于旧数据兼容。',
            ],
            'realtime_booking_orders' => [
                'page_url' => $businessPage,
                'request_url' => $realtimeUrl,
                'json_path' => 'candidate:data.bookOrderNum',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=realtime_booking_orders',
                'source_interface' => 'getDayReportRealTimeDate',
                'source_keys' => 'bookOrderNum',
                'target_value' => 'bookOrderNum',
                'value_meaning' => '经营报告概要日报实时数据：实时预订订单',
                'status' => 'needs_parser',
                'enabled' => true,
                'notes' => '截图已确认页面展示；source key 需用真实响应样例核验后再改为 confirmed。',
            ],
            'realtime_booking_orders_last_week' => [
                'page_url' => $businessPage,
                'request_url' => $realtimeUrl,
                'json_path' => 'candidate:data.synchronizationBookOrderNum',
                'ownership_rule' => '上周同期对比值：仅作对比维度，不覆盖本期实时预订订单。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=realtime_booking_orders_last_week',
                'source_interface' => 'getDayReportRealTimeDate',
                'source_keys' => 'synchronizationBookOrderNum, lastBookOrderNum',
                'target_value' => 'synchronizationBookOrderNum',
                'value_meaning' => '实时预订订单上周同期',
                'status' => 'needs_parser',
                'enabled' => true,
                'notes' => '截图已确认页面展示；source key 需用真实响应样例核验后再改为 confirmed。',
            ],
            'realtime_booking_orders_rank' => [
                'page_url' => $businessPage,
                'request_url' => $realtimeUrl,
                'json_path' => 'candidate:data.bookOrderNumRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.realtime_booking_orders_rank',
                'source_interface' => 'getDayReportRealTimeDate',
                'source_keys' => 'bookOrderNumRank, bookingOrdersrank',
                'target_value' => 'bookOrderNumRank',
                'value_meaning' => '实时预订订单竞争圈排名',
                'status' => 'needs_parser',
                'enabled' => true,
                'notes' => '排名只进入 rank_metrics/data_value 展示；source key 需用真实响应样例核验。',
            ],
            'in_house_room_nights' => [
                'page_url' => $businessPage,
                'request_url' => $realtimeUrl,
                'json_path' => 'candidate:data.bookQuantity',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=in_house_room_nights',
                'source_interface' => 'getDayReportRealTimeDate',
                'source_keys' => 'bookQuantity, stayInRN, inHouseRoomNights',
                'target_value' => 'bookQuantity',
                'value_meaning' => '经营报告概要日报实时数据：实时在店间夜',
                'status' => 'needs_parser',
                'enabled' => true,
                'notes' => '截图已确认页面展示；不得覆盖离店间夜量 room_nights，source key 需样例核验。',
            ],
            'in_house_room_nights_last_week' => [
                'page_url' => $businessPage,
                'request_url' => $realtimeUrl,
                'json_path' => 'candidate:data.synchronizationBookQuantity',
                'ownership_rule' => '上周同期对比值：仅作对比维度，不覆盖本期实时在店间夜。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=in_house_room_nights_last_week',
                'source_interface' => 'getDayReportRealTimeDate',
                'source_keys' => 'synchronizationBookQuantity, lastStayInRN',
                'target_value' => 'synchronizationBookQuantity',
                'value_meaning' => '实时在店间夜上周同期',
                'status' => 'needs_parser',
                'enabled' => true,
                'notes' => '截图已确认页面展示；source key 需用真实响应样例核验后再改为 confirmed。',
            ],
            'in_house_room_nights_rank' => [
                'page_url' => $businessPage,
                'request_url' => $realtimeUrl,
                'json_path' => 'candidate:data.stayInRNrank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.in_house_room_nights_rank',
                'source_interface' => 'getDayReportRealTimeDate',
                'source_keys' => 'stayInRNrank, bookQuantityRank',
                'target_value' => 'stayInRNrank',
                'value_meaning' => '实时在店间夜竞争圈排名',
                'status' => 'needs_parser',
                'enabled' => true,
                'notes' => '排名只进入 rank_metrics/data_value 展示；source key 需用真实响应样例核验。',
            ],
            'order_amount' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.amount',
                'ownership_rule' => $selfRule,
                'storage_field' => 'online_daily_data.amount',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'amount',
                'target_value' => 'amount',
                'value_meaning' => '经营报告概要日报卡片：离店销售额',
                'notes' => '严格固定取卡片主值 data.amount；bookAmount 是预订口径，不能覆盖离店销售额。',
            ],
            'order_amount_last_week' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.synchronizationAmount',
                'ownership_rule' => '上周同期对比值：仅作对比维度，不覆盖本期离店销售额。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=order_amount_last_week',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'synchronizationAmount',
                'target_value' => 'synchronizationAmount',
                'value_meaning' => '离店销售额上周同期',
                'notes' => '严格固定取 data.synchronizationAmount。',
            ],
            'amount_rank' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.rankOfAmount',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.amount_rank',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'rankOfAmount',
                'target_value' => 'rankOfAmount',
                'value_meaning' => '离店销售额竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入销售额。',
            ],
            'room_nights' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.quantity',
                'ownership_rule' => $selfRule,
                'storage_field' => 'online_daily_data.quantity',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'quantity',
                'target_value' => 'quantity',
                'value_meaning' => '经营报告概要日报卡片：离店间夜量',
                'notes' => '严格固定取卡片主值 data.quantity；bookQuantity 是预订间夜，不能覆盖离店间夜。',
            ],
            'room_nights_last_week' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.synchronizationQuantity',
                'ownership_rule' => '上周同期对比值：仅作对比维度，不覆盖本期离店间夜。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=room_nights_last_week',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'synchronizationQuantity',
                'target_value' => 'synchronizationQuantity',
                'value_meaning' => '离店间夜量上周同期',
                'notes' => '严格固定取 data.synchronizationQuantity。',
            ],
            'quantity_rank' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.rankOfQuantity',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.quantity_rank',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'rankOfQuantity',
                'target_value' => 'rankOfQuantity',
                'value_meaning' => '离店间夜量竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入间夜量。',
            ],
            'occupied_rooms' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.occupiedRooms',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=occupied_rooms',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'occupiedRooms',
                'target_value' => 'occupiedRooms',
                'value_meaning' => '已售间夜 / 已入住房间数',
                'notes' => '严格固定取 data.occupiedRooms；不覆盖离店间夜量 data.quantity。',
            ],
            'occupied_rooms_sync' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.synchronizationOccupiedRooms',
                'ownership_rule' => '同步后对比值：仅作对比维度，不覆盖本期已售间夜。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=occupied_rooms_sync',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'synchronizationOccupiedRooms',
                'target_value' => 'synchronizationOccupiedRooms',
                'value_meaning' => '同步后已售间夜',
                'notes' => '严格固定取 data.synchronizationOccupiedRooms。',
            ],
            'occupied_rooms_rank' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.rankOfOccupiedRooms',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.occupied_rooms_rank',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'rankOfOccupiedRooms',
                'target_value' => 'rankOfOccupiedRooms',
                'value_meaning' => '已售间夜竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入已售间夜。',
            ],
            'competitor_avg_occupied_rooms' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.competitorsAverageOccupiedRooms',
                'ownership_rule' => $competitorRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=competitor_avg_occupied_rooms',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'competitorsAverageOccupiedRooms',
                'target_value' => 'competitorsAverageOccupiedRooms',
                'value_meaning' => '竞对平均已售间夜',
                'notes' => '竞对平均值单独保留，不覆盖本店已售间夜。',
            ],
            'avg_price' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.averagePrice',
                'ownership_rule' => $selfRule,
                'storage_field' => 'online_daily_data.data_value where metric_key=avg_price',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'averagePrice',
                'target_value' => 'averagePrice',
                'value_meaning' => '经营报告概要日报卡片：平均卖价',
                'notes' => '严格固定取 data.averagePrice；不把 minPrice 当平均卖价。',
            ],
            'avg_price_last_week' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.synchronizationAveragePrice',
                'ownership_rule' => '上周同期对比值：仅作对比维度，不覆盖本期平均卖价。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=avg_price_last_week',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'synchronizationAveragePrice',
                'target_value' => 'synchronizationAveragePrice',
                'value_meaning' => '平均卖价上周同期',
                'notes' => '严格固定取 data.synchronizationAveragePrice。',
            ],
            'avg_price_rank' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.rankOfAveragePrice',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.avg_price_rank',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'rankOfAveragePrice',
                'target_value' => 'rankOfAveragePrice',
                'value_meaning' => '平均卖价竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入平均卖价。',
            ],
            'close_rate' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.closeRate',
                'ownership_rule' => $selfRule,
                'storage_field' => 'online_daily_data.data_value where metric_key=close_rate',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'closeRate',
                'target_value' => 'closeRate',
                'value_meaning' => '经营报告概要日报卡片：成交率',
                'notes' => '严格固定取 data.closeRate；曝光转化率另走 queryFlowTransforNewV1.flowRate。',
            ],
            'close_rate_last_week' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.synchronizationCloseRate',
                'ownership_rule' => '上周同期对比值：仅作对比维度，不覆盖本期成交率。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=close_rate_last_week',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'synchronizationCloseRate',
                'target_value' => 'synchronizationCloseRate',
                'value_meaning' => '成交率上周同期',
                'notes' => '严格固定取 data.synchronizationCloseRate。',
            ],
            'close_rate_rank' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.rankOfCloseRate',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.close_rate_rank',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'rankOfCloseRate',
                'target_value' => 'rankOfCloseRate',
                'value_meaning' => '成交率竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入成交率。',
            ],
            'occupancy_rate' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.occupancyRate',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=occupancy_rate',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'occupancyRate',
                'target_value' => 'occupancyRate',
                'value_meaning' => '经营报告概要日报：实时出租率',
                'status' => 'confirmed',
                'enabled' => true,
                'notes' => '严格固定取 data.occupancyRate；仅代表携程概要日报在店实时出租率口径，不包装成全酒店入住率。',
            ],
            'occupancy_rate_sync' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.synchronizationOccupancyRate',
                'ownership_rule' => '同步后对比值：仅作对比维度，不覆盖本期入住率。',
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=occupancy_rate_sync',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'synchronizationOccupancyRate',
                'target_value' => 'synchronizationOccupancyRate',
                'value_meaning' => '实时出租率上周同期',
                'notes' => '严格固定取 data.synchronizationOccupancyRate。',
            ],
            'occupancy_rate_rank' => [
                'page_url' => $businessPage,
                'request_url' => $capacityUrl,
                'json_path' => 'data.rankOfOccupancyRate',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.occupancy_rate_rank',
                'source_interface' => 'fetchCapacityOverViewV4',
                'source_keys' => 'rankOfOccupancyRate',
                'target_value' => 'rankOfOccupancyRate',
                'value_meaning' => '实时出租率竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入实时出租率。',
            ],
            'competitor_average' => [
                'page_url' => $businessPage,
                'json_path' => '待拆分：competitorAvgNumber / competitorsAverageOrderQuantity / competitorsAverageOccupiedRooms',
                'ownership_rule' => $competitorRule,
                'storage_field' => 'ota_ctrip_metric_facts',
                'source_interface' => '待拆分',
                'source_keys' => 'competitorAvgNumber, competitorsAverageOrderQuantity, competitorsAverageOccupiedRooms',
                'target_value' => '待拆分',
                'value_meaning' => '竞争圈平均值泛化字段',
                'status' => 'paused',
                'enabled' => false,
                'notes' => '泛化字段不允许启用；应拆成竞争圈平均访客、订单、间夜等独立字段。',
            ],
            'competition_rank' => [
                'page_url' => $businessPage,
                'request_url' => $marketUrl,
                'json_path' => 'data.rankOfAmount',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.data_type=ranking',
                'source_interface' => 'fetchMarketOverViewV2',
                'source_keys' => 'rankOfAmount',
                'target_value' => 'rankOfAmount',
                'value_meaning' => '竞争圈成交排名',
                'status' => 'paused',
                'enabled' => false,
                'notes' => '排名不是销售额/订单/间夜，默认停用；需要时按 ranking 类型查看。',
            ],
            'avg_user_age' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserAge',
                'json_path' => 'data.avg',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.data_value + raw_data.metrics.avg_user_age',
                'source_interface' => 'queryUserAge',
                'source_keys' => 'avg',
                'target_value' => 'avg_user_age',
                'value_meaning' => '平均年龄，单位岁。',
                'notes' => '只保存接口返回 avg，不用年龄段分布占比反算平均值。',
            ],
            'user_age' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserAge / queryUserFeatures',
                'json_path' => 'data.titleList[] / data[].age',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.user_age',
                'source_interface' => 'queryUserAge / queryUserFeatures',
                'source_keys' => 'titleList, age',
                'target_value' => 'titleList[] / age',
                'value_meaning' => '年龄段维度；queryUserAge 对应 data.valueList[] 为分布占比，queryUserFeatures 为摘要特征。',
                'notes' => '分布占比只来自 queryUserAge.valueList；queryUserFeatures 不生成占比。',
            ],
            'user_source' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserFeatures',
                'json_path' => 'data[].source',
                'ownership_rule' => '携程 OTA 渠道用户行为摘要；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.user_source',
                'source_interface' => 'queryUserFeatures',
                'source_keys' => 'source',
                'target_value' => 'source',
                'value_meaning' => '用户特征摘要中的客源来源。',
                'notes' => '摘要字段不生成 distribution_share。',
            ],
            'travel_time' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserFeatures / queryUserTravelTime',
                'json_path' => 'data[].traveltime / data.titleList[] / data[].name',
                'ownership_rule' => '携程 OTA 渠道用户行为摘要/分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.travel_time',
                'source_interface' => 'queryUserFeatures / queryUserTravelTime',
                'source_keys' => 'traveltime, titleList, name',
                'target_value' => 'traveltime / titleList[] / name',
                'value_meaning' => '用户特征摘要或出行时间分布维度。',
                'notes' => 'queryUserTravelTime 占比必须来自 value/valueList，不由文本维度反推。',
            ],
            'booking_hour' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'getOrderDistribution',
                'json_path' => 'data.titleList[] / data[].name',
                'ownership_rule' => '携程 OTA 渠道24小时预订分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.booking_hour',
                'source_interface' => 'getOrderDistribution',
                'source_keys' => 'titleList, name',
                'target_value' => 'booking_hour',
                'value_meaning' => '24小时预订时段维度，如 00:00、14:00。',
                'notes' => '占比来自 value/valueList，不补齐缺失小时。',
            ],
            'price_band' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserFeatures',
                'json_path' => 'data[].consumer',
                'ownership_rule' => '携程 OTA 渠道用户行为摘要；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.price_band',
                'source_interface' => 'queryUserFeatures',
                'source_keys' => 'consumer',
                'target_value' => 'consumer',
                'value_meaning' => '用户特征摘要中的消费档位。',
                'notes' => '消费档位是文本维度，不等同于订单金额或 ADR。',
            ],
            'hotel_star_preference' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserStar',
                'json_path' => 'data.titleList[] / data[].name',
                'ownership_rule' => '携程 OTA 渠道用户星级偏好分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.hotel_star_preference',
                'source_interface' => 'queryUserStar',
                'source_keys' => 'titleList, name',
                'target_value' => 'hotel_star_preference',
                'value_meaning' => '酒店星级偏好维度。',
                'notes' => '占比来自 value/valueList，不写入全酒店星级结构字段。',
            ],
            'consumption_power' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserPrice',
                'json_path' => 'data.titleList[] / data[].name',
                'ownership_rule' => '携程 OTA 渠道用户消费能力分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.consumption_power',
                'source_interface' => 'queryUserPrice',
                'source_keys' => 'titleList, name',
                'target_value' => 'consumption_power',
                'value_meaning' => '消费能力区间维度，如 <=200、201-500。',
                'notes' => '消费能力是用户分布维度，不等同于 ADR 或订单金额。',
            ],
            'booking_method' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryOrderType',
                'json_path' => 'data.titleList[] / data[].name',
                'ownership_rule' => '携程 OTA 渠道预订方式分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.booking_method',
                'source_interface' => 'queryOrderType',
                'source_keys' => 'titleList, name',
                'target_value' => 'booking_method',
                'value_meaning' => '预订方式维度，如电脑端、移动端、其他。',
                'notes' => '占比来自 value/valueList，不用渠道订单量反推。',
            ],
            'order_hotel_count' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserOrders',
                'json_path' => 'data.titleList[] / data[].name',
                'ownership_rule' => '携程 OTA 渠道订购酒店次数分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.order_hotel_count',
                'source_interface' => 'queryUserOrders',
                'source_keys' => 'titleList, name',
                'target_value' => 'order_hotel_count',
                'value_meaning' => '订购酒店次数维度，如 1次、2次、3次及以上。',
                'notes' => '占比来自 value/valueList，不用订单明细反推。',
            ],
            'avg_booking_days' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserBookingDays',
                'json_path' => 'data.avg',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.data_value + raw_data.metrics.avg_booking_days',
                'source_interface' => 'queryUserBookingDays',
                'source_keys' => 'avg',
                'target_value' => 'avg_booking_days',
                'value_meaning' => '平均提前预订天数，单位天。',
                'notes' => '只保存接口返回 avg，不用 titleList/valueList 反算平均值。',
            ],
            'booking_days' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserBookingDays',
                'json_path' => 'data.titleList[]',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.booking_days',
                'source_interface' => 'queryUserBookingDays',
                'source_keys' => 'titleList',
                'target_value' => 'titleList[]',
                'value_meaning' => '提前预订天数区间；对应 data.valueList[] 为分布占比。',
                'notes' => '按 titleList 和 valueList 下标一一配对，不补齐缺失值。',
            ],
            'avg_stay_days' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserStayDays',
                'json_path' => 'data.avg',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.data_value + raw_data.metrics.avg_stay_days',
                'source_interface' => 'queryUserStayDays',
                'source_keys' => 'avg',
                'target_value' => 'avg_stay_days',
                'value_meaning' => '平均连续入住天数，单位天。',
                'notes' => '只保存接口返回 avg，不用 titleList/valueList 反算平均值。',
            ],
            'stay_days' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserStayDays',
                'json_path' => 'data.titleList[]',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.stay_days',
                'source_interface' => 'queryUserStayDays',
                'source_keys' => 'titleList',
                'target_value' => 'titleList[]',
                'value_meaning' => '连续入住天数区间；对应 data.valueList[] 为分布占比。',
                'notes' => '按 titleList 和 valueList 下标一一配对，不补齐缺失值。',
            ],
            'user_sex' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserSex',
                'json_path' => 'data[].name',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.user_sex',
                'source_interface' => 'queryUserSex',
                'source_keys' => 'name',
                'target_value' => 'name',
                'value_meaning' => '性别维度；对应 data[].value 为分布占比。',
                'notes' => '维度值写入 raw_data.dimension_values，分布占比写入 data_value/raw_data.metrics.distribution_share。',
            ],
            'user_type' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserType',
                'json_path' => 'data[].name',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.user_type',
                'source_interface' => 'queryUserType',
                'source_keys' => 'name',
                'target_value' => 'name',
                'value_meaning' => '用户类型维度；对应 data[].value 为分布占比。',
                'notes' => '维度值写入 raw_data.dimension_values，分布占比写入 data_value/raw_data.metrics.distribution_share。',
            ],
            'price_sensitivity' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserPriceInfo',
                'json_path' => 'data.titleList[]',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.price_sensitivity',
                'source_interface' => 'queryUserPriceInfo',
                'source_keys' => 'titleList',
                'target_value' => 'titleList[]',
                'value_meaning' => '价格敏感度维度；对应 data.valueList[] 为分布占比。',
                'notes' => '按 titleList 和 valueList 下标一一配对，不补齐缺失值。',
            ],
            'order_preference' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserPoint',
                'json_path' => 'data.titleList[]',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.order_preference',
                'source_interface' => 'queryUserPoint',
                'source_keys' => 'titleList',
                'target_value' => 'titleList[]',
                'value_meaning' => '订购偏好维度，如促销类型敏感度、优惠券偏好、早餐订购。',
                'notes' => '与 preference_frequency 组成二维分布；占比来自 userColumnBos[].valueList[]。',
            ],
            'preference_frequency' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserPoint',
                'json_path' => 'data.userColumnBos[].titleList[]',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.preference_frequency',
                'source_interface' => 'queryUserPoint',
                'source_keys' => 'userColumnBos[].titleList[]',
                'target_value' => 'preference_frequency',
                'value_meaning' => '订购偏好频次维度，如从未、偶尔、较少、经常。',
                'notes' => '按 userColumnBos 序号与 titleList 序号配对；缺失值不补齐。',
            ],
            'user_source_scope' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserSource',
                'json_path' => 'data.localCityRate / data.otherCityRate / data.topCityRate',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.user_source_scope',
                'source_interface' => 'queryUserSource',
                'source_keys' => 'localCityRate, otherCityRate, topCityRate',
                'target_value' => 'localCityRate, otherCityRate, topCityRate',
                'value_meaning' => '本地、异地、TOP5城市范围维度；对应同名字段为分布占比。',
                'notes' => '范围维度只表达来源结构，不等同于全酒店客源结构。',
            ],
            'source_region' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserSource',
                'json_path' => 'data.provinces[].name',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.source_region',
                'source_interface' => 'queryUserSource',
                'source_keys' => 'provinces[].name',
                'target_value' => 'provinces[].name',
                'value_meaning' => '客源省份/地区维度；对应 provinces[].value 为分布占比。',
                'notes' => '保留平台返回名称，包含境外地区时不强行归并。',
            ],
            'source_city' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserSource',
                'json_path' => 'data.cities[].name',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.source_city',
                'source_interface' => 'queryUserSource',
                'source_keys' => 'cities[].name',
                'target_value' => 'cities[].name',
                'value_meaning' => 'TOP城市维度；对应 cities[].value 为分布占比。',
                'notes' => '仅记录接口返回 TOP 城市列表，不推断未返回城市。',
            ],
            'distribution_share' => [
                'page_url' => $userBehaviorPage,
                'request_url' => $userBehaviorApi . 'queryUserSex / queryUserType / queryUserPriceInfo / queryUserAge / queryUserBookingDays / queryUserStayDays / queryUserPoint / queryUserSource / queryUserTravelTime / queryUserStar / queryUserPrice / queryOrderType / queryUserOrders / getOrderDistribution',
                'json_path' => 'data[].value / data.valueList[] / data.userColumnBos[].valueList[] / data.localCityRate / data.otherCityRate / data.topCityRate / data.provinces[].value / data.cities[].value',
                'ownership_rule' => '携程 OTA 渠道用户行为分布；只代表平台近180天预订数据口径。',
                'storage_field' => 'online_daily_data.data_value + raw_data.metrics.distribution_share',
                'source_interface' => 'queryUserSex / queryUserType / queryUserPriceInfo / queryUserAge / queryUserBookingDays / queryUserStayDays / queryUserPoint / queryUserSource / queryUserTravelTime / queryUserStar / queryUserPrice / queryOrderType / queryUserOrders / getOrderDistribution',
                'source_keys' => 'value, valueList, userColumnBos[].valueList, localCityRate, otherCityRate, topCityRate, provinces[].value, cities[].value',
                'target_value' => 'distribution_share',
                'value_meaning' => '分布占比，单位 %；按维度字段区分性别、类型、年龄、价格敏感、提前预订、入住天数、订购偏好、客源范围/省份/城市、出行时间、星级偏好、消费能力、预订方式、订购次数、预订小时。',
                'notes' => '占比必须来自响应里的数值字段，不由维度字段反推。',
            ],
            'seq_rank' => [
                'page_url' => $businessPage,
                'request_url' => $seqRankUrl,
                'json_path' => 'data.rank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.data_type=ranking',
                'source_interface' => 'fetchCurrentHotelSeqInfoV1',
                'source_keys' => 'rank',
                'target_value' => 'rank',
                'value_meaning' => '当前酒店实时排名',
                'status' => 'confirmed',
                'enabled' => true,
                'notes' => '排名字段进入 ranking 事实和 rank_metrics，不参与销售额、订单数或间夜汇总。',
            ],
            'competitor_visitor' => [
                'page_url' => $businessPage,
                'request_url' => $flowCompeteUrl,
                'json_path' => 'data.comhtluv',
                'ownership_rule' => $competitorRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=competitor_visitor',
                'source_interface' => 'getDayReportFlowCompete',
                'source_keys' => 'comhtluv',
                'target_value' => 'comhtluv',
                'value_meaning' => '竞争圈/竞品访客',
                'notes' => '竞品指标单独保留，不覆盖本店 visitor_count。',
            ],
            'competitor_orders' => [
                'page_url' => $businessPage,
                'request_url' => $flowCompeteUrl,
                'json_path' => 'data.ordquantity',
                'ownership_rule' => $competitorRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=competitor_orders',
                'source_interface' => 'getDayReportFlowCompete',
                'source_keys' => 'ordquantity',
                'target_value' => 'ordquantity',
                'value_meaning' => '竞争圈/竞品订单',
                'notes' => '竞品指标单独保留，不覆盖本店 order_count。',
            ],
            'competitor_revenue' => [
                'page_url' => $businessPage,
                'request_url' => $flowCompeteUrl,
                'json_path' => 'data.ordamount',
                'ownership_rule' => $competitorRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=competitor_revenue',
                'source_interface' => 'getDayReportFlowCompete',
                'source_keys' => 'ordamount',
                'target_value' => 'ordamount',
                'value_meaning' => '竞争圈/竞品收入',
                'notes' => '竞品指标单独保留，不覆盖本店 order_amount。',
            ],
            'competitor_hotel_list' => [
                'page_url' => $businessPage,
                'json_path' => 'data.competingHotels[]',
                'ownership_rule' => '竞品实体列表，不是标量指标；每条必须保留 masterHotelId/hotelName。',
                'storage_field' => 'raw_data.entity_snapshot',
                'source_interface' => 'queryCompetingHotelsV2',
                'source_keys' => 'masterHotelId, hotelName, distance, starLevel, zoneName',
                'target_value' => 'data.competingHotels[]',
                'value_meaning' => '竞品酒店实体快照',
                'status' => 'paused',
                'enabled' => false,
                'notes' => '实体列表不进入默认字段采集；需要单独做竞品实体管理。',
            ],
            'competition_rank_order_count' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'sellRanksBO[].bookingOrdersrank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_order_count',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'bookingOrdersrank, orderRank, orderQuantityRank, bookOrderNum',
                'target_value' => 'bookingOrdersrank',
                'value_meaning' => '竞争圈榜单：预订订单量排名',
                'notes' => '排名只进入 ranking/raw_data.rank_metrics，不写入订单量。',
            ],
            'competition_rank_order_amount' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'sellRanksBO[].bookingGMVrank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_order_amount',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'bookingGMVrank, amountRank, orderAmountRank, amount',
                'target_value' => 'bookingGMVrank',
                'value_meaning' => '竞争圈榜单：预订销售额排名',
                'notes' => '排名只进入 ranking/raw_data.rank_metrics，不写入销售额。',
            ],
            'competition_rank_room_nights' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'sellRanksBO[].stayInRNrank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_room_nights',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'stayInRNrank, quantity',
                'target_value' => 'stayInRNrank',
                'value_meaning' => '竞争圈榜单：在店间夜排名',
                'notes' => '排名只进入 ranking/raw_data.rank_metrics，不写入间夜量。',
            ],
            'competition_rank_occupancy_rate' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'sellRanksBO[].rentalRaterank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_occupancy_rate',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'rentalRaterank',
                'target_value' => 'rentalRaterank',
                'value_meaning' => '竞争圈榜单：出租率排名',
                'notes' => '排名只进入 ranking/raw_data.rank_metrics，不写入出租率。',
            ],
            'competition_rank_app_detail_visitor' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'flowRanksBO[].totalDetailNum',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_app_detail_visitor',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'totalDetailNum, detailVisitorRank, appDetailUvRank',
                'target_value' => 'totalDetailNum',
                'value_meaning' => '竞争圈榜单：APP详情页访客量排名',
                'notes' => '排名只进入 ranking/raw_data.rank_metrics，不写入访客量。',
            ],
            'competition_rank_app_conversion_rate' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'flowRanksBO[].convertionRate',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_app_conversion_rate',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'convertionRate, conversionRate, detailConversionRateRank',
                'target_value' => 'convertionRate',
                'value_meaning' => '竞争圈榜单：APP详情页转化率排名',
                'notes' => '排名只进入 ranking/raw_data.rank_metrics，不写入转化率。',
            ],
            'competition_rank_psi_score' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'serviceRanksBO[].serviceScoreRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_psi_score',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'serviceScoreRank, psiScoreRank, psiRank',
                'target_value' => 'serviceScoreRank',
                'value_meaning' => '竞争圈榜单：PSI分排名',
                'notes' => '页面字段是榜单名次，已确认；source key 需用完整 Response 复核，缺失时显式标记，不用兜底值。',
            ],
            'competition_rank_ctrip_rating' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'serviceRanksBO[].commentScore',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_ctrip_rating',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'commentScore, commentScoreRank, ctripCommentScoreRank, ctripRatingRank',
                'target_value' => 'commentScore',
                'value_meaning' => '竞争圈榜单：携程点评分排名',
                'notes' => '页面字段是榜单名次，已确认；source key 需用完整 Response 复核，缺失时显式标记，不用兜底值。',
            ],
            'competition_rank_qunar_rating' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'serviceRanksBO[].qunarCommentScoreRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_qunar_rating',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'qunarCommentScoreRank, qunarRatingRank',
                'target_value' => 'qunarCommentScoreRank',
                'value_meaning' => '竞争圈榜单：去哪儿点评分排名',
                'notes' => '页面字段是榜单名次，已确认；source key 需用完整 Response 复核，缺失时显式标记，不用兜底值。',
            ],
            'competition_rank_tongcheng_rating' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'serviceRanksBO[].tongchengCommentScoreRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_tongcheng_rating',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'tongchengCommentScoreRank, tongChengCommentScoreRank, tongchengRatingRank',
                'target_value' => 'tongchengCommentScoreRank',
                'value_meaning' => '竞争圈榜单：同程点评分排名',
                'notes' => '页面字段是榜单名次，已确认；source key 需用完整 Response 复核，缺失时显式标记，不用兜底值。',
            ],
            'competition_rank_zhixing_rating' => [
                'page_url' => 'https://ebooking.ctrip.com/ebkgrowth/datacenter/competition/competitionlist?microJump=true',
                'request_url' => 'https://ebooking.ctrip.com/restapi/soa2/{nodeId}/getCompetingRank',
                'json_path' => 'serviceRanksBO[].zhixingCommentScoreRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.competition_rank_zhixing_rating',
                'source_interface' => 'getCompetingRank',
                'source_keys' => 'zhixingCommentScoreRank, zhiXingCommentScoreRank, zhixingRatingRank',
                'target_value' => 'zhixingCommentScoreRank',
                'value_meaning' => '竞争圈榜单：智行点评分排名',
                'notes' => '页面字段是榜单名次，已确认；source key 需用完整 Response 复核，缺失时显式标记，不用兜底值。',
            ],
            'psi_score' => [
                'page_url' => $businessPage . ' / ' . self::CTRIP_PSI_PAGE_URL,
                'request_url' => $serverQuantityUrl . ' / ' . self::CTRIP_PSI_REQUEST_URL,
                'json_path' => 'data.serviceScore / data.psiScoreBo.totalScore',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=psi_score',
                'source_interface' => 'getDayReportServerQuantity / getHotelPsiV2',
                'source_keys' => 'serviceScore, totalScore',
                'target_value' => 'serviceScore',
                'value_meaning' => 'PSI 服务质量分',
                'status' => 'confirmed',
                'enabled' => true,
                'notes' => '两个 PSI 来源应为同一业务分值：经营日报取 data.serviceScore，PSI 详情取本店 data.psiScoreBo.totalScore；relHtlPsiBoList 只作相关酒店事实。',
            ],
            'service_score' => [
                'page_url' => $businessPage,
                'request_url' => $serverQuantityUrl,
                'json_path' => 'data.serviceScore',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=service_score',
                'source_interface' => 'getDayReportServerQuantity',
                'source_keys' => 'serviceScore',
                'target_value' => 'serviceScore',
                'value_meaning' => '携程服务质量分',
                'status' => 'paused',
                'enabled' => false,
                'notes' => '兼容旧字段；标准字段使用 psi_score，避免同一 serviceScore 重复入库。',
            ],
            'service_score_rank' => [
                'page_url' => $businessPage,
                'request_url' => $serverQuantityUrl,
                'json_path' => 'data.serviceScoreRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.service_score_rank',
                'source_interface' => 'getDayReportServerQuantity',
                'source_keys' => 'serviceScoreRank',
                'target_value' => 'serviceScoreRank',
                'value_meaning' => 'PSI 服务质量分竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入 PSI 分值。',
            ],
            'ctrip_comment_count' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2 / ' . $commentSummaryUrl,
                'json_path' => 'data.ctripCommentCount / ctripCount.commentCount',
                'ownership_rule' => '携程 OTA 点评摘要；只采集数量与评分汇总，不采集点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.ctrip_comment_count',
                'source_interface' => 'getCommentsScoreV2 / getCommentNumV2',
                'source_keys' => 'ctripCommentCount, ctripCount.commentCount',
                'target_value' => 'ctripCommentCount / ctripCount.commentCount',
                'value_meaning' => '携程点评数量。',
                'notes' => '只保存聚合数量，不保存点评内容。',
            ],
            'qunar_comment_count' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2 / ' . $commentSummaryUrl,
                'json_path' => 'data.qunarCommentCount / qunarCount.commentCount',
                'ownership_rule' => '去哪儿 OTA 点评摘要；只采集数量与评分汇总，不采集点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.qunar_comment_count',
                'source_interface' => 'getCommentsScoreV2 / getCommentNumV2',
                'source_keys' => 'qunarCommentCount, qunarCount.commentCount',
                'target_value' => 'qunarCommentCount / qunarCount.commentCount',
                'value_meaning' => '去哪儿点评数量。',
                'notes' => '只保存聚合数量，不保存点评内容。',
            ],
            'elong_comment_count' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2 / ' . $commentSummaryUrl,
                'json_path' => 'data.elongCommentCount / elongCount.commentCount',
                'ownership_rule' => '艺龙 OTA 点评摘要；只采集数量与评分汇总，不采集点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.elong_comment_count',
                'source_interface' => 'getCommentsScoreV2 / getCommentNumV2',
                'source_keys' => 'elongCommentCount, elongCount.commentCount',
                'target_value' => 'elongCommentCount / elongCount.commentCount',
                'value_meaning' => '艺龙点评数量。',
                'notes' => '接口返回 null 时保持缺失状态，不补 0。',
            ],
            'zx_comment_count' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl,
                'json_path' => 'zxCount.commentCount',
                'ownership_rule' => '智行 OTA 点评摘要；只采集数量聚合，不采集点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.zx_comment_count',
                'source_interface' => 'getCommentNumV2',
                'source_keys' => 'zxCount.commentCount, zhixingCount.commentCount',
                'target_value' => 'zxCount.commentCount',
                'value_meaning' => '智行点评数量。',
                'notes' => '来自 getCommentNumV2 渠道聚合对象；缺失时保持缺失，不补 0。',
            ],
            'ctrip_rating' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => $serverQuantityUrl . ' / https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2',
                'json_path' => 'data.ctripRatingall',
                'ownership_rule' => $selfRule,
                'storage_field' => 'online_daily_data.comment_score + raw_data.metrics.ctrip_rating',
                'source_interface' => 'getDayReportServerQuantity / getCommentsScoreV2',
                'source_keys' => 'ctripRatingall',
                'target_value' => 'ctripRatingall',
                'value_meaning' => '酒店点评分',
                'notes' => '只采评分汇总，不采点评明文。',
            ],
            'qunar_rating' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2',
                'json_path' => 'data.qunarRatingall',
                'ownership_rule' => '去哪儿 OTA 点评摘要；只采集评分汇总，不采集点评明文。',
                'storage_field' => 'online_daily_data.qunar_comment_score + raw_data.metrics.qunar_rating',
                'source_interface' => 'getCommentsScoreV2',
                'source_keys' => 'qunarRatingall',
                'target_value' => 'qunarRatingall',
                'value_meaning' => '去哪儿点评分。',
                'notes' => '只保存评分汇总，不保存点评明文。',
            ],
            'elong_rating' => [
                'page_url' => self::CTRIP_FLOW_TRANSFORM_PAGE_URL,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2',
                'json_path' => 'data.elongRatingall',
                'ownership_rule' => '艺龙 OTA 点评摘要；只采集评分汇总，不采集点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.elong_rating',
                'source_interface' => 'getCommentsScoreV2',
                'source_keys' => 'elongRatingall',
                'target_value' => 'elongRatingall',
                'value_meaning' => '艺龙点评分。',
                'notes' => '接口返回 null 时保持缺失状态，不补默认评分。',
            ],
            'ctrip_rating_rank' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2',
                'json_path' => 'data.ctripRatingAllRanking',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.ctrip_rating_rank',
                'source_interface' => 'getCommentsScoreV2',
                'source_keys' => 'ctripRatingAllRanking',
                'target_value' => 'ctripRatingAllRanking',
                'value_meaning' => '携程点评分竞争圈排名。',
                'notes' => '排名只进入 raw_data.rank_metrics，不写入评分。',
            ],
            'qunar_rating_rank' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2',
                'json_path' => 'data.qunarRatingAllRanking',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.qunar_rating_rank',
                'source_interface' => 'getCommentsScoreV2',
                'source_keys' => 'qunarRatingAllRanking',
                'target_value' => 'qunarRatingAllRanking',
                'value_meaning' => '去哪儿点评分竞争圈排名。',
                'notes' => '排名只进入 raw_data.rank_metrics，不写入评分。',
            ],
            'comment_response_rate' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2 / ' . $commentSummaryUrl,
                'json_path' => 'data.responseRate / {channel}Count.responseRate',
                'ownership_rule' => '携程 OTA 点评摘要；点评回复率，不等同于 IM 5分钟回复率。',
                'storage_field' => 'online_daily_data.raw_data.metrics.comment_response_rate',
                'source_interface' => 'getCommentsScoreV2 / getCommentNumV2',
                'source_keys' => 'responseRate, ctripCount.responseRate',
                'target_value' => 'responseRate',
                'value_meaning' => '点评回复率，单位 %。',
                'notes' => '该字段来自点评摘要接口，不写入 IM 回复率字段。',
            ],
            'review_environment_score' => [
                'page_url' => $commentPage,
                'request_url' => $hotelRatingUrl,
                'json_path' => 'ratingInfo.ratingLocation / ctripRatings.ratingLocation / elongRatings.ratingLocation / ratingInfo.scoreInfo.subScores[type=ratingLocation].scoreSimple / elongRatings.scoreInfo.subScores[type=ratingLocation].score',
                'ownership_rule' => '携程 OTA 点评质量摘要；只采集环境子评分，不采集点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.review_environment_score',
                'source_interface' => 'getHotelRating',
                'source_keys' => 'ratingLocation, scoreInfo.subScores[type=ratingLocation].scoreSimple',
                'target_value' => 'ratingLocation',
                'value_meaning' => '点评环境评分，单位分。',
                'status' => 'confirmed',
                'notes' => '来自 getHotelRating 成功响应；只保存评分汇总，goodCommentTags/poorCommentTags 不进入默认经营指标。',
            ],
            'review_facility_score' => [
                'page_url' => $commentPage,
                'request_url' => $hotelRatingUrl,
                'json_path' => 'ratingInfo.ratingFacility / ctripRatings.ratingFacility / elongRatings.ratingFacility / ratingInfo.scoreInfo.subScores[type=ratingFacility].scoreSimple / elongRatings.scoreInfo.subScores[type=ratingFacility].score',
                'ownership_rule' => '携程 OTA 点评质量摘要；只采集设施子评分，不采集点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.review_facility_score',
                'source_interface' => 'getHotelRating',
                'source_keys' => 'ratingFacility, scoreInfo.subScores[type=ratingFacility].scoreSimple',
                'target_value' => 'ratingFacility',
                'value_meaning' => '点评设施评分，单位分。',
                'status' => 'confirmed',
                'notes' => '来自 getHotelRating 成功响应；只保存评分汇总，goodCommentTags/poorCommentTags 不进入默认经营指标。',
            ],
            'review_service_score' => [
                'page_url' => $commentPage,
                'request_url' => $hotelRatingUrl,
                'json_path' => 'ratingInfo.ratingService / ctripRatings.ratingService / elongRatings.ratingService / ratingInfo.scoreInfo.subScores[type=ratingService].scoreSimple / elongRatings.scoreInfo.subScores[type=ratingService].score',
                'ownership_rule' => '携程 OTA 点评质量摘要；只采集点评服务子评分，不与 PSI 服务质量分混用。',
                'storage_field' => 'online_daily_data.raw_data.metrics.review_service_score',
                'source_interface' => 'getHotelRating',
                'source_keys' => 'ratingService, scoreInfo.subScores[type=ratingService].scoreSimple',
                'target_value' => 'ratingService',
                'value_meaning' => '点评服务评分，单位分。',
                'status' => 'confirmed',
                'notes' => '来自 getHotelRating 成功响应；字段名为 ratingService，不与 PSI service_score 混用。',
            ],
            'review_cleanliness_score' => [
                'page_url' => $commentPage,
                'request_url' => $hotelRatingUrl,
                'json_path' => 'ratingInfo.ratingRoom / ctripRatings.ratingRoom / elongRatings.ratingRoom / ratingInfo.scoreInfo.subScores[type=ratingRoom].scoreSimple / elongRatings.scoreInfo.subScores[type=ratingRoom].score',
                'ownership_rule' => '携程 OTA 点评质量摘要；只采集卫生子评分，不采集点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.review_cleanliness_score',
                'source_interface' => 'getHotelRating',
                'source_keys' => 'ratingRoom, scoreInfo.subScores[type=ratingRoom].scoreSimple',
                'target_value' => 'ratingRoom',
                'value_meaning' => '点评卫生评分，单位分。',
                'status' => 'confirmed',
                'notes' => '来自 getHotelRating 成功响应；只保存评分汇总，goodCommentTags/poorCommentTags 不进入默认经营指标。',
            ],
            'review_photo_count' => [
                'page_url' => $commentPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2 / ' . $commentSummaryUrl,
                'json_path' => 'data.hasPicCount / {channel}Count.hasPicCount',
                'ownership_rule' => '携程 OTA 点评质量摘要；只保存带图点评聚合计数，不保存图片或点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.review_photo_count',
                'source_interface' => 'getCommentsScoreV2 / getCommentNumV2',
                'source_keys' => 'hasPicCount, ctripCount.hasPicCount, qunarCount.hasPicCount, elongCount.hasPicCount, zxCount.hasPicCount, zhixingCount.hasPicCount, photoCommentCount, pictureCommentCount, imageCommentCount',
                'target_value' => 'review_photo_count',
                'value_meaning' => '带图点评数，单位条。',
                'notes' => '作为带图点评率分子；缺失时不补 0。',
            ],
            'review_photo_rate' => [
                'page_url' => self::CTRIP_PSI_PAGE_URL,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2 / ' . $commentSummaryUrl,
                'json_path' => 'derived:data.hasPicCount / data.commentCount / {channel}Count.hasPicCount / {channel}Count.commentCount',
                'ownership_rule' => '携程 OTA 点评质量摘要；带图点评率为聚合公式字段，不保存图片或点评明文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.review_photo_rate',
                'source_interface' => 'getCommentsScoreV2 / getCommentNumV2',
                'source_keys' => 'hasPicCount, commentCount',
                'target_value' => 'review_photo_rate',
                'value_meaning' => '带图点评率，单位 %。',
                'notes' => '公式：hasPicCount / commentCount * 100；commentCount 缺失或为 0 时保持缺失状态。',
            ],
            'rating_competitor_total' => [
                'page_url' => $businessPage . ' / ' . $userBehaviorPage,
                'request_url' => 'https://ebooking.ctrip.com/datacenter/api/dataCenter/comment/getCommentsScoreV2',
                'json_path' => 'data.competitorHotelTotal',
                'ownership_rule' => '携程 OTA 点评竞争圈摘要；只作为排名分母。',
                'storage_field' => 'online_daily_data.raw_data.metrics.rating_competitor_total',
                'source_interface' => 'getCommentsScoreV2',
                'source_keys' => 'competitorHotelTotal',
                'target_value' => 'competitorHotelTotal',
                'value_meaning' => '点评排名竞争圈酒店总数。',
                'notes' => '用于解释 4/26、8/26 等排名分母，不作为经营规模指标。',
            ],
            'comment_score_summary' => [
                'page_url' => $businessPage,
                'request_url' => $serverQuantityUrl,
                'json_path' => 'data.ctripRatingall',
                'ownership_rule' => $selfRule,
                'storage_field' => 'online_daily_data.comment_score',
                'source_interface' => 'getDayReportServerQuantity',
                'source_keys' => 'ctripRatingall',
                'target_value' => 'ctripRatingall',
                'value_meaning' => '酒店点评分兼容字段，标准口径同 ctrip_rating',
                'notes' => '兼容旧 field_key；新增配置优先看 ctrip_rating。',
            ],
            'comment_store_name' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl . ' / ' . $commentListUrl,
                'json_path' => 'data.hotelName / data.masterHotelName / data.storeName',
                'ownership_rule' => '点评页门店口径；来自系统绑定或接口返回，不从点评正文推断。',
                'storage_field' => 'online_daily_data.hotel_name + raw_data.metric_hotel_name',
                'source_interface' => 'getCommentNumV2 / getCommentList',
                'source_keys' => 'hotelName, masterHotelName, storeName, hotel_name',
                'target_value' => 'comment_store_name',
                'value_meaning' => '点评数据所属门店。',
                'notes' => '点评聚合字段；不保存点评内容、客人信息、房型或回复文本。',
            ],
            'comment_date' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl . ' / ' . $commentListUrl,
                'json_path' => 'data.date / data.dataDate / data.statDate / data.commentTime',
                'ownership_rule' => '点评统计日期口径；优先接口统计日期，缺失时保留缺失状态，不用采集时间伪造业务日期。',
                'storage_field' => 'online_daily_data.data_date',
                'source_interface' => 'getCommentNumV2 / getCommentList',
                'source_keys' => 'date, dataDate, statDate, commentTime, createTime, submitTime',
                'target_value' => 'comment_date',
                'value_meaning' => '点评统计或评论发生日期。',
                'notes' => '用于点评指标按日归集；不保存点评正文。',
            ],
            'comment_channel' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl . ' / ' . $commentListUrl,
                'json_path' => 'data.channel / data.channelName / data.platform / data.source',
                'ownership_rule' => '点评渠道维度；只保留渠道名，不保留用户身份或点评内容。',
                'storage_field' => 'online_daily_data.raw_data.dimension_values.comment_channel',
                'source_interface' => 'getCommentNumV2 / getCommentList',
                'source_keys' => 'channel, channelName, platform, source, commentChannel, bizType',
                'target_value' => 'comment_channel',
                'value_meaning' => '携程、去哪儿、同程旅行、智行等点评渠道。',
                'notes' => '渠道为点评指标维度，不作为全酒店客源渠道。',
            ],
            'comment_score' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl . ' / ' . $commentListUrl,
                'json_path' => 'data.score / data.commentScore / data.rating',
                'ownership_rule' => '点评分聚合口径；只保留评分数值，不保留点评明文。',
                'storage_field' => 'online_daily_data.comment_score + raw_data.metrics.comment_score',
                'source_interface' => 'getCommentNumV2 / getCommentList',
                'source_keys' => 'score, commentScore, rating, ratingall, HotelRating, ctripRatingall, totalScore, overallScore',
                'target_value' => 'comment_score',
                'value_meaning' => '点评分，单位分。',
                'notes' => '优先聚合接口评分；列表接口只用于评分聚合。',
            ],
            'comment_count' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl . ' / ' . $commentListUrl,
                'json_path' => 'data.commentCount / data.totalCount / data.allCount / {channel}Count.commentCount',
                'ownership_rule' => '点评数聚合口径；只保存计数，不保存点评内容。',
                'storage_field' => 'online_daily_data.data_value + raw_data.metrics.comment_count',
                'source_interface' => 'getCommentNumV2 / getCommentList',
                'source_keys' => 'commentCount, commentsCount, reviewCount, totalCommentCount, totalCount, allCount, ctripCount.commentCount, qunarCount.commentCount, elongCount.commentCount, zxCount.commentCount',
                'target_value' => 'comment_count',
                'value_meaning' => '点评数，单位条。',
                'notes' => '优先 getCommentNumV2 聚合计数；getCommentList 仅作行数复核。',
            ],
            'bad_review_count' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl . ' / ' . $commentListUrl,
                'json_path' => 'data.badReviewCount / data.negativeCount / {channel}Count.noRecommendCount / data.score',
                'ownership_rule' => '差评/不推荐数聚合口径；优先聚合接口计数，只有列表评分时按 0 < score < 4.0 聚合，不保存正文。',
                'storage_field' => 'online_daily_data.raw_data.metrics.bad_review_count',
                'source_interface' => 'getCommentNumV2 / getCommentList',
                'source_keys' => 'badReviewCount, negativeCommentCount, negativeCount, badCount, lowScoreCount, noRecommendCount, score, commentScore, rating',
                'target_value' => 'bad_review_count',
                'value_meaning' => '差评/不推荐数，单位条。',
                'notes' => '不保存点评内容、客人姓名、回复、房型、订单号或点评 ID。',
            ],
            'comment_unreply_count' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl,
                'json_path' => '{channel}Count.unReplyCount',
                'ownership_rule' => '点评未回复数聚合口径；只保存计数，不保存点评内容。',
                'storage_field' => 'online_daily_data.raw_data.metrics.comment_unreply_count',
                'source_interface' => 'getCommentNumV2',
                'source_keys' => 'unReplyCount, ctripCount.unReplyCount, qunarCount.unReplyCount, elongCount.unReplyCount, zxCount.unReplyCount, zhixingCount.unReplyCount, unreplyCount, unRepliedCount, unrepliedCount',
                'target_value' => 'unReplyCount',
                'value_meaning' => '未回复点评数，单位条。',
                'notes' => '可与 responseRate 互相复核；缺失时保持缺失，不补 0。',
            ],
            'comment_good_rate' => [
                'page_url' => $commentPage,
                'request_url' => $commentSummaryUrl,
                'json_path' => '{channel}Count.goodRate',
                'ownership_rule' => '点评好评率聚合口径；只保存百分比，不保存点评内容。',
                'storage_field' => 'online_daily_data.raw_data.metrics.comment_good_rate',
                'source_interface' => 'getCommentNumV2',
                'source_keys' => 'goodRate, ctripCount.goodRate, qunarCount.goodRate, elongCount.goodRate, zxCount.goodRate, zhixingCount.goodRate',
                'target_value' => 'goodRate',
                'value_meaning' => '点评好评率，单位 %。',
                'notes' => '0-1 小数入库时按百分比展示；缺失时保持缺失，不用差评数反推。',
            ],
            'reply_rate' => [
                'page_url' => $businessPage,
                'request_url' => $serverQuantityUrl,
                'json_path' => 'data.replyrate5m',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=reply_rate',
                'source_interface' => 'getDayReportServerQuantity',
                'source_keys' => 'replyrate5m',
                'target_value' => 'replyrate5m',
                'value_meaning' => '5分钟回复率',
                'notes' => '严格固定口径；IM 看板同名字段另行管理。',
            ],
            'reply_rank' => [
                'page_url' => $businessPage,
                'request_url' => $serverQuantityUrl,
                'json_path' => 'data.imScoreHtlrank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.reply_rank',
                'source_interface' => 'getDayReportServerQuantity',
                'source_keys' => 'imScoreHtlrank',
                'target_value' => 'imScoreHtlrank',
                'value_meaning' => '5分钟回复率竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入回复率。',
            ],
            'five_min_reply_rate' => [
                'page_url' => $userBehaviorImPage,
                'request_url' => 'https://ebooking.ctrip.com/userbehavior/getImIndex',
                'json_path' => 'data.replyRate5m / data.fiveMinReplyRate / data.replyRate',
                'ownership_rule' => '携程 OTA 用户行为 IM 看板；只代表平台 IM 会话口径。',
                'storage_field' => 'online_daily_data.flow_rate + raw_data.metrics.five_min_reply_rate',
                'source_interface' => 'getImIndex',
                'source_keys' => 'replyRate5m, fiveMinReplyRate, replyRate',
                'target_value' => 'five_min_reply_rate',
                'value_meaning' => 'IM 5分钟回复率。',
                'notes' => 'IM 看板字段，不与点评回复率 comment_response_rate 混用。',
            ],
            'manual_reply_rate' => [
                'page_url' => $userBehaviorImPage,
                'request_url' => 'https://ebooking.ctrip.com/userbehavior/getImIndex',
                'json_path' => 'data.manualReplyRate / data.humanReplyRate / data.manualreplyrate5m',
                'ownership_rule' => '携程 OTA 用户行为 IM 看板；只代表平台 IM 会话口径。',
                'storage_field' => 'online_daily_data.flow_rate + raw_data.metrics.manual_reply_rate',
                'source_interface' => 'getImIndex',
                'source_keys' => 'manualReplyRate, humanReplyRate, manualreplyrate5m, manualreplyRate2m',
                'target_value' => 'manual_reply_rate',
                'value_meaning' => 'IM 5分钟人工回复率。',
                'notes' => '顶部指标卡字段，单位 %。',
            ],
            'robot_resolution_rate' => [
                'page_url' => $userBehaviorImPage,
                'request_url' => 'https://ebooking.ctrip.com/userbehavior/getImIndex',
                'json_path' => 'data.robotResolutionRate / data.robotResolveRate / data.aisolverate',
                'ownership_rule' => '携程 OTA 用户行为 IM 看板；只代表平台 IM 会话口径。',
                'storage_field' => 'online_daily_data.raw_data.metrics.robot_resolution_rate',
                'source_interface' => 'getImIndex',
                'source_keys' => 'robotResolutionRate, robotResolveRate, aisolverate',
                'target_value' => 'robot_resolution_rate',
                'value_meaning' => '机器人解决率。',
                'notes' => '顶部指标卡字段，单位 %。',
            ],
            'im_rank' => [
                'page_url' => $userBehaviorImPage,
                'request_url' => 'https://ebooking.ctrip.com/userbehavior/getImIndex',
                'json_path' => 'data.rank / data.replyrate5mRank / data.manualreplyrate5mRank / data.aisolverateRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.im_rank',
                'source_interface' => 'getImIndex',
                'source_keys' => 'rank, rank2, replyrate5mRank, manualreplyrate5mRank, aisolverateRank',
                'target_value' => 'im_rank',
                'value_meaning' => 'IM 竞争圈排名。',
                'notes' => '排名只进入 raw_data.rank_metrics，不写入回复率。',
            ],
            'session_count' => [
                'page_url' => $userBehaviorImPage,
                'request_url' => 'https://ebooking.ctrip.com/userbehavior/getImDateDistribute / getImSessionDistribute / getImOrderConversionDetail',
                'json_path' => 'data[].sessionCount / data[].totalSession / data.validsnum',
                'ownership_rule' => '携程 OTA 用户行为 IM 看板；只代表平台 IM 会话口径。',
                'storage_field' => 'online_daily_data.data_value + raw_data.metrics.session_count',
                'source_interface' => 'getImDateDistribute / getImSessionDistribute / getImOrderConversionDetail',
                'source_keys' => 'sessionCount, totalSession, totalSessions, totalsessions, conversationCount, validsnum',
                'target_value' => 'session_count',
                'value_meaning' => 'IM 会话量。',
                'notes' => '用于趋势图、时间分布和会话明细弹窗。',
            ],
            'manual_session_count' => [
                'page_url' => $userBehaviorImPage,
                'request_url' => 'https://ebooking.ctrip.com/userbehavior/getImSessionDistribute / getImOrderConversionDetail',
                'json_path' => 'data[].manualSessionCount / data.manualreplyin5mnum / data.replynum',
                'ownership_rule' => '携程 OTA 用户行为 IM 看板；只代表平台 IM 会话口径。',
                'storage_field' => 'online_daily_data.raw_data.metrics.manual_session_count',
                'source_interface' => 'getImSessionDistribute / getImOrderConversionDetail',
                'source_keys' => 'manualSessionCount, humanSessionCount, manualreplyin5mnum, replynum',
                'target_value' => 'manual_session_count',
                'value_meaning' => '人工会话量/回复中用户数。',
                'notes' => '会话明细字段，缺失时保持缺采状态。',
            ],
            'robot_session_count' => [
                'page_url' => $userBehaviorImPage,
                'request_url' => 'https://ebooking.ctrip.com/userbehavior/getImSessionDistribute',
                'json_path' => 'data[].robotSessionCount / data[].aisolveratenum',
                'ownership_rule' => '携程 OTA 用户行为 IM 看板；只代表平台 IM 会话口径。',
                'storage_field' => 'online_daily_data.raw_data.metrics.robot_session_count',
                'source_interface' => 'getImSessionDistribute',
                'source_keys' => 'robotSessionCount, aisolveratenum',
                'target_value' => 'robot_session_count',
                'value_meaning' => '机器人会话量。',
                'notes' => '会话明细字段，缺失时保持缺采状态。',
            ],
            'im_order_conversion_rate' => [
                'page_url' => $userBehaviorImPage,
                'request_url' => 'https://ebooking.ctrip.com/userbehavior/getImOrderConversionRateByDay / getImOrderConversionDetail',
                'json_path' => 'data[].orderConversionRate / data.htlreplyCr',
                'ownership_rule' => '携程 OTA 用户行为 IM 看板；只代表平台 IM 会话转化口径。',
                'storage_field' => 'online_daily_data.flow_rate + raw_data.metrics.im_order_conversion_rate',
                'source_interface' => 'getImOrderConversionRateByDay / getImOrderConversionDetail',
                'source_keys' => 'orderConversionRate, conversionRate, htlreplyCr',
                'target_value' => 'im_order_conversion_rate',
                'value_meaning' => 'IM 客人转化率。',
                'notes' => 'IM 转化率字段，单位 %。',
            ],
            'hotel_collect' => [
                'page_url' => $businessPage,
                'request_url' => $serverQuantityUrl,
                'json_path' => 'data.hotelCollect',
                'ownership_rule' => $selfRule,
                'storage_field' => 'ota_ctrip_metric_facts.metric_key=hotel_collect',
                'source_interface' => 'getDayReportServerQuantity',
                'source_keys' => 'hotelCollect',
                'target_value' => 'hotelCollect',
                'value_meaning' => '酒店收藏数',
                'notes' => '严格固定取 data.hotelCollect。',
            ],
            'hotel_collect_rank' => [
                'page_url' => $businessPage,
                'request_url' => $serverQuantityUrl,
                'json_path' => 'data.hotelCollectRank',
                'ownership_rule' => $rankRule,
                'storage_field' => 'online_daily_data.raw_data.rank_metrics.hotel_collect_rank',
                'source_interface' => 'getDayReportServerQuantity',
                'source_keys' => 'hotelCollectRank',
                'target_value' => 'hotelCollectRank',
                'value_meaning' => '酒店收藏数竞争圈排名',
                'notes' => '排名只进入 rank_metrics/data_value 展示，不写入收藏数。',
            ],
            'ad_cost' => [
                'page_url' => self::CTRIP_ADS_PAGE_URL,
                'request_url' => self::CTRIP_ADS_REQUEST_URL,
                'json_path' => 'records[].todayCost',
                'ownership_rule' => '广告口径：仅写 advertising，不得混入 order_amount/revenue。',
                'storage_field' => 'online_daily_data.amount where data_type=advertising',
                'source_interface' => 'queryCampaignReportList',
                'source_keys' => 'records[].todayCost, records[].cashCost, records[].bonusCost',
                'target_value' => 'todayCost',
                'value_meaning' => '携程广告花费',
                'notes' => '广告成本只进入 advertising 数据层，不进入经营销售额。',
            ],
        ][$fieldKey] ?? [];
    }
}
