CREATE TABLE IF NOT EXISTS `ai_model_call_logs` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `request_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '请求ID',
  `module` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '业务模块',
  `scenario` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '调用场景',
  `hotel_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '酒店ID',
  `user_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  `provider` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '模型服务商',
  `model_key` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '模型配置Key',
  `model_name` VARCHAR(150) NOT NULL DEFAULT '' COMMENT '实际模型名称',
  `prompt_version` VARCHAR(120) NOT NULL DEFAULT '' COMMENT 'Prompt版本',
  `prompt_hash` CHAR(64) NOT NULL DEFAULT '' COMMENT 'Prompt SHA256',
  `prompt_preview` VARCHAR(1000) DEFAULT NULL COMMENT 'Prompt脱敏预览',
  `prompt_length` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Prompt长度',
  `request_payload_size` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '请求体大小',
  `http_status` INT NOT NULL DEFAULT 0 COMMENT 'HTTP状态码',
  `latency_ms` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '耗时毫秒',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '调用状态:success/failed/blocked',
  `error_type` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '错误类型',
  `error_message` VARCHAR(500) DEFAULT NULL COMMENT '脱敏错误信息',
  `response_hash` CHAR(64) NOT NULL DEFAULT '' COMMENT '响应SHA256',
  `response_preview` VARCHAR(1000) DEFAULT NULL COMMENT '响应脱敏预览',
  `response_length` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '响应长度',
  `confidence_score` DECIMAL(4,3) DEFAULT NULL COMMENT '置信度0-1',
  `low_confidence` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否低置信度',
  `human_confirmation_required` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否需要人工确认',
  `human_confirmation_status` VARCHAR(30) NOT NULL DEFAULT 'not_required' COMMENT '人工确认状态',
  `human_confirmed_by` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '确认人ID',
  `human_confirmed_at` DATETIME DEFAULT NULL COMMENT '确认时间',
  `human_confirmation_note` VARCHAR(500) DEFAULT NULL COMMENT '确认备注',
  `knowledge_sources_json` JSON DEFAULT NULL COMMENT '知识/数据来源引用',
  `evaluation_set` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '评估集标识',
  `eval_case_id` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '评估集用例ID',
  `governance_json` JSON DEFAULT NULL COMMENT '治理扩展信息',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_ai_model_call_logs_created_at` (`created_at`),
  KEY `idx_ai_model_call_logs_module` (`module`, `scenario`),
  KEY `idx_ai_model_call_logs_model` (`provider`, `model_key`),
  KEY `idx_ai_model_call_logs_status` (`status`, `low_confidence`),
  KEY `idx_ai_model_call_logs_prompt` (`prompt_version`, `prompt_hash`),
  KEY `idx_ai_model_call_logs_request` (`request_id`),
  KEY `idx_ai_model_call_logs_confirmation` (`human_confirmation_status`, `human_confirmation_required`),
  KEY `idx_ai_model_call_logs_eval` (`evaluation_set`, `eval_case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI模型调用治理日志';

CREATE TABLE IF NOT EXISTS `ai_prompt_versions` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `prompt_key` VARCHAR(120) NOT NULL COMMENT 'Prompt Key',
  `version` VARCHAR(80) NOT NULL COMMENT '版本号',
  `scenario` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '调用场景',
  `content_hash` CHAR(64) NOT NULL DEFAULT '' COMMENT '内容SHA256',
  `description` VARCHAR(500) DEFAULT NULL COMMENT '版本说明',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态:active/archived',
  `created_by` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_ai_prompt_versions_key_version` (`prompt_key`, `version`),
  KEY `idx_ai_prompt_versions_status` (`status`),
  KEY `idx_ai_prompt_versions_scenario` (`scenario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI Prompt版本登记';

CREATE TABLE IF NOT EXISTS `ai_evaluation_cases` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `case_key` VARCHAR(120) NOT NULL COMMENT '评估用例Key',
  `scenario` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '评估场景',
  `prompt_version` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '关联Prompt版本',
  `input_json` JSON DEFAULT NULL COMMENT '输入样本',
  `expected_json` JSON DEFAULT NULL COMMENT '期望结果',
  `metric_json` JSON DEFAULT NULL COMMENT '评估指标',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态:active/archived',
  `created_by` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_ai_evaluation_cases_case_key` (`case_key`),
  KEY `idx_ai_evaluation_cases_scenario` (`scenario`),
  KEY `idx_ai_evaluation_cases_prompt` (`prompt_version`),
  KEY `idx_ai_evaluation_cases_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI评估集用例';
