CREATE TABLE IF NOT EXISTS `ai_daily_reports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED DEFAULT NULL COMMENT 'tenant id, aligned to hotel scope',
  `hotel_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'hotel id',
  `report_date` DATE NOT NULL COMMENT 'business date, normally yesterday',
  `status` VARCHAR(30) NOT NULL DEFAULT 'generated' COMMENT 'generated/archived',
  `generation_mode` VARCHAR(30) NOT NULL DEFAULT 'rule' COMMENT 'rule/llm',
  `model_key` VARCHAR(80) NOT NULL DEFAULT '' COMMENT 'AI model key',
  `model_status` VARCHAR(30) NOT NULL DEFAULT 'not_requested' COMMENT 'ok/failed/not_requested',
  `model_message` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'AI model issue message',
  `summary` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'daily summary',
  `yesterday_result_json` JSON DEFAULT NULL COMMENT 'yesterday result metrics',
  `abnormal_metrics_json` JSON DEFAULT NULL COMMENT 'abnormal metric list',
  `competitor_changes_json` JSON DEFAULT NULL COMMENT 'competitor signal changes',
  `data_gaps_json` JSON DEFAULT NULL COMMENT 'explicit missing data list',
  `recommended_actions_json` JSON DEFAULT NULL COMMENT 'up to 3 recommended actions',
  `source_refs_json` JSON DEFAULT NULL COMMENT 'source references',
  `snapshot_json` JSON DEFAULT NULL COMMENT 'input data snapshot, excludes guest privacy fields',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'creator user id',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_daily_reports_hotel_date` (`hotel_id`, `report_date`),
  KEY `idx_ai_daily_reports_tenant_date` (`tenant_id`, `report_date`),
  KEY `idx_ai_daily_reports_hotel_status` (`hotel_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI daily operating report table';
