-- Additive evidence and comparability contract for OTA public competitor rates.
-- Existing rows intentionally remain unverified and are reference-only.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `competitor_price_log`
  ADD COLUMN IF NOT EXISTS `ota_hotel_id` varchar(80) DEFAULT NULL COMMENT 'OTA酒店标识，不作为宿析门店范围' AFTER `hotel_id`,
  ADD COLUMN IF NOT EXISTS `collected_at` datetime DEFAULT NULL COMMENT '页面事实采集时间' AFTER `fetch_time`,
  ADD COLUMN IF NOT EXISTS `source_method` varchar(40) NOT NULL DEFAULT '' COMMENT '采集方式' AFTER `collected_at`,
  ADD COLUMN IF NOT EXISTS `source_ref` varchar(500) NOT NULL DEFAULT '' COMMENT '公开来源引用或内部证据引用' AFTER `source_method`,
  ADD COLUMN IF NOT EXISTS `validation_status` varchar(32) NOT NULL DEFAULT 'unverified' COMMENT 'normal/valid/verified/incomplete/failed' AFTER `source_ref`,
  ADD COLUMN IF NOT EXISTS `readback_verified` tinyint(1) NOT NULL DEFAULT 0 COMMENT '保存后回读校验' AFTER `validation_status`,
  ADD COLUMN IF NOT EXISTS `failure_reason` varchar(500) NOT NULL DEFAULT '' COMMENT '采集或校验失败原因' AFTER `readback_verified`,
  ADD COLUMN IF NOT EXISTS `check_in_date` date DEFAULT NULL COMMENT '入住日期' AFTER `failure_reason`,
  ADD COLUMN IF NOT EXISTS `check_out_date` date DEFAULT NULL COMMENT '离店日期' AFTER `check_in_date`,
  ADD COLUMN IF NOT EXISTS `nights` smallint unsigned DEFAULT NULL COMMENT '晚数' AFTER `check_out_date`,
  ADD COLUMN IF NOT EXISTS `adults` tinyint unsigned DEFAULT NULL COMMENT '成人数' AFTER `nights`,
  ADD COLUMN IF NOT EXISTS `children` tinyint unsigned DEFAULT NULL COMMENT '儿童数' AFTER `adults`,
  ADD COLUMN IF NOT EXISTS `room_type_key` varchar(160) NOT NULL DEFAULT '' COMMENT '可比房型键' AFTER `children`,
  ADD COLUMN IF NOT EXISTS `ota_product_id` varchar(120) NOT NULL DEFAULT '' COMMENT 'OTA产品标识' AFTER `room_type_key`,
  ADD COLUMN IF NOT EXISTS `rate_plan_key` varchar(160) NOT NULL DEFAULT '' COMMENT '可比价型键' AFTER `ota_product_id`,
  ADD COLUMN IF NOT EXISTS `package_name` varchar(160) NOT NULL DEFAULT '' COMMENT '套餐名称' AFTER `rate_plan_key`,
  ADD COLUMN IF NOT EXISTS `breakfast` varchar(80) NOT NULL DEFAULT '' COMMENT '早餐口径' AFTER `package_name`,
  ADD COLUMN IF NOT EXISTS `cancellation_policy` varchar(500) NOT NULL DEFAULT '' COMMENT '取消政策口径' AFTER `breakfast`,
  ADD COLUMN IF NOT EXISTS `payment_mode` varchar(80) NOT NULL DEFAULT '' COMMENT '支付方式' AFTER `cancellation_policy`,
  ADD COLUMN IF NOT EXISTS `tax_fee_included` tinyint(1) DEFAULT NULL COMMENT '价格是否含税费' AFTER `payment_mode`,
  ADD COLUMN IF NOT EXISTS `price_basis` varchar(80) NOT NULL DEFAULT '' COMMENT '每间每晚等价格基准' AFTER `tax_fee_included`,
  ADD COLUMN IF NOT EXISTS `currency` char(3) NOT NULL DEFAULT '' COMMENT 'ISO币种' AFTER `price_basis`,
  ADD COLUMN IF NOT EXISTS `availability` varchar(32) NOT NULL DEFAULT '' COMMENT '仅表示OTA渠道公开可订状态' AFTER `currency`,
  ADD COLUMN IF NOT EXISTS `comparison_key` char(64) NOT NULL DEFAULT '' COMMENT '可比维度哈希，不含竞对身份' AFTER `availability`,
  ADD COLUMN IF NOT EXISTS `content_hash` char(64) NOT NULL DEFAULT '' COMMENT '结构化事实哈希' AFTER `comparison_key`,
  ADD INDEX IF NOT EXISTS `idx_competitor_price_comparable` (`store_id`, `platform`, `check_in_date`, `validation_status`, `readback_verified`),
  ADD INDEX IF NOT EXISTS `idx_competitor_price_comparison_key` (`comparison_key`, `collected_at`);

ALTER TABLE `competitor_analysis`
  ADD COLUMN IF NOT EXISTS `collected_at` datetime DEFAULT NULL COMMENT '页面事实采集时间' AFTER `analysis_date`,
  ADD COLUMN IF NOT EXISTS `source_method` varchar(40) NOT NULL DEFAULT '' COMMENT '采集方式' AFTER `collected_at`,
  ADD COLUMN IF NOT EXISTS `source_ref` varchar(500) NOT NULL DEFAULT '' COMMENT '公开来源引用或内部证据引用' AFTER `source_method`,
  ADD COLUMN IF NOT EXISTS `validation_status` varchar(32) NOT NULL DEFAULT 'unverified' COMMENT 'normal/valid/verified/incomplete/failed' AFTER `source_ref`,
  ADD COLUMN IF NOT EXISTS `readback_verified` tinyint(1) NOT NULL DEFAULT 0 COMMENT '保存后回读校验' AFTER `validation_status`,
  ADD COLUMN IF NOT EXISTS `failure_reason` varchar(500) NOT NULL DEFAULT '' COMMENT '采集或校验失败原因' AFTER `readback_verified`,
  ADD COLUMN IF NOT EXISTS `check_in_date` date DEFAULT NULL COMMENT '入住日期' AFTER `failure_reason`,
  ADD COLUMN IF NOT EXISTS `check_out_date` date DEFAULT NULL COMMENT '离店日期' AFTER `check_in_date`,
  ADD COLUMN IF NOT EXISTS `nights` smallint unsigned DEFAULT NULL COMMENT '晚数' AFTER `check_out_date`,
  ADD COLUMN IF NOT EXISTS `adults` tinyint unsigned DEFAULT NULL COMMENT '成人数' AFTER `nights`,
  ADD COLUMN IF NOT EXISTS `children` tinyint unsigned DEFAULT NULL COMMENT '儿童数' AFTER `adults`,
  ADD COLUMN IF NOT EXISTS `room_type_key` varchar(160) NOT NULL DEFAULT '' COMMENT '可比房型键' AFTER `children`,
  ADD COLUMN IF NOT EXISTS `rate_plan_key` varchar(160) NOT NULL DEFAULT '' COMMENT '可比价型键' AFTER `room_type_key`,
  ADD COLUMN IF NOT EXISTS `breakfast` varchar(80) NOT NULL DEFAULT '' COMMENT '早餐口径' AFTER `rate_plan_key`,
  ADD COLUMN IF NOT EXISTS `cancellation_policy` varchar(500) NOT NULL DEFAULT '' COMMENT '取消政策口径' AFTER `breakfast`,
  ADD COLUMN IF NOT EXISTS `payment_mode` varchar(80) NOT NULL DEFAULT '' COMMENT '支付方式' AFTER `cancellation_policy`,
  ADD COLUMN IF NOT EXISTS `tax_fee_included` tinyint(1) DEFAULT NULL COMMENT '价格是否含税费' AFTER `payment_mode`,
  ADD COLUMN IF NOT EXISTS `price_basis` varchar(80) NOT NULL DEFAULT '' COMMENT '每间每晚等价格基准' AFTER `tax_fee_included`,
  ADD COLUMN IF NOT EXISTS `currency` char(3) NOT NULL DEFAULT '' COMMENT 'ISO币种' AFTER `price_basis`,
  ADD COLUMN IF NOT EXISTS `availability` varchar(32) NOT NULL DEFAULT '' COMMENT '仅表示OTA渠道公开可订状态' AFTER `currency`,
  ADD COLUMN IF NOT EXISTS `comparison_key` char(64) NOT NULL DEFAULT '' COMMENT '可比维度哈希，不含竞对身份' AFTER `availability`,
  ADD COLUMN IF NOT EXISTS `content_hash` char(64) NOT NULL DEFAULT '' COMMENT '结构化事实哈希' AFTER `comparison_key`,
  ADD INDEX IF NOT EXISTS `idx_competitor_analysis_comparable` (`hotel_id`, `ota_platform`, `check_in_date`, `validation_status`, `readback_verified`),
  ADD INDEX IF NOT EXISTS `idx_competitor_analysis_comparison_key` (`comparison_key`, `collected_at`);
