CREATE TABLE IF NOT EXISTS `opening_projects` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hotel_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '酒店ID',
  `project_name` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '开业项目名称',
  `hotel_name` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '酒店名称',
  `city` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '城市',
  `brand` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '品牌',
  `positioning` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '定位',
  `room_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '房间数',
  `opening_date` DATE NOT NULL COMMENT '计划开业日期',
  `manager_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '项目负责人',
  `status` VARCHAR(30) NOT NULL DEFAULT 'preparing' COMMENT '项目状态',
  `overall_score` DECIMAL(5,1) NOT NULL DEFAULT 0 COMMENT '开业准备总评分',
  `risk_level` VARCHAR(20) NOT NULL DEFAULT 'low' COMMENT '风险等级',
  `ai_penetration_rate` DECIMAL(5,1) NOT NULL DEFAULT 0 COMMENT 'AI渗透率',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_opening_projects_hotel_status` (`hotel_id`, `status`),
  KEY `idx_opening_projects_opening_date` (`opening_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='开业项目表';

CREATE TABLE IF NOT EXISTS `opening_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '开业项目ID',
  `category` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '检查分类',
  `task_name` VARCHAR(160) NOT NULL DEFAULT '' COMMENT '检查项名称',
  `task_desc` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '检查项说明',
  `is_core` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否核心事项',
  `owner_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '负责人',
  `collaborator_name` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '协同人',
  `deadline` DATE DEFAULT NULL COMMENT '截止时间',
  `status` VARCHAR(30) NOT NULL DEFAULT 'todo' COMMENT '状态 todo/doing/done/blocked',
  `risk_level` VARCHAR(20) NOT NULL DEFAULT 'low' COMMENT '风险等级',
  `acceptance_standard` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '验收标准',
  `ai_suggestion` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'AI建议',
  `remark` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_opening_tasks_project_category` (`project_id`, `category`),
  KEY `idx_opening_tasks_project_status` (`project_id`, `status`),
  KEY `idx_opening_tasks_deadline` (`deadline`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='开业检查项表';
