CREATE TABLE IF NOT EXISTS `ota_meituan_reviews` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `system_hotel_id` int unsigned NOT NULL COMMENT 'System hotel id',
  `review_id` varchar(120) NOT NULL COMMENT 'Meituan review id',
  `meituan_user_id` varchar(120) NOT NULL DEFAULT '',
  `source_username` varchar(160) NOT NULL DEFAULT '',
  `review_date` date DEFAULT NULL,
  `checkin_date` date DEFAULT NULL,
  `room_name` varchar(180) NOT NULL DEFAULT '',
  `room_name_prefix` varchar(120) NOT NULL DEFAULT '',
  `score` decimal(5,2) DEFAULT NULL,
  `content` text NULL,
  `raw_review_json` longtext NOT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ota_meituan_review_hotel_review` (`system_hotel_id`, `review_id`),
  KEY `idx_ota_meituan_review_date` (`system_hotel_id`, `checkin_date`),
  KEY `idx_ota_meituan_review_user` (`system_hotel_id`, `meituan_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Meituan review order matching review pool';

CREATE TABLE IF NOT EXISTS `ota_meituan_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `system_hotel_id` int unsigned NOT NULL COMMENT 'System hotel id',
  `order_id` varchar(100) NOT NULL COMMENT 'Meituan order id',
  `meituan_user_id` varchar(120) NOT NULL DEFAULT '',
  `guest_name_masked` varchar(120) NOT NULL DEFAULT '',
  `arrival_date` date DEFAULT NULL,
  `departure_date` date DEFAULT NULL,
  `room_name` varchar(180) NOT NULL DEFAULT '',
  `room_name_prefix` varchar(120) NOT NULL DEFAULT '',
  `order_status` varchar(80) NOT NULL DEFAULT '',
  `phone_masked` varchar(32) NOT NULL DEFAULT '',
  `phone_last4` char(4) NOT NULL DEFAULT '',
  `phone_status` varchar(40) NOT NULL DEFAULT 'not_returned_by_order_api',
  `phone_source` varchar(80) NOT NULL DEFAULT 'not_returned',
  `raw_order_json` longtext NOT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ota_meituan_order_hotel_order` (`system_hotel_id`, `order_id`),
  KEY `idx_ota_meituan_order_user` (`system_hotel_id`, `meituan_user_id`),
  KEY `idx_ota_meituan_order_arrival_room` (`system_hotel_id`, `arrival_date`, `room_name_prefix`),
  KEY `idx_ota_meituan_order_phone_last4` (`system_hotel_id`, `phone_last4`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Meituan review order matching order pool';

CREATE TABLE IF NOT EXISTS `ota_meituan_review_order_matches` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `system_hotel_id` int unsigned NOT NULL COMMENT 'System hotel id',
  `review_id` varchar(120) NOT NULL COMMENT 'Meituan review id',
  `order_id` varchar(100) NOT NULL DEFAULT '',
  `meituan_user_id` varchar(120) NOT NULL DEFAULT '',
  `guest_name_masked` varchar(120) NOT NULL DEFAULT '',
  `match_status` varchar(40) NOT NULL DEFAULT 'unmatched' COMMENT 'found/candidate_review_order/needs_ops/out_of_coverage/matched/unbound',
  `match_method` varchar(80) NOT NULL DEFAULT '',
  `confidence` varchar(30) NOT NULL DEFAULT 'none',
  `candidate_orders_json` longtext NOT NULL,
  `evidence_json` longtext NOT NULL,
  `bound_by` int unsigned DEFAULT NULL,
  `bound_at` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ota_meituan_review_match_review` (`system_hotel_id`, `review_id`),
  KEY `idx_ota_meituan_review_match_order` (`system_hotel_id`, `order_id`),
  KEY `idx_ota_meituan_review_match_status` (`system_hotel_id`, `match_status`, `confidence`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Meituan review order matching result';
