-- Ctrip OTA metric tables.
-- Scope: Ctrip eBooking OTA channel data only; excludes biztravel modules for now.
-- This migration keeps online_daily_data compatible and stores new Ctrip fields in merged fact/entity tables.

CREATE TABLE IF NOT EXISTS `ota_ctrip_capture_runs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned DEFAULT NULL,
  `system_hotel_id` int unsigned DEFAULT NULL,
  `ota_hotel_id` varchar(64) NOT NULL DEFAULT '',
  `hotel_name` varchar(160) NOT NULL DEFAULT '',
  `profile_id` varchar(80) NOT NULL DEFAULT '',
  `data_date` date DEFAULT NULL,
  `source` varchar(20) NOT NULL DEFAULT 'ctrip',
  `capture_mode` varchar(40) NOT NULL DEFAULT 'browser_profile',
  `capture_sections` text NULL,
  `auth_status` varchar(30) NOT NULL DEFAULT '',
  `gate_status` varchar(30) NOT NULL DEFAULT '',
  `gap_status` varchar(30) NOT NULL DEFAULT '',
  `response_count` int unsigned NOT NULL DEFAULT 0,
  `fact_count` int unsigned NOT NULL DEFAULT 0,
  `standard_row_count` int unsigned NOT NULL DEFAULT 0,
  `evidence_file` varchar(255) NOT NULL DEFAULT '',
  `started_at` datetime DEFAULT NULL,
  `captured_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `created_by` int unsigned DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ctrip_runs_evidence` (`evidence_file`),
  KEY `idx_ctrip_runs_tenant_date` (`tenant_id`, `data_date`),
  KEY `idx_ctrip_runs_hotel_date` (`system_hotel_id`, `data_date`),
  KEY `idx_ctrip_runs_status` (`source`, `gate_status`, `gap_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Ctrip OTA capture run metadata';

CREATE TABLE IF NOT EXISTS `ota_ctrip_metric_catalog` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `metric_key` varchar(120) NOT NULL,
  `metric_label` varchar(160) NOT NULL DEFAULT '',
  `category` varchar(60) NOT NULL DEFAULT '',
  `metric_scope` varchar(40) NOT NULL DEFAULT 'ota_channel',
  `data_type` varchar(50) NOT NULL DEFAULT '',
  `unit` varchar(30) NOT NULL DEFAULT '',
  `value_type` varchar(30) NOT NULL DEFAULT '',
  `selection_status` varchar(30) NOT NULL DEFAULT 'selected',
  `build_decision` varchar(60) NOT NULL DEFAULT '',
  `target_table` varchar(80) NOT NULL DEFAULT '',
  `capture_status` varchar(60) NOT NULL DEFAULT '',
  `merge_group` varchar(80) NOT NULL DEFAULT '',
  `sections_json` text NULL,
  `endpoints_json` text NULL,
  `source_keys_json` text NULL,
  `is_common_dimension` tinyint NOT NULL DEFAULT 0,
  `is_biztravel` tinyint NOT NULL DEFAULT 0,
  `needs_user_site` tinyint NOT NULL DEFAULT 0,
  `notes` text NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ctrip_metric_catalog_key` (`metric_key`, `category`),
  KEY `idx_ctrip_metric_catalog_select` (`selection_status`, `build_decision`),
  KEY `idx_ctrip_metric_catalog_target` (`target_table`, `capture_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Ctrip OTA field catalog and build selection';

CREATE TABLE IF NOT EXISTS `ota_ctrip_metric_facts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `run_id` bigint unsigned DEFAULT NULL,
  `tenant_id` int unsigned DEFAULT NULL,
  `system_hotel_id` int unsigned DEFAULT NULL,
  `ota_hotel_id` varchar(64) NOT NULL DEFAULT '',
  `hotel_name` varchar(160) NOT NULL DEFAULT '',
  `data_date` date DEFAULT NULL,
  `source` varchar(20) NOT NULL DEFAULT 'ctrip',
  `capture_section` varchar(80) NOT NULL DEFAULT '',
  `endpoint_id` varchar(120) NOT NULL DEFAULT '',
  `metric_key` varchar(120) NOT NULL DEFAULT '',
  `metric_label` varchar(160) NOT NULL DEFAULT '',
  `category` varchar(60) NOT NULL DEFAULT '',
  `data_type` varchar(50) NOT NULL DEFAULT '',
  `metric_scope` varchar(40) NOT NULL DEFAULT 'ota_channel',
  `unit` varchar(30) NOT NULL DEFAULT '',
  `value_type` varchar(30) NOT NULL DEFAULT '',
  `value_decimal` decimal(20,4) DEFAULT NULL,
  `value_text` varchar(1000) DEFAULT NULL,
  `value_json` longtext NULL,
  `compare_type` varchar(40) NOT NULL DEFAULT '',
  `entity_type` varchar(60) NOT NULL DEFAULT '',
  `entity_key` varchar(160) NOT NULL DEFAULT '',
  `entity_name` varchar(255) NOT NULL DEFAULT '',
  `dimension_key` varchar(255) NOT NULL DEFAULT '',
  `dimension_label` varchar(255) NOT NULL DEFAULT '',
  `source_key` varchar(160) NOT NULL DEFAULT '',
  `source_path` varchar(700) NOT NULL DEFAULT '',
  `source_hash` char(64) NOT NULL DEFAULT '',
  `source_url` varchar(1000) NOT NULL DEFAULT '',
  `raw_data` longtext NULL,
  `capture_status` varchar(60) NOT NULL DEFAULT '',
  `captured_at` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ctrip_metric_fact` (`system_hotel_id`, `data_date`, `capture_section`, `endpoint_id`, `metric_key`, `source_hash`),
  KEY `idx_ctrip_metric_facts_run` (`run_id`),
  KEY `idx_ctrip_metric_facts_tenant_date` (`tenant_id`, `data_date`),
  KEY `idx_ctrip_metric_facts_hotel_metric` (`system_hotel_id`, `metric_key`, `data_date`),
  KEY `idx_ctrip_metric_facts_section` (`capture_section`, `endpoint_id`, `metric_key`),
  KEY `idx_ctrip_metric_facts_entity` (`entity_type`, `entity_key`, `data_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Merged Ctrip OTA scalar metric facts';

CREATE TABLE IF NOT EXISTS `ota_ctrip_entity_snapshots` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `run_id` bigint unsigned DEFAULT NULL,
  `tenant_id` int unsigned DEFAULT NULL,
  `system_hotel_id` int unsigned DEFAULT NULL,
  `ota_hotel_id` varchar(64) NOT NULL DEFAULT '',
  `data_date` date DEFAULT NULL,
  `source` varchar(20) NOT NULL DEFAULT 'ctrip',
  `capture_section` varchar(80) NOT NULL DEFAULT '',
  `endpoint_id` varchar(120) NOT NULL DEFAULT '',
  `entity_type` varchar(60) NOT NULL DEFAULT '',
  `entity_key` varchar(160) NOT NULL DEFAULT '',
  `entity_name` varchar(255) NOT NULL DEFAULT '',
  `attributes_json` longtext NULL,
  `capture_status` varchar(60) NOT NULL DEFAULT '',
  `first_seen_at` datetime DEFAULT NULL,
  `last_seen_at` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ctrip_entity_snapshot` (`system_hotel_id`, `source`, `entity_type`, `entity_key`, `data_date`),
  KEY `idx_ctrip_entity_run` (`run_id`),
  KEY `idx_ctrip_entity_tenant_date` (`tenant_id`, `data_date`),
  KEY `idx_ctrip_entity_type` (`entity_type`, `entity_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Ctrip OTA room/competitor/ad/user/event entity snapshots';

CREATE TABLE IF NOT EXISTS `ota_ctrip_capture_gaps` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `run_id` bigint unsigned DEFAULT NULL,
  `tenant_id` int unsigned DEFAULT NULL,
  `system_hotel_id` int unsigned DEFAULT NULL,
  `ota_hotel_id` varchar(64) NOT NULL DEFAULT '',
  `data_date` date DEFAULT NULL,
  `capture_section` varchar(80) NOT NULL DEFAULT '',
  `endpoint_id` varchar(120) NOT NULL DEFAULT '',
  `metric_key` varchar(120) NOT NULL DEFAULT '',
  `metric_label` varchar(160) NOT NULL DEFAULT '',
  `gap_type` varchar(60) NOT NULL DEFAULT '',
  `gap_status` varchar(60) NOT NULL DEFAULT 'needs_user_site',
  `expected_source_keys` text NULL,
  `user_site_url` varchar(1000) NOT NULL DEFAULT '',
  `evidence_note` text NULL,
  `evidence_file` varchar(255) NOT NULL DEFAULT '',
  `resolved_at` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ctrip_gap_field` (`system_hotel_id`, `data_date`, `capture_section`, `endpoint_id`, `metric_key`),
  KEY `idx_ctrip_gaps_run` (`run_id`),
  KEY `idx_ctrip_gaps_tenant` (`tenant_id`, `gap_status`),
  KEY `idx_ctrip_gaps_section` (`capture_section`, `endpoint_id`, `metric_key`),
  KEY `idx_ctrip_gaps_hotel_date` (`system_hotel_id`, `data_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Ctrip OTA missing endpoint and field gaps';
