CREATE TABLE IF NOT EXISTS `ai_daily_report_broadcast_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL COMMENT 'tenant id resolved from the hotel scope',
  `hotel_id` INT UNSIGNED NOT NULL COMMENT 'system hotel id',
  `business_date` DATE NOT NULL COMMENT 'business date represented by the broadcast',
  `version_no` INT UNSIGNED NOT NULL COMMENT 'immutable version within one hotel and business date',
  `facts_broadcast_status` VARCHAR(40) NOT NULL COMMENT 'facts_broadcast_ready/waiting_data/collection_failed',
  `analysis_status` VARCHAR(40) NOT NULL DEFAULT 'analysis_blocked' COMMENT 'analysis_ready/analysis_blocked; independent from broadcast readiness',
  `view_status` VARCHAR(30) NOT NULL DEFAULT 'ready' COMMENT 'ready/pending_view',
  `generation_trigger` VARCHAR(30) NOT NULL DEFAULT 'manual' COMMENT 'manual/background',
  `template_version` VARCHAR(80) NOT NULL COMMENT 'deterministic broadcast template version',
  `hotel_name_snapshot` VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'hotel name captured with this immutable version',
  `data_cutoff_at` DATETIME DEFAULT NULL COMMENT 'latest collection time among facts used by this broadcast',
  `facts_fingerprint` CHAR(64) NOT NULL COMMENT 'stable identity of facts, gaps and source status',
  `snapshot_fingerprint` CHAR(64) NOT NULL COMMENT 'readback identity of the immutable persisted snapshot',
  `final_text_sha256` CHAR(64) NOT NULL COMMENT 'sha256 of final_text',
  `facts_json` JSON NOT NULL COMMENT 'facts copied from strict current readback without recalculation',
  `fact_refs_json` JSON NOT NULL COMMENT 'exact source record references used by facts_json',
  `missing_items_json` JSON NOT NULL COMMENT 'explicit missing, failed or caliber-uncertain items',
  `source_status_json` JSON NOT NULL COMMENT 'per-platform readback and analysis status',
  `final_text` TEXT NOT NULL COMMENT 'single text used by page, clipboard and browser speech',
  `generated_at` DATETIME NOT NULL COMMENT 'business snapshot generation time',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_daily_broadcast_scope_version` (`tenant_id`, `hotel_id`, `business_date`, `version_no`),
  UNIQUE KEY `uk_ai_daily_broadcast_facts` (`tenant_id`, `hotel_id`, `business_date`, `template_version`, `generation_trigger`, `facts_fingerprint`),
  KEY `idx_ai_daily_broadcast_latest` (`tenant_id`, `hotel_id`, `business_date`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Versioned trusted operating broadcast snapshots';
