CREATE TABLE IF NOT EXISTS `weekly_operating_plan_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `hotel_id` BIGINT UNSIGNED NOT NULL,
  `week_start` DATE NOT NULL,
  `week_end` DATE NOT NULL,
  `version_no` INT UNSIGNED NOT NULL,
  `status` VARCHAR(40) NOT NULL,
  `source_digest` CHAR(64) NOT NULL,
  `snapshot_fingerprint` CHAR(64) NOT NULL,
  `final_text_sha256` CHAR(64) NOT NULL,
  `daily_run_refs_json` JSON NOT NULL,
  `broadcast_snapshot_refs_json` JSON NOT NULL,
  `lifecycle_summary_json` JSON NOT NULL,
  `repeated_gap_summary_json` JSON NOT NULL,
  `selected_focus_json` JSON NOT NULL,
  `missing_days_json` JSON NOT NULL,
  `final_text` TEXT NOT NULL,
  `generation_trigger` VARCHAR(30) NOT NULL DEFAULT 'background',
  `generated_at` DATETIME NOT NULL,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_weekly_plan_scope_version` (`tenant_id`, `hotel_id`, `week_start`, `week_end`, `version_no`),
  UNIQUE KEY `uk_weekly_plan_source` (`tenant_id`, `hotel_id`, `week_start`, `week_end`, `generation_trigger`, `source_digest`),
  KEY `idx_weekly_plan_latest` (`tenant_id`, `hotel_id`, `week_end`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Immutable source-backed weekly operating plans';
