-- 酒店经营目标合同：每次调整追加一个版本，旧版本不覆盖。
CREATE TABLE IF NOT EXISTS `hotel_operating_goal_contracts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL COMMENT '租户ID',
  `hotel_id` INT UNSIGNED NOT NULL COMMENT '宿析酒店ID',
  `version_no` INT UNSIGNED NOT NULL COMMENT '酒店内递增版本号',
  `contract_schema` VARCHAR(50) NOT NULL COMMENT 'hotel_operating_goal.v1',
  `primary_objective` VARCHAR(30) NOT NULL COMMENT 'revenue/profit/cash_flow',
  `primary_metric_key` VARCHAR(80) NOT NULL COMMENT '首要目标指标键',
  `objective_direction` VARCHAR(20) NOT NULL COMMENT 'increase/preserve',
  `guard_metrics_json` JSON NOT NULL COMMENT '保护指标及上下限',
  `operating_constraints_json` JSON NOT NULL COMMENT '最低价、库存、房型、渠道和日期约束',
  `risk_preference` VARCHAR(20) NOT NULL COMMENT 'conservative/balanced/aggressive',
  `operating_phase` VARCHAR(40) NOT NULL COMMENT '当前经营阶段',
  `phase_note` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '阶段补充说明',
  `stop_conditions_json` JSON NOT NULL COMMENT '必须停止的条件',
  `rollback_plan` VARCHAR(1000) NOT NULL COMMENT '停止后的回滚方案',
  `effective_from` DATE NOT NULL COMMENT '合同生效经营日',
  `effective_to` DATE NOT NULL COMMENT '合同截止经营日',
  `version_note` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '本次换版原因',
  `content_digest` CHAR(64) NOT NULL COMMENT '规范化合同SHA-256摘要',
  `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hotel_goal_contract_version` (`tenant_id`, `hotel_id`, `version_no`),
  UNIQUE KEY `uniq_hotel_goal_contract_digest` (`tenant_id`, `hotel_id`, `content_digest`),
  KEY `idx_hotel_goal_contract_current` (`tenant_id`, `hotel_id`, `id`),
  KEY `idx_hotel_goal_contract_effective` (`tenant_id`, `hotel_id`, `effective_from`, `effective_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='酒店经营目标合同版本账本';

-- 经营干预合同：绑定一个已存在的执行意图和当时的目标合同版本。
CREATE TABLE IF NOT EXISTS `operation_intervention_contracts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL COMMENT '租户ID',
  `hotel_id` INT UNSIGNED NOT NULL COMMENT '宿析酒店ID',
  `intent_id` BIGINT UNSIGNED NOT NULL COMMENT '运营执行意图ID',
  `version_no` INT UNSIGNED NOT NULL COMMENT '意图内递增版本号',
  `goal_contract_id` BIGINT UNSIGNED NOT NULL COMMENT '冻结的目标合同ID',
  `goal_contract_version_no` INT UNSIGNED NOT NULL COMMENT '冻结的目标合同版本',
  `contract_schema` VARCHAR(60) NOT NULL COMMENT 'operation_intervention.v1',
  `design_timing` VARCHAR(20) NOT NULL COMMENT 'prospective/retrospective',
  `action_type` VARCHAR(80) NOT NULL COMMENT '经营动作类型',
  `rationale` VARCHAR(1000) NOT NULL COMMENT '为什么做',
  `target_metric_key` VARCHAR(80) NOT NULL COMMENT '想改变的指标',
  `expected_direction` VARCHAR(20) NOT NULL COMMENT 'increase/decrease',
  `expected_delta` DECIMAL(20,6) NOT NULL COMMENT '预先声明的最小变化',
  `expected_delta_unit` VARCHAR(20) NOT NULL COMMENT 'absolute/percent',
  `risk_metric_keys_json` JSON NOT NULL COMMENT '可能受伤害的保护指标键',
  `baseline_snapshot_json` JSON NOT NULL COMMENT '执行前基线及来源身份',
  `observation_window_start` DATE NOT NULL COMMENT '观察窗开始经营日',
  `observation_window_end` DATE NOT NULL COMMENT '观察窗结束经营日',
  `comparison_mode` VARCHAR(40) NOT NULL COMMENT 'same_length_period/same_day_realtime/target_stay_observation',
  `comparison_reference` VARCHAR(1000) NOT NULL COMMENT '可比日期或对照对象',
  `minimum_sample_size` INT UNSIGNED NOT NULL COMMENT '预先声明的最小样本量',
  `stop_condition` VARCHAR(1000) NOT NULL COMMENT '本次干预停止条件',
  `content_digest` CHAR(64) NOT NULL COMMENT '规范化干预合同SHA-256摘要',
  `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_operation_intervention_version` (`tenant_id`, `hotel_id`, `intent_id`, `version_no`),
  UNIQUE KEY `uniq_operation_intervention_digest` (`tenant_id`, `hotel_id`, `intent_id`, `content_digest`),
  KEY `idx_operation_intervention_intent` (`tenant_id`, `hotel_id`, `intent_id`, `id`),
  KEY `idx_operation_intervention_goal` (`tenant_id`, `hotel_id`, `goal_contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运营任务经营干预合同版本账本';

-- 干预学习判定：允许保存 indeterminate，永不把缺失证据补成成功。
CREATE TABLE IF NOT EXISTS `operation_intervention_assessments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL COMMENT '租户ID',
  `hotel_id` INT UNSIGNED NOT NULL COMMENT '宿析酒店ID',
  `intent_id` BIGINT UNSIGNED NOT NULL COMMENT '运营执行意图ID',
  `task_id` BIGINT UNSIGNED NOT NULL COMMENT '已进入执行链的任务ID',
  `intervention_contract_id` BIGINT UNSIGNED NOT NULL COMMENT '冻结的干预合同ID',
  `assessment_schema` VARCHAR(60) NOT NULL COMMENT 'operation_intervention_assessment.v1',
  `verdict` VARCHAR(20) NOT NULL COMMENT 'supported/contradicted/indeterminate',
  `reason_codes_json` JSON NOT NULL COMMENT '确定性判定理由及缺口',
  `followup_snapshot_json` JSON NOT NULL COMMENT '观察窗结果快照',
  `guard_observations_json` JSON NOT NULL COMMENT '保护指标观察结果',
  `external_interferences_json` JSON NOT NULL COMMENT '外部干扰声明',
  `stop_triggered` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否触发停止条件',
  `stop_evidence_refs_json` JSON NOT NULL COMMENT '停止条件证据引用',
  `comparison_json` JSON NOT NULL COMMENT '同口径比较与目标进度',
  `result_summary` VARCHAR(1000) NOT NULL COMMENT '系统三态判定摘要',
  `causality_claimed` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '固定为0，不宣称因果',
  `content_digest` CHAR(64) NOT NULL COMMENT '完整判定SHA-256摘要',
  `assessed_by` BIGINT UNSIGNED NOT NULL COMMENT '发起判定的用户ID',
  `assessed_at` DATETIME NOT NULL COMMENT '判定时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_operation_intervention_assessment_digest` (`tenant_id`, `hotel_id`, `task_id`, `content_digest`),
  KEY `idx_operation_intervention_assessment_task` (`tenant_id`, `hotel_id`, `intent_id`, `task_id`, `id`),
  KEY `idx_operation_intervention_assessment_verdict` (`tenant_id`, `hotel_id`, `verdict`, `id`),
  KEY `idx_operation_intervention_assessment_contract` (`tenant_id`, `intervention_contract_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='经营干预三态学习判定追加账本';

-- 三张表均为追加式业务账本。纠错通过新版本或新判定完成，不提供 UPDATE/DELETE 业务接口。
