-- Fourteen-day, human-controlled forecast pilot batches.
-- The pilot gate is intentionally separate from the mature operational gate:
-- 14 trusted history days may start a bounded pilot, while mature operation
-- continues to require the existing 21-day / 10-sample / 60% policy.
CREATE TABLE IF NOT EXISTS `temporal_forecast_trials` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL COMMENT 'tenant resolved from the system hotel',
  `system_hotel_id` INT UNSIGNED NOT NULL COMMENT 'authorized SUXIOS hotel id',
  `trial_version` VARCHAR(64) NOT NULL COMMENT 'immutable pilot version id',
  `forecast_run_id` VARCHAR(48) NOT NULL COMMENT 'immutable forecast run under evaluation',
  `policy_version` VARCHAR(48) NOT NULL DEFAULT 'limited_pilot_v1',
  `metric_scope` VARCHAR(40) NOT NULL DEFAULT 'ota_channel',
  `platform` VARCHAR(40) NOT NULL DEFAULT 'all_ota',
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `required_target_days` SMALLINT UNSIGNED NOT NULL DEFAULT 14,
  `required_history_days` SMALLINT UNSIGNED NOT NULL DEFAULT 14,
  `core_metrics_json` JSON NOT NULL,
  `pilot_policy_json` JSON NOT NULL,
  `mature_policy_json` JSON NOT NULL,
  `source_identity_json` JSON NOT NULL,
  `immutable_digest` CHAR(64) NOT NULL,
  `eligibility_status` VARCHAR(32) NOT NULL DEFAULT 'eligible',
  `maturity_status` VARCHAR(32) NOT NULL DEFAULT 'accruing',
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `operation_intent_id` BIGINT UNSIGNED DEFAULT NULL,
  `final_review_json` JSON DEFAULT NULL,
  `approved_by` BIGINT UNSIGNED DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  `reviewed_by` BIGINT UNSIGNED DEFAULT NULL,
  `reviewed_at` DATETIME DEFAULT NULL,
  `stopped_reason` VARCHAR(500) DEFAULT NULL,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_temporal_forecast_trial_version` (`trial_version`),
  UNIQUE KEY `uniq_temporal_forecast_trial_run` (`tenant_id`, `system_hotel_id`, `forecast_run_id`),
  KEY `idx_temporal_forecast_trial_hotel_status` (`tenant_id`, `system_hotel_id`, `status`, `created_at`),
  KEY `idx_temporal_forecast_trial_intent` (`operation_intent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='bounded 14-day OTA forecast pilot batches';

CREATE TABLE IF NOT EXISTS `temporal_forecast_trial_points` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trial_id` BIGINT UNSIGNED NOT NULL,
  `tenant_id` INT UNSIGNED NOT NULL,
  `system_hotel_id` INT UNSIGNED NOT NULL,
  `forecast_snapshot_id` BIGINT UNSIGNED NOT NULL,
  `metric_key` VARCHAR(50) NOT NULL,
  `target_date` DATE NOT NULL,
  `horizon_days` SMALLINT UNSIGNED NOT NULL,
  `predicted_value` DECIMAL(18,4) DEFAULT NULL,
  `lower_bound` DECIMAL(18,4) DEFAULT NULL,
  `upper_bound` DECIMAL(18,4) DEFAULT NULL,
  `sample_days` SMALLINT UNSIGNED NOT NULL,
  `source_refs_json` JSON NOT NULL,
  `point_digest` CHAR(64) NOT NULL,
  `actual_status` VARCHAR(32) NOT NULL DEFAULT 'pending_actual',
  `actual_value` DECIMAL(18,4) DEFAULT NULL,
  `absolute_error` DECIMAL(18,4) DEFAULT NULL,
  `within_range` TINYINT(1) DEFAULT NULL,
  `actual_readback_json` JSON DEFAULT NULL,
  `actual_reason_code` VARCHAR(100) DEFAULT NULL,
  `actual_readback_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_temporal_forecast_trial_snapshot` (`trial_id`, `forecast_snapshot_id`),
  UNIQUE KEY `uniq_temporal_forecast_trial_metric_date` (`trial_id`, `metric_key`, `target_date`),
  KEY `idx_temporal_forecast_trial_point_date` (`tenant_id`, `system_hotel_id`, `target_date`, `actual_status`),
  CONSTRAINT `fk_temporal_forecast_trial_points_trial`
    FOREIGN KEY (`trial_id`) REFERENCES `temporal_forecast_trials` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='immutable forecast points and finalized actual readbacks for a pilot';
