CREATE TABLE IF NOT EXISTS `ota_local_collector_devices` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `device_public_id` VARCHAR(80) NOT NULL,
  `device_token_hash` CHAR(64) NOT NULL,
  `device_name` VARCHAR(120) NOT NULL,
  `device_platform` VARCHAR(30) NOT NULL DEFAULT 'windows',
  `collector_version` VARCHAR(40) NOT NULL DEFAULT '',
  `capabilities_json` TEXT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'offline',
  `last_seen_at` DATETIME NULL,
  `last_error_code` VARCHAR(80) NOT NULL DEFAULT '',
  `last_error_summary` VARCHAR(500) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ota_local_device_public_id` (`device_public_id`),
  KEY `idx_ota_local_device_owner_status` (`tenant_id`,`user_id`,`status`),
  KEY `idx_ota_local_device_seen` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ota_local_collector_accounts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `device_id` BIGINT UNSIGNED NOT NULL,
  `platform` VARCHAR(20) NOT NULL,
  `account_alias` VARCHAR(120) NOT NULL,
  `profile_key_hash` CHAR(64) NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'login_required',
  `session_status` VARCHAR(50) NOT NULL DEFAULT 'login_required',
  `last_session_verified_at` DATETIME NULL,
  `last_success_at` DATETIME NULL,
  `last_error_code` VARCHAR(80) NOT NULL DEFAULT '',
  `last_error_summary` VARCHAR(500) NOT NULL DEFAULT '',
  `retry_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `next_retry_at` DATETIME NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ota_local_account_alias` (`tenant_id`,`user_id`,`platform`,`account_alias`),
  UNIQUE KEY `uq_ota_local_account_profile` (`device_id`,`platform`,`profile_key_hash`),
  KEY `idx_ota_local_account_device_status` (`device_id`,`status`),
  KEY `idx_ota_local_account_session` (`tenant_id`,`platform`,`session_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ota_local_collector_account_hotels` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `account_id` BIGINT UNSIGNED NOT NULL,
  `system_hotel_id` BIGINT UNSIGNED NOT NULL,
  `platform` VARCHAR(20) NOT NULL,
  `platform_hotel_id` VARCHAR(120) NOT NULL,
  `platform_hotel_name` VARCHAR(160) NOT NULL DEFAULT '',
  `data_source_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL DEFAULT 'active',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ota_local_account_hotel` (`account_id`,`system_hotel_id`),
  UNIQUE KEY `uq_ota_local_hotel_platform` (`tenant_id`,`system_hotel_id`,`platform`),
  KEY `idx_ota_local_mapping_account_status` (`account_id`,`status`),
  KEY `idx_ota_local_mapping_source` (`data_source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ota_local_collector_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `device_id` BIGINT UNSIGNED NOT NULL,
  `account_id` BIGINT UNSIGNED NOT NULL,
  `system_hotel_id` BIGINT UNSIGNED NOT NULL,
  `platform` VARCHAR(20) NOT NULL,
  `task_type` VARCHAR(30) NOT NULL,
  `data_date` DATE NULL,
  `data_type` VARCHAR(50) NOT NULL DEFAULT 'business',
  `status` VARCHAR(40) NOT NULL DEFAULT 'queued',
  `priority` INT NOT NULL DEFAULT 50,
  `attempt` INT UNSIGNED NOT NULL DEFAULT 0,
  `max_attempts` INT UNSIGNED NOT NULL DEFAULT 3,
  `available_at` DATETIME NOT NULL,
  `lease_token_hash` CHAR(64) NOT NULL DEFAULT '',
  `lease_expires_at` DATETIME NULL,
  `idempotency_key` CHAR(64) NOT NULL,
  `request_json` MEDIUMTEXT NULL,
  `result_summary_json` MEDIUMTEXT NULL,
  `error_code` VARCHAR(80) NOT NULL DEFAULT '',
  `error_summary` VARCHAR(500) NOT NULL DEFAULT '',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ota_local_task_idempotency` (`idempotency_key`),
  KEY `idx_ota_local_task_device_queue` (`device_id`,`status`,`available_at`,`priority`),
  KEY `idx_ota_local_task_account_date` (`account_id`,`system_hotel_id`,`data_date`,`task_type`),
  KEY `idx_ota_local_task_lease` (`lease_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
