CREATE TABLE IF NOT EXISTS `ota_ctrip_im_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `system_hotel_id` int unsigned NOT NULL COMMENT '系统酒店ID',
  `group_id` varchar(80) NOT NULL COMMENT '携程IM会话groupId',
  `session_id` varchar(120) NOT NULL DEFAULT '',
  `guest_uid` char(32) NOT NULL DEFAULT '' COMMENT '携程IM客人会员UID/MD5',
  `guest_name` varchar(120) NOT NULL DEFAULT '' COMMENT 'IM会员昵称或客人名',
  `guest_avatar_url` varchar(500) NOT NULL DEFAULT '',
  `arrival_date` date DEFAULT NULL,
  `departure_date` date DEFAULT NULL,
  `room_name` varchar(180) NOT NULL DEFAULT '',
  `room_name_prefix` varchar(120) NOT NULL DEFAULT '',
  `order_id` varchar(80) NOT NULL DEFAULT '',
  `match_status` varchar(40) NOT NULL DEFAULT 'unverified' COMMENT 'usable/degraded_missing_arrival_date/unusable_no_guest_member',
  `members_json` longtext NOT NULL COMMENT '授权导入的IM members',
  `evidence_json` text NULL COMMENT '采集证据摘要',
  `fetched_at` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ota_ctrip_im_hotel_group` (`system_hotel_id`, `group_id`),
  KEY `idx_ota_ctrip_im_guest_uid` (`system_hotel_id`, `guest_uid`),
  KEY `idx_ota_ctrip_im_arrival` (`system_hotel_id`, `arrival_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='携程评价订单匹配-IM会话缓存';

CREATE TABLE IF NOT EXISTS `ota_ctrip_reviews` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `system_hotel_id` int unsigned NOT NULL COMMENT '系统酒店ID',
  `comment_id` varchar(120) NOT NULL COMMENT '携程评价ID',
  `source_username` varchar(160) NOT NULL DEFAULT '' COMMENT '评价页用户名',
  `user_avatar_url` varchar(500) NOT NULL DEFAULT '',
  `review_date` date DEFAULT NULL,
  `checkin_date` date DEFAULT NULL,
  `room_name` varchar(180) NOT NULL DEFAULT '',
  `score` decimal(5,2) DEFAULT NULL,
  `content` text NULL,
  `raw_review_json` longtext NOT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ota_ctrip_review_hotel_comment` (`system_hotel_id`, `comment_id`),
  KEY `idx_ota_ctrip_review_date` (`system_hotel_id`, `checkin_date`),
  KEY `idx_ota_ctrip_review_username` (`system_hotel_id`, `source_username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='携程评价订单匹配-评价池';

CREATE TABLE IF NOT EXISTS `ota_ctrip_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `system_hotel_id` int unsigned NOT NULL COMMENT '系统酒店ID',
  `order_id` varchar(80) NOT NULL COMMENT '携程订单号',
  `guest_uid` char(32) NOT NULL DEFAULT '' COMMENT 'IM客人UID/MD5',
  `guest_name` varchar(120) NOT NULL DEFAULT '',
  `arrival_date` date DEFAULT NULL,
  `departure_date` date DEFAULT NULL,
  `room_name` varchar(180) NOT NULL DEFAULT '',
  `room_name_prefix` varchar(120) NOT NULL DEFAULT '',
  `order_status` varchar(80) NOT NULL DEFAULT '',
  `source_platform` varchar(40) NOT NULL DEFAULT 'ctrip',
  `raw_order_json` longtext NOT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ota_ctrip_order_hotel_order` (`system_hotel_id`, `order_id`),
  KEY `idx_ota_ctrip_order_guest_uid` (`system_hotel_id`, `guest_uid`),
  KEY `idx_ota_ctrip_order_guest_name_date` (`system_hotel_id`, `guest_name`, `arrival_date`),
  KEY `idx_ota_ctrip_order_arrival_room` (`system_hotel_id`, `arrival_date`, `room_name_prefix`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='携程评价订单匹配-订单池';

CREATE TABLE IF NOT EXISTS `ota_ctrip_review_order_matches` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `system_hotel_id` int unsigned NOT NULL COMMENT '系统酒店ID',
  `comment_id` varchar(120) NOT NULL COMMENT '携程评价ID',
  `order_id` varchar(80) NOT NULL DEFAULT '',
  `guest_uid` char(32) NOT NULL DEFAULT '',
  `guest_name` varchar(120) NOT NULL DEFAULT '',
  `match_status` varchar(40) NOT NULL DEFAULT 'unmatched' COMMENT 'found/person_locked/needs_ops/out_of_coverage/matched',
  `match_method` varchar(80) NOT NULL DEFAULT '',
  `confidence` varchar(30) NOT NULL DEFAULT 'none',
  `candidate_orders_json` longtext NOT NULL,
  `evidence_json` longtext NOT NULL,
  `bound_by` int unsigned DEFAULT NULL,
  `bound_at` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ota_ctrip_review_match_comment` (`system_hotel_id`, `comment_id`),
  KEY `idx_ota_ctrip_review_match_order` (`system_hotel_id`, `order_id`),
  KEY `idx_ota_ctrip_review_match_status` (`system_hotel_id`, `match_status`, `confidence`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='携程评价订单匹配结果';
