CREATE TABLE IF NOT EXISTS `strategy_simulation_records` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `project_name` VARCHAR(120) NOT NULL,
    `city` VARCHAR(60) NOT NULL,
    `district` VARCHAR(80) DEFAULT '',
    `address` VARCHAR(255) DEFAULT '',
    `property_area` DECIMAL(12,2) DEFAULT 0,
    `room_count` INT DEFAULT 0,
    `monthly_rent` DECIMAL(12,2) DEFAULT 0,
    `decoration_budget` DECIMAL(12,2) DEFAULT 0,
    `lease_years` INT DEFAULT 0,
    `rent_free_months` INT DEFAULT 0,
    `business_type` VARCHAR(60) DEFAULT '',
    `target_customer` VARCHAR(60) DEFAULT '',
    `competitor_count` INT DEFAULT 0,
    `target_hotel_level` VARCHAR(60) DEFAULT '',
    `input_json` JSON DEFAULT NULL,
    `data_snapshot_json` JSON DEFAULT NULL,
    `score_json` JSON DEFAULT NULL,
    `recommendation_json` JSON DEFAULT NULL,
    `risk_json` JSON DEFAULT NULL,
    `created_by` INT UNSIGNED DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL,
    INDEX `idx_city_district` (`city`, `district`),
    INDEX `idx_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='战略推演记录表';

CREATE TABLE IF NOT EXISTS `strategy_data_snapshots` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `city` VARCHAR(60) NOT NULL,
    `district` VARCHAR(80) DEFAULT '',
    `address` VARCHAR(255) DEFAULT '',
    `business_type` VARCHAR(60) DEFAULT '',
    `target_customer` VARCHAR(60) DEFAULT '',
    `source_type` VARCHAR(40) DEFAULT '',
    `source_name` VARCHAR(120) DEFAULT '',
    `source_date` DATE DEFAULT NULL,
    `freshness_level` VARCHAR(40) DEFAULT '',
    `raw_json` JSON DEFAULT NULL,
    `normalized_json` JSON DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_snapshot_cache` (`city`, `district`, `business_type`, `target_customer`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='战略推演数据快照表';
