CREATE TABLE IF NOT EXISTS `operation_execution_intents` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_module` VARCHAR(80) NOT NULL DEFAULT '' COMMENT 'source module: root_cause/strategy_simulation/ai/manual',
  `source_record_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'source record id',
  `hotel_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'hotel id',
  `platform` VARCHAR(40) NOT NULL DEFAULT '' COMMENT 'OTA platform',
  `object_type` VARCHAR(30) NOT NULL DEFAULT '' COMMENT 'price/inventory/campaign',
  `action_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'execution action type',
  `date_start` DATE NOT NULL COMMENT 'execution start date',
  `date_end` DATE DEFAULT NULL COMMENT 'execution end date',
  `current_value_json` JSON DEFAULT NULL COMMENT 'current value snapshot',
  `target_value_json` JSON DEFAULT NULL COMMENT 'target execution value',
  `evidence_json` JSON DEFAULT NULL COMMENT 'decision evidence',
  `expected_metric` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'expected metric',
  `expected_delta` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'expected metric delta percent',
  `risk_level` VARCHAR(30) NOT NULL DEFAULT 'medium' COMMENT 'risk level',
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending_approval' COMMENT 'draft/pending_approval/blocked/approved/rejected',
  `blocked_reason` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'blocked reason',
  `review_remark` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'approval or rejection remark',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'creator user id',
  `approved_by` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'approval user id',
  `approved_at` DATETIME DEFAULT NULL COMMENT 'approval time',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_operation_exec_intent_hotel_status` (`hotel_id`, `status`),
  KEY `idx_operation_exec_intent_object` (`platform`, `object_type`, `action_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='operation execution intent table';

CREATE TABLE IF NOT EXISTS `operation_execution_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `intent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'execution intent id',
  `hotel_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'hotel id',
  `execution_mode` VARCHAR(30) NOT NULL DEFAULT 'manual' COMMENT 'manual/browser/api',
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operator user id',
  `target_value_json` JSON DEFAULT NULL COMMENT 'target execution value',
  `current_value_json` JSON DEFAULT NULL COMMENT 'current execution value',
  `blocked_reason` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'blocked reason',
  `action_track_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operation_action_tracks id',
  `result_status` VARCHAR(30) NOT NULL DEFAULT 'observing' COMMENT 'observing/success/near_success/failed',
  `result_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'review summary',
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending_execute' COMMENT 'pending_execute/executing/blocked/executed/failed',
  `executed_at` DATETIME DEFAULT NULL COMMENT 'execution time',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_operation_exec_task_intent` (`intent_id`),
  KEY `idx_operation_exec_task_hotel_status` (`hotel_id`, `status`),
  KEY `idx_operation_exec_task_action` (`action_track_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='operation execution task table';

CREATE TABLE IF NOT EXISTS `operation_execution_evidence` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'execution task id',
  `evidence_type` VARCHAR(50) NOT NULL DEFAULT 'manual' COMMENT 'manual_screenshot/api_response/remark',
  `before_json` JSON DEFAULT NULL COMMENT 'before execution evidence',
  `after_json` JSON DEFAULT NULL COMMENT 'after execution evidence',
  `attachment_path` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'local attachment path',
  `platform_response_json` JSON DEFAULT NULL COMMENT 'platform response payload',
  `remark` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'evidence remark',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'creator user id',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_operation_exec_evidence_task` (`task_id`),
  KEY `idx_operation_exec_evidence_type` (`evidence_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='operation execution evidence table';
