-- Manual investor cash only; independent of OTA/AI and retired feasibility writes.
CREATE TABLE IF NOT EXISTS `investment_payback_projects` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL,
  `hotel_id` INT UNSIGNED NULL,
  `project_name` VARCHAR(160) NOT NULL,
  `investor_name` VARCHAR(160) NOT NULL,
  `basis` VARCHAR(32) NOT NULL DEFAULT 'investor_cash',
  `currency` CHAR(3) NOT NULL DEFAULT 'CNY',
  `status` VARCHAR(24) NOT NULL DEFAULT 'draft',
  `first_invested_on` DATE NULL,
  `expected_monthly_amount` DECIMAL(14,2) NULL,
  `expected_source` VARCHAR(1000) NOT NULL DEFAULT '',
  `forecast_as_of` DATE NOT NULL,
  `history_complete_through` DATE NULL,
  `opening_as_of` DATE NULL,
  `opening_invested` DECIMAL(14,2) NULL,
  `opening_recovered` DECIMAL(14,2) NULL,
  `opening_source` VARCHAR(1000) NOT NULL DEFAULT '',
  `notes` VARCHAR(2000) NOT NULL DEFAULT '',
  `client_request_id` VARCHAR(100) NOT NULL,
  `input_digest` CHAR(64) NOT NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NOT NULL,
  `updated_by` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `archived_at` DATETIME NULL,
  `archive_reason` VARCHAR(1000) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payback_project_request` (`tenant_id`,`created_by`,`client_request_id`),
  KEY `idx_payback_project_scope` (`tenant_id`,`hotel_id`,`archived_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `investment_payback_entries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `kind` VARCHAR(24) NOT NULL,
  `amount` DECIMAL(14,2) NOT NULL,
  `business_date` VARCHAR(10) NOT NULL,
  `precision` VARCHAR(8) NOT NULL,
  `is_planned` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `confirmed_zero` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `category` VARCHAR(120) NOT NULL DEFAULT '',
  `source` VARCHAR(1000) NOT NULL DEFAULT '',
  `notes` VARCHAR(2000) NOT NULL DEFAULT '',
  `original_entry_id` BIGINT UNSIGNED NULL,
  `client_request_id` VARCHAR(100) NOT NULL,
  `input_digest` CHAR(64) NOT NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NOT NULL,
  `updated_by` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `voided_at` DATETIME NULL,
  `voided_by` BIGINT UNSIGNED NULL,
  `void_reason` VARCHAR(1000) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payback_entry_request` (`tenant_id`,`project_id`,`created_by`,`client_request_id`),
  KEY `idx_payback_entry_scope` (`tenant_id`,`project_id`,`business_date`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `investment_payback_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `entry_id` BIGINT UNSIGNED NULL,
  `actor_id` BIGINT UNSIGNED NOT NULL,
  `event_type` VARCHAR(32) NOT NULL,
  `project_version` INT UNSIGNED NOT NULL,
  `payload_json` JSON NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_payback_event_scope` (`tenant_id`,`project_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
