-- Immutable, versioned coarse forecasts for the SUXIOS past/present/future loop.
-- Values remain OTA-channel scoped and are never execution-price instructions.
CREATE TABLE IF NOT EXISTS `temporal_forecast_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'tenant id resolved from system hotel',
  `system_hotel_id` INT UNSIGNED NOT NULL COMMENT 'authorized SUXIOS hotel id',
  `metric_scope` VARCHAR(40) NOT NULL DEFAULT 'ota_channel' COMMENT 'metric scope, currently ota_channel only',
  `platform` VARCHAR(40) NOT NULL DEFAULT 'all_ota' COMMENT 'all_ota/ctrip/meituan',
  `metric_key` VARCHAR(50) NOT NULL COMMENT 'OTA revenue/order/room-night/traffic metric key',
  `forecast_run_id` VARCHAR(48) NOT NULL COMMENT 'immutable forecast version id',
  `as_of_date` DATE NOT NULL COMMENT 'latest fact date known to this forecast',
  `as_of_time` DATETIME NOT NULL COMMENT 'time this forecast version was generated',
  `target_date` DATE NOT NULL COMMENT 'forecasted business date',
  `horizon_days` SMALLINT UNSIGNED NOT NULL COMMENT 'days from as_of_date to target_date',
  `model_version` VARCHAR(80) NOT NULL DEFAULT 'coarse_trend_v1' COMMENT 'deterministic forecast version',
  `method` VARCHAR(120) NOT NULL DEFAULT 'weekday_recent_trend_interval' COMMENT 'forecast method',
  `predicted_direction` VARCHAR(20) NOT NULL DEFAULT 'stable' COMMENT 'up/stable/down',
  `predicted_value` DECIMAL(18,4) DEFAULT NULL COMMENT 'internal point estimate; UI should prefer interval',
  `lower_bound` DECIMAL(18,4) DEFAULT NULL COMMENT 'coarse lower interval',
  `upper_bound` DECIMAL(18,4) DEFAULT NULL COMMENT 'coarse upper interval',
  `confidence_score` DECIMAL(5,4) DEFAULT NULL COMMENT '0-1 evidence confidence',
  `confidence_level` VARCHAR(20) NOT NULL DEFAULT 'low' COMMENT 'low/medium/high',
  `sample_days` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'valid historical sample days',
  `source_start_date` DATE DEFAULT NULL,
  `source_end_date` DATE DEFAULT NULL,
  `source_refs_json` JSON DEFAULT NULL COMMENT 'bounded source trace summary, no credentials',
  `data_quality_status` VARCHAR(30) NOT NULL DEFAULT 'insufficient' COMMENT 'ready/partial/insufficient',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_temporal_forecast_point` (`forecast_run_id`, `system_hotel_id`, `platform`, `metric_key`, `target_date`),
  KEY `idx_temporal_forecast_hotel_target` (`system_hotel_id`, `target_date`, `as_of_time`),
  KEY `idx_temporal_forecast_hotel_run` (`system_hotel_id`, `forecast_run_id`),
  KEY `idx_temporal_forecast_tenant_date` (`tenant_id`, `target_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='versioned OTA coarse forecast snapshots for temporal review';
