[PHP]
; 文件上传
file_uploads = On
upload_max_filesize = 20M
post_max_size = 20M

; SQLite
pdo_sqlite.enable = On

; 时区
date.timezone = Asia/Shanghai

; 错误显示
display_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED

; 性能
max_execution_time = 300
memory_limit = 256M
