import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { gzipSync } from 'node:zlib';
import { compile } from '@vue/compiler-dom';
import { minify } from 'terser';
import { loadFrontendTemplateSource } from './frontend_template_source.mjs';

const EMPTY_V_IF_ANCHOR_SOURCE = '_createCommentVNode("v-if", true)';
const EMPTY_V_IF_ANCHOR_RUNTIME = '_createCommentVNode("", true)';

export const FRONTEND_TEMPLATE_MINIFY_OPTIONS = Object.freeze({
  ecma: 2020,
  module: false,
  toplevel: false,
  compress: Object.freeze({ defaults: true, passes: 2 }),
  mangle: Object.freeze({ safari10: true, toplevel: false }),
  format: Object.freeze({
    ascii_only: false,
    beautify: false,
    comments: false,
    semicolons: true,
  }),
});

export function compileFrontendTemplate(template) {
  const errors = [];
  const result = compile(String(template || ''), {
    mode: 'function',
    prefixIdentifiers: true,
    hoistStatic: false,
    comments: false,
    onError: (error) => errors.push(error),
  });
  if (errors.length) {
    const details = errors.map((error) => {
      const line = error.loc?.start?.line ? ` at line ${error.loc.start.line}` : '';
      return `${error.message}${line}`;
    }).join('; ');
    throw new Error(`Vue template compilation failed: ${details}`);
  }

  const markerCount = result.code.split(EMPTY_V_IF_ANCHOR_SOURCE).length - 1;
  if (markerCount < 1) throw new Error('Expected Vue v-if comment anchors were not generated.');
  return result.code.replaceAll(EMPTY_V_IF_ANCHOR_SOURCE, EMPTY_V_IF_ANCHOR_RUNTIME);
}

export async function buildFrontendTemplateRender(template) {
  const compiled = compileFrontendTemplate(template);
  const wrapped = `window.SUXI_APP_RENDER=(function(Vue){${compiled}})(Vue);`;
  const result = await minify(
    { 'app-render.js': wrapped },
    structuredClone(FRONTEND_TEMPLATE_MINIFY_OPTIONS)
  );
  if (!result.code) throw new Error('Terser returned an empty frontend render artifact.');
  return `${result.code}\n`;
}

const readText = (file) => (fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '');

export async function inspectFrontendTemplateBuild(repoRoot) {
  const templatePath = path.join(repoRoot, 'resources/frontend/app-template.html');
  const renderPath = path.join(repoRoot, 'public/app-render.min.js');
  const runtimeVuePath = path.join(repoRoot, 'public/vue.runtime.global.prod.js');
  const compilerVuePath = path.join(repoRoot, 'public/vue.global.prod.js');
  const pinnedRuntimeVuePath = path.join(repoRoot, 'node_modules/vue/dist/vue.runtime.global.prod.js');
  const indexPath = path.join(repoRoot, 'public/index.html');
  const appMainPath = path.join(repoRoot, 'public/app-main.js');
  const templateSnapshotBuffer = fs.existsSync(templatePath) ? fs.readFileSync(templatePath) : Buffer.alloc(0);
  const templateSnapshot = templateSnapshotBuffer.toString('utf8');
  const artifact = readText(renderPath);
  const runtimeVue = readText(runtimeVuePath);
  const compilerVue = readText(compilerVuePath);
  const pinnedRuntimeVue = readText(pinnedRuntimeVuePath);
  const html = readText(indexPath);
  const appMain = readText(appMainPath);
  const failures = [];
  let fragmentSource = null;
  let template = '';
  let rebuilt = '';

  if (!templateSnapshotBuffer.length) failures.push('resources/frontend/app-template.html is missing or empty.');
  try {
    fragmentSource = loadFrontendTemplateSource(repoRoot);
    template = fragmentSource.template;
  } catch (error) {
    failures.push(error.message);
  }
  const templateSnapshotMatches = Boolean(
    fragmentSource && templateSnapshotBuffer.length && fragmentSource.templateBuffer.equals(templateSnapshotBuffer)
  );
  const templateSnapshotHash = templateSnapshotBuffer.length
    ? crypto.createHash('sha256').update(templateSnapshotBuffer).digest('hex')
    : '';
  const templateSnapshotPinMatches = Boolean(
    fragmentSource
    && fragmentSource.manifest.source_snapshot_sha256 === templateSnapshotHash
    && fragmentSource.manifest.source_snapshot_bytes === templateSnapshotBuffer.length
  );
  if (fragmentSource && templateSnapshotBuffer.length && !templateSnapshotMatches) {
    failures.push('Business template fragments do not match resources/frontend/app-template.html byte-for-byte.');
  }
  if (fragmentSource && templateSnapshotBuffer.length && !templateSnapshotPinMatches) {
    failures.push('Frontend template compatibility snapshot metadata is stale.');
  }
  if (template) {
    try {
      rebuilt = await buildFrontendTemplateRender(template);
    } catch (error) {
      failures.push(error.message);
    }
  }
  if (!artifact) failures.push('public/app-render.min.js is missing or empty.');
  else if (rebuilt && artifact !== rebuilt) failures.push('public/app-render.min.js is stale or not generated by the pinned build contract.');
  if (!runtimeVue) failures.push('public/vue.runtime.global.prod.js is missing or empty.');
  else if (runtimeVue !== pinnedRuntimeVue) failures.push('The runtime-only Vue artifact must exactly match pinned vue@3.5.32.');
  if (templateSnapshotBuffer.length < 1_000_000) failures.push('The canonical root template is unexpectedly small.');
  if (!templateSnapshot.includes('v-if="!isLoggedIn"') || !templateSnapshot.includes('v-if="toast.show"')) {
    failures.push('The canonical root template snapshot is missing login or global toast boundaries.');
  }
  if (!/<div id="app" v-cloak><\/div>/.test(html)) failures.push('public/index.html must contain only the empty #app runtime shell.');
  if (/src="vue\.global\.prod\.js/.test(html)) failures.push('public/index.html must not load the compiler-enabled Vue build.');
  if (!/render:\s*requireSuxiAppRender\(\)/.test(appMain)) failures.push('public/app-main.js must attach the precompiled root render.');

  const renderHash = artifact ? crypto.createHash('sha256').update(artifact).digest('hex').slice(0, 10) : '';
  if (renderHash && !new RegExp(`<script defer src="app-render\\.min\\.js\\?v=[^"]*-h${renderHash}"`).test(html)) {
    failures.push('public/index.html must reference the current precompiled render content hash.');
  }
  const deferredScripts = [...html.matchAll(/<script\s+defer\s+src="([^"]+)"[^>]*><\/script>/g)]
    .map((match) => match[1].split('?')[0]);
  if (deferredScripts[0] !== 'vue.runtime.global.prod.js'
    || deferredScripts.at(-2) !== 'app-render.min.js'
    || deferredScripts.at(-1) !== 'app-main.min.js') {
    failures.push('Deferred startup order must be runtime Vue -> helpers -> precompiled render -> app entry.');
  }
  if (artifact && Buffer.byteLength(artifact) >= 1_300_000) failures.push('The precompiled render artifact exceeded the 1.3 MB raw ceiling.');
  if (artifact && gzipSync(artifact, { level: 6 }).length >= 225_000) failures.push('The precompiled render artifact exceeded the 225 KB gzip ceiling.');
  if (runtimeVue && compilerVue && !(Buffer.byteLength(runtimeVue) < Buffer.byteLength(compilerVue) * 0.75)) {
    failures.push('The runtime-only Vue artifact must remain materially smaller than the compiler build.');
  }

  return {
    failures,
    metrics: {
      template_bytes: templateSnapshotBuffer.length,
      fragment_count: fragmentSource?.fragments.length ?? 0,
      fragment_bytes: fragmentSource?.templateBuffer.length ?? 0,
      fragment_manifest: fragmentSource
        ? path.relative(repoRoot, fragmentSource.manifestPath).replaceAll('\\', '/')
        : '',
      template_snapshot_matches: templateSnapshotMatches,
      template_snapshot_pin_matches: templateSnapshotPinMatches,
      render_bytes: Buffer.byteLength(artifact),
      render_gzip_bytes: artifact ? gzipSync(artifact, { level: 6 }).length : 0,
      render_hash: renderHash,
      runtime_vue_bytes: Buffer.byteLength(runtimeVue),
      runtime_vue_gzip_bytes: runtimeVue ? gzipSync(runtimeVue, { level: 6 }).length : 0,
      compiler_vue_bytes: Buffer.byteLength(compilerVue),
      compiler_vue_gzip_bytes: compilerVue ? gzipSync(compilerVue, { level: 6 }).length : 0,
    },
  };
}
