import fs from 'node:fs';
import path from 'node:path';
import { buildTailwindRuntimeCss } from './frontend_tailwind_build.mjs';
import { buildFrontendAssetHash, readFrontendAssetVersion } from './frontend_asset_version.mjs';

const LOGIN_SECTION_START = '/* SUXIOS login visual refresh */';
const LOGIN_SECTION_END = '/* SUXIOS logged-in app taste polish:';

function extractBalancedRule(source, selector, startAt = 0) {
  const start = source.indexOf(selector, startAt);
  if (start < 0) throw new Error(`Missing login critical CSS selector: ${selector}`);
  const open = source.indexOf('{', start);
  if (open < 0) throw new Error(`Missing opening brace for login critical CSS selector: ${selector}`);

  let depth = 0;
  for (let index = open; index < source.length; index += 1) {
    if (source[index] === '{') depth += 1;
    if (source[index] !== '}') continue;
    depth -= 1;
    if (depth === 0) return source.slice(start, index + 1);
  }
  throw new Error(`Missing closing brace for login critical CSS selector: ${selector}`);
}

export async function buildLoginCriticalCss(repoRoot) {
  const publicRoot = path.join(repoRoot, 'public');
  const indexPath = path.join(publicRoot, 'index.html');
  const bootstrapPath = path.join(publicRoot, 'app-bootstrap.js');
  const tailwindSourcePath = path.join(publicRoot, 'tailwind.full.css');
  const stylePath = path.join(publicRoot, 'style.css');
  const style = fs.readFileSync(stylePath, 'utf8');
  const loginStart = style.indexOf(LOGIN_SECTION_START);
  const loginEnd = style.indexOf(LOGIN_SECTION_END, loginStart);
  if (loginStart < 0 || loginEnd <= loginStart) {
    throw new Error('Unable to locate the bounded public-login CSS section in public/style.css.');
  }

  const globalEnd = style.indexOf('/* Tailwind');
  if (globalEnd < 0) throw new Error('Unable to locate the public style global guard boundary.');
  const rootRule = extractBalancedRule(style, ':root {');
  const localeRule = extractBalancedRule(style, '.locale-switch {');
  const localeSelectRule = extractBalancedRule(style, '.locale-switch select {', style.indexOf('.locale-switch {'));
  const tailwind = await buildTailwindRuntimeCss(
    fs.readFileSync(tailwindSourcePath, 'utf8'),
    [indexPath, bootstrapPath],
  );

  return [
    '/* Generated by scripts/build_login_critical_css.mjs. */',
    tailwind.trim(),
    style.slice(0, globalEnd).trim(),
    rootRule.trim(),
    localeRule.trim(),
    localeSelectRule.trim(),
    style.slice(loginStart, loginEnd).trim(),
  ].join('\n\n') + '\n';
}

export async function inspectLoginCriticalCss(repoRoot) {
  const artifactPath = path.join(repoRoot, 'public/login-critical.css');
  const indexPath = path.join(repoRoot, 'public/index.html');
  const stylePath = path.join(repoRoot, 'public/style.css');
  const expected = await buildLoginCriticalCss(repoRoot);
  const artifact = fs.existsSync(artifactPath) ? fs.readFileSync(artifactPath, 'utf8') : '';
  const html = fs.readFileSync(indexPath, 'utf8');
  const failures = [];
  let version = null;

  try {
    version = readFrontendAssetVersion(html, 'login-critical.css');
  } catch (error) {
    failures.push(error.message);
  }
  if (artifact !== expected) failures.push('public/login-critical.css is stale or missing.');
  if (artifact && (!artifact.endsWith('\n') || artifact.endsWith('\n\n'))) {
    failures.push('public/login-critical.css must end with exactly one newline.');
  }
  const hash = buildFrontendAssetHash(artifact);
  if (!version || version.hash !== hash) failures.push('public/index.html must reference the current login-critical.css hash.');
  if (artifact && Buffer.byteLength(artifact) >= Buffer.byteLength(fs.readFileSync(stylePath)) * 0.2) {
    failures.push('Public login critical CSS must stay below 20% of the full application stylesheet.');
  }

  return {
    failures,
    metrics: {
      artifact_bytes: Buffer.byteLength(artifact),
      full_style_bytes: Buffer.byteLength(fs.readFileSync(stylePath)),
      artifact_hash: hash,
    },
  };
}
