import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const readContractSource = (file) => file === 'public/index.html'
  ? `${read(file)}\n${read('resources/frontend/app-template.html')}\n${read('public/app-main.js')}`
  : read(file);
const checks = [];

function check(file, label, ok, detail = '') {
  checks.push({ file, label, ok: Boolean(ok), detail });
}

function includesAll(file, label, needles) {
  const source = readContractSource(file);
  for (const needle of needles) {
    check(file, `${label}: ${needle}`, source.includes(needle), needle);
  }
}

function excludesAll(file, label, needles) {
  const source = readContractSource(file);
  for (const needle of needles) {
    check(file, `${label}: excludes ${needle}`, !source.includes(needle), needle);
  }
}

const packageJson = JSON.parse(read('package.json'));
check(
  'package.json',
  'package exposes Revenue AI closure verifier',
  packageJson.scripts?.['verify:revenue-ai-closure'] === 'node scripts/verify_revenue_ai_closure_contract.mjs',
  'verify:revenue-ai-closure'
);
check(
  'package.json',
  'p0 guards include Revenue AI closure verifier',
  String(packageJson.scripts?.['verify:p0-guards'] || '').includes('npm run verify:revenue-ai-closure'),
  'verify:p0-guards'
);
check(
  'package.json',
  'package exposes Ctrip-only Revenue AI runtime verifier',
  packageJson.scripts?.['verify:revenue-ai-ctrip-scope'] === 'C:\\xampp\\php\\php.exe scripts\\verify_revenue_ai_ctrip_scope.php',
  'verify:revenue-ai-ctrip-scope'
);
check(
  'package.json',
  'package exposes Ctrip-only Revenue AI generation smoke verifier',
  packageJson.scripts?.['verify:revenue-ai-ctrip-generation'] === 'C:\\xampp\\php\\php.exe scripts\\verify_revenue_ai_ctrip_generation_smoke.php',
  'verify:revenue-ai-ctrip-generation'
);
check(
  'package.json',
  'package exposes Ctrip-only Revenue AI operation ROI smoke verifier',
  packageJson.scripts?.['verify:revenue-ai-ctrip-operation-roi'] === 'C:\\xampp\\php\\php.exe scripts\\verify_revenue_ai_ctrip_generation_smoke.php --complete-operation-roi=1',
  'verify:revenue-ai-ctrip-operation-roi'
);
check(
  'package.json',
  'package exposes Ctrip pricing input pipeline runtime verifier',
  packageJson.scripts?.['verify:revenue-ai-ctrip-pricing-inputs'] === 'C:\\xampp\\php\\php.exe scripts\\verify_revenue_ai_ctrip_pricing_input_pipeline.php',
  'verify:revenue-ai-ctrip-pricing-inputs'
);
check(
  'package.json',
  'package exposes operator-file Ctrip pricing pre-execute gate',
  packageJson.scripts?.['verify:revenue-ai-ctrip-pricing-file'] === 'C:\\xampp\\php\\php.exe scripts\\verify_revenue_ai_ctrip_pricing_input_pipeline.php',
  'verify:revenue-ai-ctrip-pricing-file'
);
check(
  'package.json',
  'package exposes transaction verifier for Ctrip pending review packet',
  packageJson.scripts?.['verify:revenue-ai-ctrip-pending-review-packet'] === 'C:\\xampp\\php\\php.exe scripts\\verify_revenue_ai_ctrip_pending_review_packet.php',
  'verify:revenue-ai-ctrip-pending-review-packet'
);
check(
  'package.json',
  'package exposes transaction verifier for Ctrip review-decision runner',
  packageJson.scripts?.['verify:revenue-ai-ctrip-review-decision'] === 'C:\\xampp\\php\\php.exe scripts\\verify_revenue_ai_ctrip_review_decision.php',
  'verify:revenue-ai-ctrip-review-decision'
);
check(
  'package.json',
  'package exposes read-only Ctrip pricing source-field audit',
  packageJson.scripts?.['inspect:revenue-ai-ctrip-pricing-sources'] === 'C:\\xampp\\php\\php.exe scripts\\inspect_revenue_ai_ctrip_pricing_source_fields.php',
  'inspect:revenue-ai-ctrip-pricing-sources'
);
check(
  'package.json',
  'package exposes read-only Ctrip traffic demand trend report',
  packageJson.scripts?.['report:revenue-ai-ctrip-traffic-demand-trend'] === 'C:\\xampp\\php\\php.exe scripts\\report_revenue_ai_ctrip_traffic_demand_trend.php',
  'report:revenue-ai-ctrip-traffic-demand-trend'
);
check(
  'package.json',
  'package exposes read-only Ctrip input readiness report',
  packageJson.scripts?.['report:revenue-ai-ctrip-input-readiness'] === 'C:\\xampp\\php\\php.exe scripts\\report_revenue_ai_ctrip_input_readiness.php',
  'report:revenue-ai-ctrip-input-readiness'
);
check(
  'package.json',
  'package exposes read-only Ctrip pricing evidence candidate report',
  packageJson.scripts?.['report:revenue-ai-ctrip-pricing-evidence-candidates'] === 'C:\\xampp\\php\\php.exe scripts\\report_revenue_ai_ctrip_pricing_evidence_candidates.php',
  'report:revenue-ai-ctrip-pricing-evidence-candidates'
);
check(
  'package.json',
  'package exposes read-only Ctrip external input candidate report',
  packageJson.scripts?.['report:revenue-ai-ctrip-external-input-candidates'] === 'node scripts/report_revenue_ai_ctrip_external_input_candidates.mjs',
  'report:revenue-ai-ctrip-external-input-candidates'
);
check(
  'package.json',
  'package exposes read-only Ctrip auto input eligibility report',
  packageJson.scripts?.['report:revenue-ai-ctrip-auto-input-eligibility'] === 'node scripts/report_revenue_ai_ctrip_auto_input_eligibility.mjs',
  'report:revenue-ai-ctrip-auto-input-eligibility'
);
check(
  'package.json',
  'package exposes Ctrip pricing operator packet report',
  packageJson.scripts?.['report:revenue-ai-ctrip-pricing-operator-packet'] === 'C:\\xampp\\php\\php.exe scripts\\report_revenue_ai_ctrip_pricing_operator_packet.php',
  'report:revenue-ai-ctrip-pricing-operator-packet'
);
check(
  'package.json',
  'package exposes Ctrip real-input gap pack report',
  packageJson.scripts?.['report:revenue-ai-ctrip-gap-pack'] === 'C:\\xampp\\php\\php.exe scripts\\report_revenue_ai_ctrip_gap_pack.php',
  'report:revenue-ai-ctrip-gap-pack'
);
check(
  'package.json',
  'package exposes Ctrip pending review packet report',
  packageJson.scripts?.['report:revenue-ai-ctrip-pending-review-packet'] === 'C:\\xampp\\php\\php.exe scripts\\report_revenue_ai_ctrip_pending_review_packet.php',
  'report:revenue-ai-ctrip-pending-review-packet'
);
check(
  'package.json',
  'package exposes Ctrip operator handoff bundle exporter',
  packageJson.scripts?.['export:revenue-ai-ctrip-operator-bundle'] === 'C:\\xampp\\php\\php.exe scripts\\export_revenue_ai_ctrip_operator_bundle.php',
  'export:revenue-ai-ctrip-operator-bundle'
);
check(
  'package.json',
  'package exposes Ctrip operator handoff bundle verifier',
  packageJson.scripts?.['verify:revenue-ai-ctrip-operator-bundle'] === 'node scripts/verify_revenue_ai_ctrip_operator_bundle.mjs',
  'verify:revenue-ai-ctrip-operator-bundle'
);
check(
  'package.json',
  'package exposes no-execute Ctrip operator handoff bundle preflight',
  packageJson.scripts?.['verify:revenue-ai-ctrip-operator-bundle-preflight'] === 'node scripts/verify_revenue_ai_ctrip_operator_bundle_preflight.mjs',
  'verify:revenue-ai-ctrip-operator-bundle-preflight'
);
check(
  'package.json',
  'package exposes no-execute Ctrip operator CSV-to-JSON preflight',
  packageJson.scripts?.['verify:revenue-ai-ctrip-operator-csv-preflight'] === 'node scripts/verify_revenue_ai_ctrip_operator_csv_preflight.mjs',
  'verify:revenue-ai-ctrip-operator-csv-preflight'
);
check(
  'package.json',
  'package exposes no-execute Ctrip operator quick-reply preflight',
  packageJson.scripts?.['verify:revenue-ai-ctrip-operator-quick-reply-preflight'] === 'node scripts/verify_revenue_ai_ctrip_operator_quick_reply_preflight.mjs',
  'verify:revenue-ai-ctrip-operator-quick-reply-preflight'
);
check(
  'package.json',
  'package exposes Ctrip review-decision template exporter',
  packageJson.scripts?.['export:revenue-ai-ctrip-review-template'] === 'C:\\xampp\\php\\php.exe scripts\\execute_revenue_ai_ctrip_review_decision.php --print-template=1',
  'export:revenue-ai-ctrip-review-template'
);
check(
  'package.json',
  'package exposes dry-run Ctrip pricing input importer',
  packageJson.scripts?.['import:revenue-ai-ctrip-pricing-inputs'] === 'C:\\xampp\\php\\php.exe scripts\\import_revenue_ai_ctrip_pricing_inputs.php',
  'import:revenue-ai-ctrip-pricing-inputs'
);
check(
  'package.json',
  'package exposes validate-only Ctrip pricing input verifier',
  packageJson.scripts?.['validate:revenue-ai-ctrip-pricing-inputs'] === 'C:\\xampp\\php\\php.exe scripts\\import_revenue_ai_ctrip_pricing_inputs.php --validate-only=1',
  'validate:revenue-ai-ctrip-pricing-inputs'
);
check(
  'package.json',
  'package exposes lint-only Ctrip pricing input verifier',
  packageJson.scripts?.['lint:revenue-ai-ctrip-pricing-inputs'] === 'C:\\xampp\\php\\php.exe scripts\\import_revenue_ai_ctrip_pricing_inputs.php --lint-only=1',
  'lint:revenue-ai-ctrip-pricing-inputs'
);
check(
  'package.json',
  'package exposes current Ctrip pricing input template exporter',
  packageJson.scripts?.['export:revenue-ai-ctrip-pricing-template'] === 'C:\\xampp\\php\\php.exe scripts\\import_revenue_ai_ctrip_pricing_inputs.php --print-current-template',
  'export:revenue-ai-ctrip-pricing-template'
);
check(
  'package.json',
  'package exposes Ctrip pricing CSV intake to JSON builder',
  packageJson.scripts?.['build:revenue-ai-ctrip-pricing-input-from-csv'] === 'C:\\xampp\\php\\php.exe scripts\\import_revenue_ai_ctrip_pricing_inputs.php --build-json-from-csv=1',
  'build:revenue-ai-ctrip-pricing-input-from-csv'
);
check(
  'package.json',
  'package exposes explicit execute Ctrip pricing input importer',
  packageJson.scripts?.['import:revenue-ai-ctrip-pricing-inputs:execute'] === 'C:\\xampp\\php\\php.exe scripts\\import_revenue_ai_ctrip_pricing_inputs.php --execute=1',
  'import:revenue-ai-ctrip-pricing-inputs:execute'
);
check(
  'package.json',
  'package exposes gated Ctrip pricing file to pending review runner',
  packageJson.scripts?.['run:revenue-ai-ctrip-pricing-file-to-pending-review'] === 'C:\\xampp\\php\\php.exe scripts\\execute_revenue_ai_ctrip_pricing_file.php',
  'run:revenue-ai-ctrip-pricing-file-to-pending-review'
);
check(
  'package.json',
  'package exposes Ctrip quick reply to pending review runner',
  packageJson.scripts?.['run:revenue-ai-ctrip-quick-reply-to-pending-review'] === 'node scripts/run_revenue_ai_ctrip_quick_reply_to_pending_review.mjs',
  'run:revenue-ai-ctrip-quick-reply-to-pending-review'
);
check(
  'package.json',
  'package exposes Ctrip review-decision runner',
  packageJson.scripts?.['run:revenue-ai-ctrip-review-decision'] === 'C:\\xampp\\php\\php.exe scripts\\execute_revenue_ai_ctrip_review_decision.php',
  'run:revenue-ai-ctrip-review-decision'
);

includesAll('scripts/verify_revenue_ai_ctrip_scope.php', 'Ctrip-only Revenue AI runtime verifier keeps current DB scope explicit', [
  'RevenueAiOverviewService',
  "'platform' => 'ctrip'",
  "'enabled_channels' => ['ctrip']",
  "'source_channels_exact_ctrip'",
  "'channel_statuses_scoped_ctrip'",
  "'p0_authority_verifier_passed'",
  "'service_p0_gate_scoped_ctrip'",
  'revenue_ai_ctrip_p0_gate_from_authority',
  'revenue_ai_ctrip_p0_verifier_command',
  "'service_p0_gate_reflects_authority'",
  "'status' => $passed ? 'ready' : 'blocked_by_p0_ota_gate'",
  "$filters['p0_downstream_gate']",
  "'manual_review_queue_loaded'",
  "'manual_review_queue_navigation_target'",
  "'agent_and_execution_state_loaded'",
  'verify_p0_ota_field_loop_closure.php',
  "'ctrip_ota_channel'",
  "'meituan_not_present'",
  "'source_policy' => 'read_current_database_revenue_ai_overview_only'",
]);

includesAll('scripts/verify_revenue_ai_ctrip_generation_smoke.php', 'Ctrip generation smoke verifier proves pending AI decision path without persistence', [
  'Db::startTrans()',
  'Db::rollback()',
  'transactional_fixture_rollback_no_ota_write',
  'ctrip_generation_insert_fixture_inputs',
  'RevenueAiOverviewService',
  'OperationManagementService',
  'new Agent($app)',
  'generatePriceSuggestions()',
  '--complete-operation-roi',
  'approveExecutionIntent(',
  'executeExecutionTask(',
  'reviewExecutionTask(',
  "'platform' => 'ctrip'",
  "'enabled_channels' => ['ctrip']",
  "'source_scope' => 'ctrip_ota_channel'",
  "'operator_execution_evidence' => [",
  "'operator_roi_evidence' => [",
  'operator_execution_evidence_keys',
  'operator_roi_evidence_keys',
  'operation_roi_exposes_operator_evidence_summary',
  'overview_effect_review_exposes_operator_evidence_summary',
  'operator_execution_evidence_summary',
  'operator_roi_evidence_summary',
  'local_manual_roi_evidence_no_ota_write',
  'CompetitorAnalysis::PLATFORM_CTRIP',
  'RoomType::STATUS_ENABLED',
  'PriceSuggestion::STATUS_PENDING',
  "'agent_generation_created_pending_suggestion'",
  "'generation_result_keeps_ctrip_manual_review_gate'",
  "'created_suggestion_uses_real_pricing_signals'",
  "'overview_queue_reads_pending_suggestion'",
  "'overview_preflight_moves_to_pending_review'",
  "'ai_to_operation_stays_blocked_before_review'",
  "'manual_review_approves_without_ota_write'",
  "'approved_suggestion_creates_operation_execution_intent'",
  "'execution_intent_keeps_manual_execution_boundary'",
  "'overview_reads_operation_execution_intent_after_review'",
  "'operation_intake_waiting_human_approval'",
  "'operation_intent_approval_creates_manual_task'",
  "'operation_execution_records_local_roi_evidence'",
  "'operation_review_marks_roi_ready'",
  "'overview_reads_operation_roi_ready_after_review'",
  "'operation_execution_tasks'",
  "'operation_execution_evidence'",
  "'operation_execution.roi_ready'",
  "'operation_execution_intents'",
  "'transaction_rolled_back'",
  "'meituan_not_present'",
]);

includesAll('scripts/verify_revenue_ai_ctrip_pricing_input_pipeline.php', 'Ctrip pricing input pipeline runtime verifier protects operator evidence and rollback boundaries', [
  'runtime_operator_input_pipeline_rollback_only',
  'operator_input_file_pre_execute_gate_rollback_only',
  'scripts/import_revenue_ai_ctrip_pricing_inputs.php',
  'scripts/verify_revenue_ai_ctrip_scope.php',
  "'file' =>",
  '--print-current-template',
  '--lint-only=1',
  '--validate-only=1',
  '--force=1',
  'real_input_file_loaded',
  'real_input_file_lint_passes_without_db',
  'real_input_file_validate_only_rolls_back_without_generation',
  'real_input_file_dry_run_generates_pending_review_and_rolls_back',
  'real_input_file_dry_run_keeps_manual_review_gate',
  'real_input_file_dry_run_preserves_operator_source_metadata',
  'ctrip_pricing_pipeline_generation_source_metadata',
  'source_metadata',
  'manual_ctrip_room_type_pricing_guard',
  'manual_demand_forecast',
  'ctrip_historical_traffic_trend',
  'derived_trend_only_no_raw_rows_no_import',
  'not_whole_hotel_occupancy',
  'manual_ctrip_competitor_price_sample',
  'operator_input_evidence_keys',
  'operator_row_source_note_present',
  'traffic_trend_input_lint_passes_without_demand_rows',
  'traffic_trend_input_validate_only_rolls_back_without_generation',
  'traffic_trend_input_dry_run_generates_pending_review_and_rolls_back',
  'traffic_trend_input_dry_run_keeps_manual_review_gate',
  'traffic_trend_input_dry_run_preserves_source_boundaries',
  'ctrip_pricing_pipeline_filled_traffic_trend_payload',
  'transaction-only verifier room row source note',
  'transaction-only verifier demand forecast row source note',
  'transaction-only verifier competitor price row source note',
  'real_input_file_scope_unchanged_after_rollback',
  'real_input_file_meituan_not_present',
  'operator-verified Ctrip pricing inputs',
  'current_real_db_gap_is_explicit',
  'room_types_empty',
  'placeholder_template_lint_fails_without_db',
  'filled_input_lint_passes_without_db',
  'validate_only_rolls_back_without_generation',
  'dry_run_generates_pending_review_and_rolls_back',
  'dry_run_generation_keeps_ctrip_manual_review_gate',
  'dry_run_generation_preserves_operator_source_metadata',
  'current_scope_unchanged_after_dry_run_rollback',
  "'platform' => 'ctrip'",
  "'enabled_channels' => ['ctrip']",
  "'source_scope' => 'ctrip_ota_channel'",
  "'auto_write_ota' => false",
  "'source_policy' => 'runtime_operator_input_pipeline_rollback_only'",
  'PHP_BINARY',
  'proc_open',
  'unlink',
  'meituan_not_present',
]);

includesAll('app/service/RevenuePricingRecommendationService.php', 'Revenue pricing recommendation carries manual Ctrip input metadata into suggestion signals', [
  'manualInputMetadata',
  'manualInputMetadataFromList',
  'manualInputMetadataRows',
  "'source_metadata' =>",
  "'manual_ctrip_room_type_pricing_guard'",
  "'manual_demand_forecast'",
  "'manual_ctrip_competitor_price_sample'",
  "$value['input_type'] ?? ''",
  "'signals' => $signals",
]);

includesAll('app/service/RevenuePricingRecommendationService.php', 'Revenue pricing recommendation accepts Ctrip traffic trend as an explicit demand forecast source', [
  'ctripTrafficDemandForecastSignal',
  'buildCtripTrafficDemandForecastSignal',
  'ctrip_historical_traffic_trend',
  'traffic_trend_score_0_100_for_Ctrip_channel_demand_trend_not_whole_hotel_occupancy_50_means_history_baseline',
  'derived_trend_only_no_raw_rows_no_import',
  'CTRIP_TRAFFIC_SOURCE_ALIASES',
  'CTRIP_COMPETITOR_PLATFORM_VALUES',
  "whereIn('ota_platform', self::CTRIP_COMPETITOR_PLATFORM_VALUES)",
  'order_submit_num',
  'order_filling_num',
  'detail_exposure',
  'list_exposure',
  "'source_scope' => 'ctrip_ota_channel'",
  "'auto_write_ota' => false",
  "$trafficForecast = $this->ctripTrafficDemandForecastSignal($hotelId, $targetDate);",
]);

includesAll('scripts/inspect_revenue_ai_ctrip_pricing_source_fields.php', 'Ctrip pricing source audit stays read-only and refuses to fabricate importable pricing inputs', [
  'RevenueAiOverviewService',
  'online_daily_data',
  'read_existing_online_daily_data_metadata_and_field_keys_only',
  'raw_values_exposed',
  'database_written',
  'ctrip_pricing_sources_field_facts',
  'can_prefill_import_file',
  'read_only_field_audit_no_values_no_import',
  'operator_verified_pricing_inputs_required',
  'room_types_enabled',
  'floor_price_or_min_rate_guard',
  'demand_forecast',
  'competitor_price_samples',
  'fact_metric_keys',
  'raw_key_samples_matching_pricing_terms',
  'sample_rows_without_raw_values',
  'candidate_source_audit',
  'metadata_counts_only_no_raw_values_no_import',
  'required_input_table_counts',
  'room_types_with_price_guards',
  'demand_forecasts_target_date',
  'competitor_analysis_ctrip_recent_7d',
  'accepted_demand_source_status',
  'demand_source_can_use_ctrip_historical_traffic_trend_no_raw_rows_no_import',
  'demand_source_status',
  'demand_forecast_row_required',
  'ctrip_traffic_demand_forecast_count',
  'room_type_price_guard_or_named_ctrip_competitor_sample_missing',
  'ctrip_room_pricing_evidence_counts',
  'roomTypeNeedles',
  'priceGuardNeedles',
  'online_daily_data_room_type_key_target_date',
  'online_daily_data_price_guard_key_target_date',
  'ota_ctrip_metric_facts_room_type_key_all_dates',
  'ota_ctrip_entity_snapshots_price_guard_key_all_dates',
  'ota_ctrip_metric_facts_room_like_all_dates',
  'ota_ctrip_entity_snapshots_room_like_all_dates',
  'can_generate_operator_file_from_existing_db',
  'candidate_sources_metadata_only',
  'operator_input_locators',
  'operator_input_locators_metadata_only',
  'metadata_locators_only_no_raw_values_no_import',
  'Use report:revenue-ai-ctrip-traffic-demand-trend as the allowed Ctrip historical traffic trend forecast source',
  'source_trace_id',
  'matched_paths',
  'inspect_current_ota_evidence',
  'pre_execute_gate',
  'ctrip_pricing_sources_hotel_arg',
  "' --hotel-id=' . $hotelId",
  '$hotelArg',
  'meituan',
]);

includesAll('scripts/report_revenue_ai_ctrip_pricing_evidence_candidates.php', 'Ctrip pricing evidence candidates stay read-only and non-importable', [
  'read_existing_online_daily_data_ctrip_candidate_values_only',
  'raw_rows_exposed',
  'candidate_values_exposed',
  'database_written',
  'auto_write_ota',
  'importable_without_operator_review',
  'room_type_candidates',
  'price_observation_candidates',
  'competitor_aggregate_candidates',
  'candidate_requires_operator_confirmation',
  'observed_ctrip_price_metric_not_floor_guard',
  'competitor_aggregate_not_price_sample',
  'operator-approved floor/protection min_price',
  'named Ctrip competitor price samples',
  'Price observations are not floor/protection prices.',
  'Competitor aggregates are not named competitor price samples.',
  'online_daily_data#',
  'source=ctrip',
  'meituan_scope_included',
  "['json', 'markdown', 'csv']",
]);

includesAll('scripts/report_revenue_ai_ctrip_pricing_operator_packet.php', 'Ctrip operator packet stays read-only and keeps real input gates explicit', [
  'read_only_operator_decision_packet_no_values_no_import',
  'raw_values_exposed',
  'database_written',
  'auto_write_ota',
  'meituan_scope_included',
  'inspect_revenue_ai_ctrip_pricing_source_fields.php',
  'import_revenue_ai_ctrip_pricing_inputs.php',
  'verify_revenue_ai_ctrip_scope.php',
  'operator_required_fields',
  'operator_collection_priorities',
  'Operator Collection Priorities',
  'Operator Evidence Locators',
  'operator_input_locators',
  'operator_input_locators_metadata_only',
  'Locator row ids and source traces are metadata only',
  'ctrip_pricing_packet_collection_priorities',
  'operator_collection_priorities_present',
  'Ctrip source hints are for locating evidence only',
  'demand_or_forecast_key',
  'No demand_forecasts row is required now',
  'optional manual override only; leave empty when using Ctrip historical traffic trend',
  'candidate_source_audit',
  'Candidate Source Audit',
  'required_input_table_counts',
  'ctrip_room_pricing_evidence_counts',
  'prefill_eligibility.status',
  'can_generate_operator_file_from_existing_db',
  'candidate_source_audit_counts_only',
  'fillable_template',
  'allowed_commands',
  'forbidden_shortcuts',
  'stop_conditions',
  'operator_packet',
  'export_operator_bundle',
  'export:revenue-ai-ctrip-operator-bundle',
  '--output-dir=<operator-bundle-dir>',
  'pre_execute_gate',
  'post_review_roi_boundary_gate_present',
  'gate_then_execute_and_generate_pending_review',
  'pending_review_packet',
  'report:revenue-ai-ctrip-pending-review-packet',
  'verify_pending_review_packet',
  'verify:revenue-ai-ctrip-pending-review-packet',
  'export_review_decision_template',
  'export:revenue-ai-ctrip-review-template',
  '--suggestion-id=<pending-suggestion-id>',
  '--output=<review-decision-json-path>',
  'validate_review_decision',
  'execute_review_decision_and_create_operation_intent',
  'verify_review_decision',
  'verify:revenue-ai-ctrip-review-decision',
  'verify_operation_roi_boundary',
  'verify:revenue-ai-ctrip-operation-roi',
  'run:revenue-ai-ctrip-review-decision',
  'run:revenue-ai-ctrip-pricing-file-to-pending-review',
  'verify:revenue-ai-ctrip-pricing-file',
  'report:revenue-ai-ctrip-traffic-demand-trend',
  'demand_trend_draft',
  'source_audit_passed',
  'template_export_passed',
  'runtime_scope_passed',
  'no_meituan_source_summary',
  'operator_input_still_required',
  'can_prefill_import_file',
  'room_types',
  'demand_forecasts',
  'competitor_price_samples',
  'ota_platform=ctrip',
  'Do not use Meituan rows or whole-hotel operating values',
  'Do not convert traffic, business, quality, or peer-rank rows into room types, price guards, or competitor prices',
  'demand forecast can only use report:revenue-ai-ctrip-traffic-demand-trend',
  'Do not fill missing prices with sample, guessed, fallback, or verifier-only values',
  'Do not set auto_write_ota=true',
  'manual review and ROI evidence',
]);

includesAll('scripts/report_revenue_ai_ctrip_traffic_demand_trend.php', 'Ctrip historical traffic demand trend report stays read-only and scoped', [
  'online_daily_data',
  'ctrip_historical_traffic_trend',
  'read_existing_online_daily_data_ctrip_traffic_aggregates_only',
  'derived_trend_only_no_raw_rows_no_import',
  'source_scope',
  'ctrip_ota_channel',
  'meituan_scope_included',
  'raw_rows_exposed',
  'aggregate_values_exposed',
  'database_written',
  'auto_write_ota',
  'importable_without_operator_review',
  'room_type_key',
  'predicted_occupancy',
  'traffic_trend_score_0_100_for_Ctrip_channel_demand_trend_not_whole_hotel_occupancy_50_means_history_baseline',
  'predicted_demand',
  'Ctrip historical traffic demand index where 100 means history-window baseline',
  'blocked_by_insufficient_traffic_history',
]);

includesAll('scripts/report_revenue_ai_ctrip_input_readiness.php', 'Ctrip input readiness report scans counts and traffic trend without creating pricing inputs', [
  'read_current_database_counts_and_ctrip_traffic_trend_only_no_raw_rows_no_import',
  'RevenuePricingRecommendationService',
  'raw_rows_exposed',
  'database_written',
  'auto_write_ota',
  'source_scope',
  'ctrip_ota_channel',
  'meituan_scope_included',
  'complete_input_candidates',
  'traffic_trend_demand_source_candidates',
  'scan_status',
  'scan_scope_note',
  'no_complete_candidate_in_current_scan',
  'all_scanned_ctrip_hotel_dates_limited_by_business_date_and_limit',
  'target_hotel_scanned_ctrip_dates_limited_by_business_date_and_limit',
  'best_available_candidate',
  'best_available_missing_inputs',
  'operator_action_required',
  'fill room_types_enabled with operator-verified room inventory',
  'fill floor_price_or_min_rate_guard with operator-approved price guard',
  'provide named Ctrip competitor_price_samples',
  'rerun operator bundle preflight before execute/generate',
  'accepted_demand_forecast_sources',
  'target_date_candidate',
  'current_required_real_inputs_before_execute',
  'target_date_demand_source',
  'target_date_missing_inputs',
  'complete_input_candidate',
  'demand_forecast_source',
  'ctrip_historical_traffic_trend',
  'required_before_execute',
  'room_types_enabled',
  'floor_price_or_min_rate_guard',
  'demand_forecast_source (demand_forecasts row or ctrip_historical_traffic_trend)',
  'competitor_price_samples',
  'online_daily_data',
  'room_types',
  'demand_forecasts',
  'competitor_analysis',
  'competitor_price_log',
  'ctrip_input_readiness_apply_ctrip_platform_filter',
  "whereIn($column, [1, '1', 'ctrip', 'xc'])",
  "where('store_id', $hotelId)",
  "where('readback_verified', 1)",
  "whereIn('validation_status', ['available', 'normal', 'ok', 'valid', 'verified'])",
  "whereNotNull('comparison_key')",
  'This report reads counts and aggregate Ctrip traffic trend only; it does not expose raw Ctrip rows.',
  'No OTA price write is allowed by this report.',
]);

includesAll('scripts/report_revenue_ai_ctrip_external_input_candidates.mjs', 'Ctrip external input candidate report is read-only and not importable', [
  'bundle_manifest',
  'bundle_manifest_with_cli_overrides',
  'bundle_manifest_path',
  'scope_source',
  'Missing operator bundle manifest.json under --dir.',
  'read_allowlisted_external_project_materials_candidates_only_no_db_no_ota_write',
  'external_project_materials_for_ctrip_operator_review',
  'candidate_hint_only_no_import_no_db_no_ota_write',
  'database_written: false',
  'auto_write_ota: false',
  'importable_value: false',
  'operator_confirmation_required: true',
  'room_count_candidates',
  'price_assumption_candidates',
  'competitor_reference_candidates',
  'room_concept_candidates',
  'market_distribution_candidates',
  'reference_final4_2_text.txt',
  'feasibility_project_plan_v3_extended.md',
  'historical_room_concept_candidate',
  'historical_ctrip_market_price_distribution',
  'old_project_context',
  'not_named_competitor_sample',
  'not_floor_price_guard',
  'not_current_ctrip_price_sample',
  'not_recent_7d_sample',
  'room_types_enabled',
  'floor_price_or_min_rate_guard',
  'competitor_price_samples',
  'does_not_write_ota_prices',
  'Room count candidates are not Ctrip room type mappings.',
  '350/450 price assumptions are not floor/protection prices.',
  'Historical competitor references are not current recent-7-day named Ctrip competitor samples.',
  'Historical room concept candidates are not current Ctrip room type mappings.',
  'Historical market price distributions are not current named Ctrip competitor price samples.',
]);

includesAll('scripts/report_revenue_ai_ctrip_auto_input_eligibility.mjs', 'Ctrip auto input eligibility report is read-only and blocks candidate-only auto closure', [
  'read_operator_bundle_evidence_only_no_db_no_ota_write',
  'blocked_by_operator_real_inputs',
  'auto_close_eligible',
  'raw_rows_exposed: false',
  'database_written: false',
  'auto_write_ota: false',
  'importable_value: false',
  'auto_import_allowed: false',
  'operator_reply_file',
  'OPERATOR_QUICK_REPLY.md',
  'operator_reply_keys_are_not_importable_until_preflight_passes',
  'operator_question',
  'reply_keys',
  'competitor_room_type_key',
  'room_type_1_key',
  'room_type_1_base_price',
  'competitor_sample_1_room_type_key',
  'room_name_or_room_count_candidates_do_not_prove_operator_enabled_room_type_key_and_sellable_room_count',
  'observed_average_prices_and_350_450_assumptions_are_not_operator_approved_base_min_max_guards',
  'competitor_aggregates_and_historical_market_references_are_not_recent_named_ctrip_price_samples',
  'ctrip_historical_traffic_trend_is_accepted_as_demand_forecast_source',
  'Do not write OTA prices.',
]);

includesAll('scripts/report_revenue_ai_ctrip_gap_pack.php', 'Ctrip real-input gap pack reports the whole Revenue AI closure without reading raw capture or writing data', [
  'read_current_revenue_ai_overview_and_operator_bundle_only',
  'read_current_revenue_ai_overview_operator_bundle_and_p0_authority_verifier',
  'raw_capture_read',
  'does_not_run_p0_verifier_or_read_raw_capture',
  'run-p0-verifier',
  'run_p0_verifier',
  'p0_authority_verifier_run',
  'ran_p0_authority_verifier_without_raw_capture_or_writes',
  'p0_field_loop_verifier_ready',
  'database_written',
  'auto_write_ota',
  'meituan_scope_included',
  'ctrip_ota_channel',
  'ctrip_p0_target_day',
  'pricing_generation_inputs',
  'ai_pending_review_suggestion',
  'human_review_to_operation_intent',
  'execution_evidence_and_roi_window',
  'investment_manual_review',
  'pricing-input-fillable.json',
  'input_readiness_scan',
  'report:revenue-ai-ctrip-input-readiness',
  'external_input_candidates',
  'report:revenue-ai-ctrip-external-input-candidates',
  'csv_to_json_preflight',
  'verify:revenue-ai-ctrip-operator-csv-preflight',
  'operator_input_evidence',
  'demand_forecast_source_status',
  'ctrip_historical_traffic_trend',
  'ctrip_traffic_demand_forecast_count',
  'operator_review_evidence.reviewed_by',
  'operator_review_evidence.reviewed_at',
  'operator_review_evidence.decision_basis',
  'operator_review_evidence.price_guard_source',
  'operator_review_evidence.operation_intent_source',
  'manual_execution_evidence.executed_by',
  'manual_execution_evidence.executed_at',
  'manual_execution_evidence.execution_basis',
  'manual_execution_evidence.room_rate_mapping_source',
  'manual_execution_evidence.execution_receipt_or_screenshot_path',
  'manual_roi_evidence.reviewed_by',
  'manual_roi_evidence.reviewed_at',
  'manual_roi_evidence.before_metric_source',
  'manual_roi_evidence.after_metric_source',
  'manual_roi_evidence.roi_calculation_basis',
  'manual_roi_evidence.roi_receipt_or_screenshot_path',
  'post_pricing_handoff_checklist',
  'ctrip_gap_pack_post_pricing_handoff_checklist',
  'Post-Pricing Handoff Checklist',
  'manual_operator_evidence_only_no_ota_write',
  'operator_roi_review_summary',
  'manual_execution_recorded',
  'manual_roi_metrics_collected',
  'ctrip_ota_channel_manual_review',
  'ctrip_ota_channel_execution_evidence',
  'ctrip_ota_channel_roi_evidence',
  'not whole-hotel truth',
  'placeholder_details',
  'real-input-checklist.json',
  'ctrip_gap_pack_real_input_checklist_items',
  'csv_row_number',
  'csv_section',
  'csv_column',
  'CSV coordinates refer to `pricing-input-intake.csv`',
  'expected_real_input',
  'forbidden_fill',
  'pricing_operator_packet',
  'report:revenue-ai-ctrip-pricing-operator-packet',
  'Fillable Placeholder Checklist',
  'previous_day',
  'next_day',
  'revenue',
  'room_nights',
  'orders',
  'conversion',
  'traffic',
  'operation_execution.roi_ready',
  'Ctrip OTA channel evidence must not be promoted to whole-hotel operating truth.',
  'Do not fill missing room, price, demand, competitor, execution, or ROI values with samples, guesses, fallbacks, or verifier-only fixtures.',
  'Manual review, execution, and ROI handoff evidence must carry operator fields; placeholders or verifier-only evidence do not close the real loop.',
]);

includesAll('scripts/export_revenue_ai_ctrip_operator_bundle.php', 'Ctrip operator bundle exports handoff files without data writes', [
  'operator_handoff_bundle_no_values_no_import',
  'refresh-evidence',
  'refresh_evidence',
  'preserved_input_files',
  'pricing-input-fillable.json',
  'pricing-input-intake.csv',
  'ctrip_operator_bundle_protected_input_file_keys',
  'ctrip_operator_bundle_preserve_file',
  'ctrip_operator_bundle_assert_preserved_fillable_scope',
  'Use a new output directory or intentional --force=1.',
  'pricing-input-template.json',
  'pricing-input-fillable.json',
  'operator-packet.md',
  'OPERATOR_INTAKE_FORM.md',
  'CTRIP_CLOSURE_RUNBOOK.md',
  'REAL_INPUT_TODO.md',
  'real-input-checklist.json',
  'pricing-input.schema.json',
  'pricing-input-intake.csv',
  'operator-action-sheet.csv',
  'OPERATOR_CONFIRMATION_BRIEF.md',
  'operator-confirmation-brief.csv',
  'OPERATOR_QUICK_REPLY.md',
  'OPERATOR_REAL_INPUT_REQUEST.md',
  'OPERATION_ROI_EVIDENCE_REQUEST.md',
  'operator-input-locators.csv',
  'OPERATOR_REVIEW_DRAFT.md',
  'demand-trend-draft.json',
  'demand-trend-draft.md',
  'pricing-evidence-candidates.json',
  'pricing-evidence-candidates.md',
  'pricing-evidence-candidates.csv',
  'external-input-candidates.json',
  'external-input-candidates.md',
  'external-input-candidates.csv',
  'auto-input-eligibility.json',
  'auto-input-eligibility.md',
  'input-readiness.json',
  'input-readiness.md',
  'pending-review-packet.json',
  'current-scope.json',
  'manifest.json',
  'raw_values_exposed',
  'database_written',
  'auto_write_ota',
  'meituan_scope_included',
  'operator_input_evidence',
  'operator_intake_form_markdown',
  'closure_runbook_markdown',
  'real_input_todo_markdown',
  'real_input_checklist_json',
  'pricing_input_schema_json',
  'pricing_input_intake_csv',
  'operator_action_sheet_csv',
  'operator_confirmation_brief_markdown',
  'operator_confirmation_brief_csv',
  'operator_confirmation_brief',
  'operator_confirmation_brief_no_values_no_import',
  'minimum_human_confirmation_brief_not_importable',
  'operator_quick_reply',
  'operator_quick_reply_no_values_no_import',
  'human_quick_reply_not_importable',
  'operator_real_input_request',
  'operator_request_no_values_no_import',
  'human_real_input_request_not_importable',
  'operator_real_input_request_markdown',
  'ctrip_operator_bundle_operator_real_input_request',
  'operation_roi_evidence_request',
  'human_operation_roi_evidence_request_no_values_no_import',
  'human_operation_roi_evidence_request_not_importable',
  'operation_roi_evidence_request_markdown',
  'ctrip_operator_bundle_operation_roi_evidence_request',
  'proves_execution_or_roi',
  'quick_reply_apply_to_fillable',
  'quick_reply_to_pending_review',
  'fillable_write_policy',
  'explicit_write_fillable_flag_only_after_no_execute_preflight_passes_no_db_no_ota_write',
  'pending_review_policy',
  'explicit_execute_only_local_pending_review_no_ota_write_manual_review_required',
  'pending_review_runner_command',
  'ctrip_operator_bundle_quick_reply_hint_rows',
  'competitor_room_type_key',
  'Leave `competitor_room_type_key` blank only when it should reuse `room_type_key`.',
  'room_type_1_key=',
  'room_type_2_key=',
  'competitor_sample_1_room_type_key=',
  'competitor_sample_2_competitor_price=',
  'Optional multi-row format',
  'Review Hints (Not Importable)',
  'Candidate hints are copied from `OPERATOR_CONFIRMATION_BRIEF.md` and `operator-confirmation-brief.csv`',
  'candidate_values_importable',
  'input_readiness_scan',
  'input_readiness_json',
  'input_readiness_markdown',
  'read_current_database_counts_and_ctrip_traffic_trend_only_no_raw_rows_no_import',
  'target_date_missing_inputs',
  'table_counts',
  'auto_input_eligibility',
  'read_operator_bundle_evidence_only_no_db_no_ota_write',
  'full_auto_close_eligible',
  'auto_import_allowed',
  'ctrip_operator_bundle_operator_action_sheet_csv',
  'candidate_to_operator_action_sheet_not_importable',
  'candidate_hints_mapped_to_fill_fields_no_values_no_import',
  'operator_confirmation_required',
  'target_json_path',
  'target_csv_section',
  'target_csv_column',
  'operator_required_action',
  'operator_confirmed_value',
  '$.room_types.0.key',
  '$.competitor_price_samples.0.room_type_key',
  'external historical room concept',
  'external room count clues',
  'external 350/450 assumptions',
  'external historical competitor or market clues',
  'field-by-field action list',
  'map candidate hints to exact `pricing-input-intake.csv` fields',
  'ctrip_operator_bundle_csv_cell_hint',
  'ctrip_operator_bundle_real_input_todo',
  'ctrip_operator_bundle_operator_intake_form',
  'ctrip_operator_bundle_operator_review_draft',
  'ctrip_operator_bundle_closure_runbook',
  'ctrip_operator_bundle_real_input_checklist',
  'ctrip_operator_bundle_pricing_input_schema',
  'ctrip_operator_bundle_demand_source_is_traffic_trend',
  'No demand_forecasts row is required on the Ctrip traffic-trend path.',
  'Manual override only: add `demand_forecasts` rows only when replacing the traffic-trend demand source',
  'ctrip_operator_bundle_placeholder_paths',
  'ctrip_operator_bundle_field_guidance',
  'operator_real_input_checklist_no_values_no_import',
  'human_fillable_collection_not_importable',
  'human_fillable_csv_not_importable_until_converted_and_linted',
  'demand_forecast_row_required',
  'Can remain empty when operator_input_evidence.demand_forecast_source names the Ctrip historical traffic trend report.',
  'leave empty for the current traffic-trend demand source',
  'metadata_locator_csv_not_importable',
  'metadata_locator_only_no_values_no_import',
  'ctrip_operator_bundle_locator_capture_contract',
  'capture_contract_status',
  'metadata_only_no_live_capture_no_import',
  'capture_source_entry',
  'capture_module',
  'field_contract',
  'accepted_evidence',
  'missing_state',
  'operator_next_step',
  'queryRoomTypeInfo',
  'queryVendibilityRoom',
  'queryCompetingHotelsV2',
  'fetchCompetitiveMarket',
  'getLossOrderCompeteHotel',
  'not_blocking_when_ctrip_historical_traffic_trend_ready',
  'missing_current_named_ctrip_competitor_price_sample',
  'manual_closure_sequence_no_ota_price_write',
  'schema_is_authoritative',
  'Optional row-level evidence reference. When filled, PHP importer preserves it as operator_row_source_note in AI pricing source metadata.',
  'https://json-schema.org/draft/2020-12/schema',
  'p0_authority',
  'p0_authority_status: `',
  'p0_authority_command:',
  'raw_capture_read_by_bundle',
  'Ctrip source hints are not importable values',
  'metadata-only evidence navigation',
  'Operator Evidence Locators',
  'Minimum CSV Fill Cells',
  'These cells are the current minimum spreadsheet inputs',
  'Field-Level Real Input Checklist',
  'Room Types And Price Guards',
  'Ctrip Competitor Price Samples',
  'build_fillable_from_csv',
  'csv_to_json_preflight',
  'demand_trend_draft',
  'report:revenue-ai-ctrip-traffic-demand-trend',
  'Ctrip historical traffic trend',
  'Ctrip OTA evidence -> revenue analysis -> AI pricing suggestion -> manual review -> operation intent -> ROI evidence',
  'Fill only real operator-verified Ctrip OTA channel values',
  'operator_row_source_note',
  'source_note`: optional row-level evidence note',
  'source_note` does not replace `operator_input_evidence`',
  'required_fields',
  'expected_real_input',
  'format_guard',
  'forbidden_fill',
  'csv_issue_map.csv_row_number',
  'csv_issue_map.csv_column',
  'csv_section',
  'csv_row_number',
  'csv_column',
  'non-Ctrip OTA',
  'base/min/max numeric > 0; min_price <= base_price; max_price >= base_price; room_count positive integer',
  'analysis_date within 7 days ending at business_date',
  'Locator row ids and source traces are metadata only',
  'operator_input_locators_csv',
  'operator_review_draft_markdown',
  'demand_trend_draft_json',
  'demand_trend_draft_markdown',
  'external_input_candidates',
  'external_input_candidates_json',
  'external_input_candidates_markdown',
  'external_input_candidates_csv',
  'scope_source',
  'bundle_manifest_scope_supported',
  'pricing_evidence_candidates',
  'pricing_evidence_candidates_json',
  'pricing_evidence_candidates_markdown',
  'pricing_evidence_candidates_csv',
  'ctrip_operator_bundle_operator_input_locators_csv',
  'report_revenue_ai_ctrip_pricing_evidence_candidates.php',
  'report_revenue_ai_ctrip_external_input_candidates.mjs',
  'report_revenue_ai_ctrip_traffic_demand_trend.php',
  'scripts/report_revenue_ai_ctrip_auto_input_eligibility.mjs',
  'report:revenue-ai-ctrip-auto-input-eligibility',
  'human_review_draft_not_importable',
  'external_project_materials_for_ctrip_operator_review',
  'read_allowlisted_external_project_materials_candidates_only_no_db_no_ota_write',
  'External Project-Material Clues Not Inputs',
  'External project-material clues are not importable',
  'External project-material clues do not replace Ctrip room type mapping',
  'room counts, 350/450 assumptions, historical room concepts, and historical competitor or market references remain non-importable',
  'not_floor_price_guard',
  'not_current_ctrip_price_sample',
  'demand_trend_draft',
  'requires_room_type_key_mapping',
  'OPERATOR_REVIEW_DRAFT.md',
  'Price Observations Not Guards',
  'Competitor Aggregates Not Price Samples',
  'Copy values only into `pricing-input-fillable.json` after operator confirmation.',
  'read_existing_online_daily_data_ctrip_candidate_values_only',
  'candidate_values_exposed',
  'operator_review_required',
  'Candidate price observations are not floor/protection prices',
  'competitor aggregates are not named competitor price samples',
  'Do not use observed Ctrip average prices as floor/protection prices',
  'pricing_evidence_candidates',
  'report:revenue-ai-ctrip-pricing-evidence-candidates',
  'not executable and not importable evidence',
  'operation_execution.roi_ready',
  'Edit pricing-input-fillable.json with operator-verified Ctrip OTA channel values',
  'Use pricing-input-template.json as read-only context',
  'Do not use Meituan rows, whole-hotel values, sample values, guessed values, fallback values, or verifier-only values.',
  'Do not create OTA price writes from this bundle',
  'report_revenue_ai_ctrip_pricing_operator_packet.php',
  'report_revenue_ai_ctrip_pricing_evidence_candidates.php',
  'import_revenue_ai_ctrip_pricing_inputs.php',
  'report_revenue_ai_ctrip_pending_review_packet.php',
  'verify_revenue_ai_ctrip_scope.php',
  'next_commands_after_filling_template',
  'preflight_no_execute',
  'quick_reply_preflight',
  'csv_to_json_preflight',
  'external_input_candidates',
  'report:revenue-ai-ctrip-external-input-candidates',
  '--dir=',
  'pricing_evidence_candidates',
  'verify:revenue-ai-ctrip-operator-bundle-preflight',
  'verify:revenue-ai-ctrip-operator-csv-preflight',
  'verify:revenue-ai-ctrip-operator-quick-reply-preflight',
  'build:revenue-ai-ctrip-pricing-input-from-csv',
  'lint:revenue-ai-ctrip-pricing-inputs',
  'validate:revenue-ai-ctrip-pricing-inputs',
  'verify:revenue-ai-ctrip-pricing-file',
  'run:revenue-ai-ctrip-pricing-file-to-pending-review',
  'report:revenue-ai-ctrip-pending-review-packet',
  'export:revenue-ai-ctrip-review-template',
  'run:revenue-ai-ctrip-review-decision',
  'verify:revenue-ai-ctrip-operation-roi',
  'verify:revenue-ai-ctrip-scope',
  'Bundle file already exists. Pass --force=1 to overwrite',
  "'source_scope' => 'ctrip_ota_channel'",
  "'enabled_channels' => ['ctrip']",
  'ctrip_operator_bundle_fillable_payload',
  'ctrip_operator_bundle_pricing_input_intake_csv',
  "'operator_intake_form_markdown'",
  "'closure_runbook_markdown'",
  "'pricing_input_intake_csv'",
  "'operator_input_locators_csv'",
  "'pricing_input_fillable_json'",
  '$fillableFile',
]);

{
  const file = 'scripts/export_revenue_ai_ctrip_operator_bundle.php';
  const source = read(file);
  const commandStart = source.indexOf("'next_commands_after_filling_template' => [");
  const commandEnd = commandStart >= 0 ? source.indexOf('        ],\n        ', commandStart) : -1;
  const commandBlock = commandStart >= 0 && commandEnd > commandStart
    ? source.slice(commandStart, commandEnd)
    : '';
  const inputFileCommands = [
    'lint_only',
    'validate_only',
    'dry_run',
    'pre_execute_gate',
    'execute_to_pending_review',
  ];
  const commandsUsingFillable = inputFileCommands.filter((name) => commandBlock.includes(`'${name}' => ctrip_operator_bundle_command('${name}', $date, $resolvedHotelId, $fillableFile)`));
  const commandsUsingTemplate = inputFileCommands.filter((name) => commandBlock.includes(`'${name}' => ctrip_operator_bundle_command('${name}', $date, $resolvedHotelId, $templateFile)`));
  check(
    file,
    'Ctrip operator bundle follow-up commands use the fillable input file, not the read-only template',
    commandsUsingFillable.length === inputFileCommands.length && commandsUsingTemplate.length === 0,
    JSON.stringify({ commandsUsingFillable, commandsUsingTemplate })
  );
}

includesAll('scripts/verify_revenue_ai_ctrip_operator_bundle.mjs', 'Ctrip operator bundle verifier stays structure-only and fillable-file scoped', [
  'operator_bundle_structure_only_no_db_no_ota_write',
  'database_touched: false',
  'auto_write_ota: false',
  'refresh_evidence_preserves_operator_inputs',
  'preserved_input_files',
  'preserved === true',
  'overwritten === false',
  'pricing-input-fillable.json',
  'pricing-input-template.json',
  'input_commands_use_fillable_file',
  'input_commands_are_hotel_scoped',
  'commands_do_not_write_ota',
  'pending_operator_real_values',
  'operator_verified_values_required',
  'can_generate_pending_review: false',
  'fillable_contains_only_real_input_fields',
  'fillable_requires_operator_input_evidence',
  'fillable_json_exposes_optional_row_source_note',
  'OPERATOR_INTAKE_FORM.md',
  'CTRIP_CLOSURE_RUNBOOK.md',
  'REAL_INPUT_TODO.md',
  'real-input-checklist.json',
  'pricing-input.schema.json',
  'pricing-input-intake.csv',
  'demand_forecast_row_required === !trafficTrendDemandReady',
  'operator_intake_form?.demand_forecast_row_required === !trafficTrendDemandReady',
  'pricingInputSchema?.properties?.demand_forecasts?.minItems === (trafficTrendDemandReady ? 0 : 1)',
  'operator-input-locators.csv',
  'OPERATOR_REVIEW_DRAFT.md',
  'demand-trend-draft.json',
  'demand-trend-draft.md',
  'pricing-evidence-candidates.json',
  'pricing-evidence-candidates.md',
  'pricing-evidence-candidates.csv',
  'external-input-candidates.json',
  'external-input-candidates.md',
  'external-input-candidates.csv',
  'auto-input-eligibility.json',
  'auto-input-eligibility.md',
  'input-readiness.json',
  'input-readiness.md',
  'OPERATOR_CONFIRMATION_BRIEF.md',
  'operator-confirmation-brief.csv',
  'OPERATOR_REAL_INPUT_REQUEST.md',
  'OPERATION_ROI_EVIDENCE_REQUEST.md',
  'externalInputCandidates',
  'autoInputEligibility',
  'inputReadiness',
  'pricingEvidenceCandidates',
  'demandTrendDraft',
  'operatorReviewDraftText',
  'pricingEvidenceCandidatesMarkdownText',
  'pricingEvidenceCandidatesCsvText',
  'externalInputCandidatesMarkdownText',
  'externalInputCandidatesCsvText',
  'inputReadinessMarkdownText',
  'operatorConfirmationBriefText',
  'operatorConfirmationBriefCsvText',
  'operatorRealInputRequestText',
  'operator_confirmation_brief_minimum_inputs_not_importable',
  'operator_quick_reply_minimum_inputs_not_importable',
  'operator_real_input_request_human_request_not_importable',
  'operation_roi_evidence_request_not_importable_not_proof',
  'human_operation_roi_evidence_request_no_values_no_import',
  'human_operation_roi_evidence_request_not_importable',
  'operation_execution.roi_ready',
  'local_manual_roi_evidence_no_ota_write',
  'operator_request_no_values_no_import',
  'human_real_input_request_not_importable',
  'Review Hints (Not Importable)',
  'Candidate hints are copied from `OPERATOR_CONFIRMATION_BRIEF.md` and `operator-confirmation-brief.csv`',
  'candidate_values_importable',
  'input_readiness_scan_command_read_only_and_scoped',
  'input_readiness_scan_manifest_and_payload_read_only',
  'auto_input_eligibility_command_read_only_and_scoped',
  'auto_input_eligibility_manifest_and_payload_read_only',
  'read_operator_bundle_evidence_only_no_db_no_ota_write',
  'room_name_or_room_count_candidates_do_not_prove_operator_enabled_room_type_key_and_sellable_room_count',
  'observed_average_prices_and_350_450_assumptions_are_not_operator_approved_base_min_max_guards',
  'competitor_aggregates_and_historical_market_references_are_not_recent_named_ctrip_price_samples',
  'ctrip_historical_traffic_trend_is_accepted_as_demand_forecast_source',
  'external_input_candidates_command_read_only_and_scoped',
  'external_input_candidates_manifest_non_importable',
  'external_input_candidates_payload_boundaries',
  'external_input_candidates_markdown_and_csv_boundaries',
  'pricing_evidence_candidates_command_read_only_and_scoped',
  'pricing_evidence_candidates_manifest_non_importable',
  'pricing_evidence_candidates_payload_boundaries',
  'pricing_evidence_candidates_markdown_and_csv_boundaries',
  'demand_trend_draft_manifest_non_importable',
  'demand_trend_draft_payload_boundaries',
  'operator_review_draft_human_review_only',
  'operatorInputLocatorsCsvHeader',
  'expectedLocatorCsvHeaders',
  'operator_input_locators_csv_metadata_only',
  'pricingInputIntakeCsvHeader',
  'expectedCsvHeaders',
  'real_input_todo_current_and_no_raw_values',
  'real_input_checklist_metadata_only',
  'pricing_input_schema_editor_guidance_only',
  'operator_intake_form_human_fillable_not_importable',
  'closure_runbook_covers_full_chain_no_ota_write',
  'post_pending_commands_present_and_scoped',
  'csv_intake_converter_command_no_db_no_ota_write',
  'csv_to_json_preflight_command_no_db_no_ota_write',
  'quick_reply_preflight_command_no_db_no_ota_write',
  'verify:revenue-ai-ctrip-operator-csv-preflight',
  'verify:revenue-ai-ctrip-operator-quick-reply-preflight',
  'quick_reply_preflight',
  'csv_to_json_preflight',
  'csv_intake_template_ctrip_only_blank_business_values',
  'required_fields,expected_real_input,format_guard,forbidden_fill',
  'non-Ctrip OTA',
  'csv_issue_map.csv_row_number',
  'csv_issue_map.csv_column',
  'checklistCsvColumns.includes',
  'checklistCsvSections.includes',
  'checklistCsvRows.includes',
  'analysis_date within 7 days ending at business_date',
  'schema_is_authoritative',
  'operator_real_input_checklist_no_values_no_import',
  'human_fillable_collection_not_importable',
  'human_fillable_csv_not_importable_until_converted_and_linted',
  'metadata_locator_csv_not_importable',
  'metadata_locator_only_no_values_no_import',
  'manual_closure_sequence_no_ota_price_write',
  'p0AuthorityTodoMatches',
  'p0_authority_status',
  'p0_authority_command:',
  'current-scope.json',
  'raw_capture_read_by_bundle',
  'verify:p0-ota-field-loop',
  'not_reverified_by_bundle',
  'Operator Evidence Locators',
  'Field-Level Real Input Checklist',
  'Room Types And Price Guards',
  'Ctrip Competitor Price Samples',
  'external_input_candidates',
  'external project-material',
  'build_fillable_from_csv',
  'csv_to_json_preflight',
  'demand_trend_draft',
  'pricing_evidence_candidates',
  'report:revenue-ai-ctrip-pricing-evidence-candidates',
  'report:revenue-ai-ctrip-traffic-demand-trend',
  'Ctrip OTA evidence -> revenue analysis -> AI pricing suggestion -> manual review -> operation intent -> ROI evidence',
  '$.room_types.0.base_price',
  '$.demand_forecasts.0.predicted_occupancy',
  'Locator row ids and source traces are metadata only',
  'metadata-only evidence navigation',
  'operation_execution.roi_ready',
  'verify:revenue-ai-ctrip-operation-roi',
  'verification_commands',
  'operator_fill_required',
  'current_preflight',
  '--hotel-id',
  '--date',
]);

includesAll('scripts/verify_revenue_ai_ctrip_operator_bundle_preflight.mjs', 'Ctrip operator bundle preflight runs the full no-execute gate sequence', [
  'operator_bundle_preflight_no_execute_no_ota_write',
  'database_commit_allowed: false',
  'execute_allowed: false',
  'auto_write_ota: false',
  'verify:revenue-ai-ctrip-operator-bundle',
  'lint:revenue-ai-ctrip-pricing-inputs',
  'validate:revenue-ai-ctrip-pricing-inputs',
  'import:revenue-ai-ctrip-pricing-inputs',
  'verify:revenue-ai-ctrip-pricing-file',
  'pricing-input-fillable.json',
  'ready_for_execute_to_pending_review',
  'next_execute_command_allowed_only_after_pass',
  'summarizeRealInputChecklist',
  'real_input_handoff',
  'operator_action_sheet_file',
  'operator_action_sheet_status',
  'operator_action_sheet_use',
  'operator_action_sheet_target_file',
  'operator_action_sheet_importable_value',
  'operator_action_sheet_auto_write_ota',
  'operator_confirmation_brief_file',
  'operator_confirmation_brief_csv_file',
  'operator_confirmation_brief_status',
  'operator_confirmation_brief_use',
  'operator_confirmation_brief_target_file',
  'operator_confirmation_brief_importable_value',
  'operator_confirmation_brief_auto_write_ota',
  'minimum_human_confirmation_brief_not_importable',
  'candidate_to_operator_action_sheet_not_importable',
  'map Ctrip candidate hints to pricing-input-intake.csv fields',
  'shortest Ctrip-only list of fields that still require operator confirmation',
  'it is not importable and does not replace operator-confirmed values',
  'first_missing_inputs',
  'missing_input_groups',
  'csv_file',
  'csv_row_number',
  'csv_section',
  'csv_column',
  'expected_real_input',
  'format_guard',
  'forbidden_fill',
  'Regenerate the operator bundle before preflight.',
  'validate_only_rollback',
  'dry_run_rollback',
  'pre_execute_gate_rollback',
]);

includesAll('scripts/verify_revenue_ai_ctrip_operator_csv_preflight.mjs', 'Ctrip operator CSV preflight converts intake to local JSON before running no-execute preflight', [
  'operator_csv_to_json_preflight_no_db_no_ota_write',
  'build:revenue-ai-ctrip-pricing-input-from-csv',
  'verify:revenue-ai-ctrip-operator-bundle-preflight',
  'pricing-input-intake.csv',
  'pricing-input-fillable.json',
  'database_commit_allowed: false',
  'execute_allowed: false',
  'auto_write_ota: false',
  'database_written: false',
  'generated_local_file_only',
  'csv_issue_map_count',
  'first_csv_issues',
  'csv_issue_map',
  'Fill pricing-input-intake.csv with real operator-verified Ctrip values',
  'CSV built and no-execute preflight passed',
  '--build-json-from-csv=1',
  '--force=1',
]);

includesAll('scripts/verify_revenue_ai_ctrip_operator_quick_reply_preflight.mjs', 'Ctrip operator quick-reply preflight converts reply text through temporary local inputs only', [
  'operator_quick_reply_preflight_no_db_no_ota_write',
  'OPERATOR_QUICK_REPLY.md',
  'pricing-input-intake.csv',
  'pricing-input-fillable.json',
  'build_json_from_quick_reply',
  'build:revenue-ai-ctrip-pricing-input-from-csv',
  'lint:revenue-ai-ctrip-pricing-inputs',
  'validate:revenue-ai-ctrip-pricing-inputs',
  'import:revenue-ai-ctrip-pricing-inputs',
  'verify:revenue-ai-ctrip-pricing-file',
  'database_commit_allowed: false',
  'execute_allowed: false',
  'auto_write_ota: false',
  'database_written: false',
  'generated_local_file_only',
  'generated_temp_files_retained',
  'temporary_local_files_no_db_no_ota_write',
  'write_fillable_requested',
  'write_fillable_policy',
  'only_after_all_no_execute_gates_pass_no_db_no_ota_write',
  'bundle_file_write_allowed',
  'bundle_fillable_written',
  '--write-fillable=1',
  'Fill OPERATOR_QUICK_REPLY.md with real operator-verified Ctrip values',
  'collectIndexedRows',
  'indexed_multi_room',
  'indexed_multi_competitor_sample',
  'room_type_1_key',
  'competitor_sample_1_room_type_key',
  'room_type_row_count',
  'competitor_sample_row_count',
  '--build-json-from-csv=1',
  '--force=1',
]);

includesAll('scripts/run_revenue_ai_ctrip_quick_reply_to_pending_review.mjs', 'Ctrip quick-reply runner gates local pending-review creation without OTA writes', [
  'quick_reply_gate_then_pending_review_no_ota_write',
  'quick_reply_to_pending_review_explicit_execute',
  'quick_reply_preflight_only_no_persistence',
  'verify:revenue-ai-ctrip-operator-quick-reply-preflight',
  'verify:revenue-ai-ctrip-operator-bundle-preflight',
  'run:revenue-ai-ctrip-pricing-file-to-pending-review',
  'scripts/verify_revenue_ai_ctrip_operator_quick_reply_preflight.mjs',
  'scripts/verify_revenue_ai_ctrip_operator_bundle_preflight.mjs',
  'scripts/execute_revenue_ai_ctrip_pricing_file.php',
  '--write-fillable=1',
  '--execute=1',
  '--generate=1',
  'database_commit_allowed',
  'database_written',
  'pending_review_created',
  'auto_write_ota: false',
  'manual review',
]);

includesAll('scripts/report_revenue_ai_ctrip_pending_review_packet.php', 'Ctrip pending review packet stays read-only and manual-review gated', [
  'RevenueAiOverviewService',
  'PriceSuggestion::STATUS_PENDING',
  "'platform' => 'ctrip'",
  "'enabled_channels' => ['ctrip']",
  'read_only_pending_review_packet_no_write',
  'blocked_empty_queue',
  'pending_review',
  'price_suggestions',
  'Ctrip Revenue AI Pending Review Packet',
  'ctrip_pending_review_build_packet',
  'database_written',
  'auto_write_ota',
  'meituan_scope_included',
  'manual_review_required',
  'operator_input_evidence_summary',
  'confirm_operator_input_evidence_sources',
  'Operator Input Evidence',
  'manual_ctrip_room_type_pricing_guard',
  'manual_demand_forecast',
  'manual_ctrip_competitor_price_sample',
  'operator_review_evidence_required',
  'fill_operator_review_evidence',
  'operator_review_evidence must be filled with the reviewer, review time, decision basis, price guard source, and operation intent source.',
  'review_endpoint_base',
  '/api/revenue-ai/price-suggestions/{id}/review',
  'execution_intent_endpoint_base',
  '/api/revenue-ai/price-suggestions/{id}/execution-intent',
  'allowed_manual_actions',
  'approve_with_changes',
  'operation_execution_before_review',
  'investment_decision_before_operation_roi',
  'upstream_next_commands',
  'report:revenue-ai-ctrip-pricing-operator-packet',
  'export_operator_bundle',
  'export:revenue-ai-ctrip-operator-bundle',
  '--output-dir=<operator-bundle-dir>',
  'run:revenue-ai-ctrip-pricing-file-to-pending-review',
  'verify:revenue-ai-ctrip-pending-review-packet',
  'export_review_decision_template',
  '--suggestion-id=<pending-suggestion-id>',
  '--output=<review-decision-json-path>',
  'validate_review_decision',
  'execute_review_decision_and_create_operation_intent',
  'verify_review_decision',
  'verify_operation_roi_boundary',
  'verify:revenue-ai-ctrip-operation-roi',
  'run:revenue-ai-ctrip-review-decision',
  'pending_items_have_no_meituan',
  'manual_review_gate_no_auto_apply',
]);

includesAll('scripts/verify_revenue_ai_ctrip_pending_review_packet.php', 'Ctrip pending review packet verifier proves positive review queue path with rollback', [
  'Db::startTrans()',
  'Db::rollback()',
  'transactional_pending_review_packet_fixture_rollback_no_ota_write',
  'ctrip_pending_review_build_packet',
  'ctrip_pending_review_verify_insert_fixture',
  'RoomType::STATUS_ENABLED',
  'PriceSuggestion::STATUS_PENDING',
  'PriceSuggestion::TYPE_COMPETITOR',
  "'source_scope' => 'ctrip_ota_channel'",
  "'source_channels' => ['ctrip']",
  'manual_review_required_no_auto_rate_write',
  'packet_reads_pending_review_item',
  'created_item_review_contract_complete',
  'created_item_exposes_operator_input_evidence_summary',
  'manual_ctrip_room_type_pricing_guard',
  'manual_demand_forecast',
  'manual_ctrip_competitor_price_sample',
  'packet_contract_blocks_downstream_shortcuts',
  'packet_exposes_post_review_roi_boundary_gate',
  'verify_operation_roi_boundary',
  'verify:revenue-ai-ctrip-operation-roi',
  'fill_operator_review_evidence',
  'operator_review_evidence_required',
  'operation_intent_source',
  'operation_execution_before_review',
  'investment_decision_before_operation_roi',
  'transaction_rolled_back',
  'meituan_not_present',
]);

includesAll('scripts/import_revenue_ai_ctrip_pricing_inputs.php', 'Ctrip pricing input importer requires operator evidence and explicit persistence', [
  'Db::startTrans()',
  'Db::rollback()',
  'Db::commit()',
  "'output' =>",
  "'force' =>",
  '--execute',
  '--generate',
  '--lint-only',
  '--validate-only',
  '--print-template',
  '--print-current-template',
  '--build-json-from-csv',
  '--csv-file',
  'ctrip_pricing_import_write_json_output',
  'ctrip_pricing_import_read_csv_rows',
  'ctrip_pricing_import_read_csv_rows_with_lines',
  'ctrip_pricing_import_required_csv_headers',
  'ctrip_pricing_import_assert_csv_header',
  'ctrip_pricing_import_payload_from_csv',
  'ctrip_pricing_import_csv_issue_map',
  'csv_issue_map_no_values_no_import',
  'csv_issue_map_count',
  'csv_row_number',
  'csv_column',
  'ctrip_pricing_import_current_template',
  'Output file already exists. Pass --force=1 to overwrite',
  "'output_file' =>",
  'ctrip_pricing_import_lint_payload',
  'ctrip_pricing_import_lint_optional_source_note',
  'ctrip_pricing_import_optional_rows',
  'ctrip_pricing_import_uses_traffic_trend_demand',
  'ctrip_pricing_import_csv_blank_demand_forecast_row',
  'ctrip_historical_traffic_trend',
  'operator_provided_ctrip_pricing_inputs_lint_only_no_db',
  'database_touched',
  'placeholder_value',
  'operator_input_evidence',
  'operator_input_evidence_missing',
  'operator_input_evidence_forbidden',
  'source_note_forbidden',
  'operator_input_evidence_attached',
  'operator_row_source_note',
  "'source_note' => ''",
  'ctrip_pricing_import_metadata',
  'ctrip_pricing_import_saved_metadata_ready',
  'ctrip_pricing_import_generation_source_metadata',
  'source_metadata',
  'manual_ctrip_room_type_pricing_guard',
  'confirmed_by',
  'confirmed_at',
  'room_type_source',
  'price_guard_source',
  'demand_forecast_source',
  'competitor_price_source',
  'room_type_key_unmatched',
  'competitor_platform_invalid',
  '--lint-only cannot be combined with --execute, --generate, or --validate-only.',
  'operator_provided_ctrip_pricing_input_template_from_current_preflight',
  'operator_provided_ctrip_pricing_csv_to_json_no_db',
  'build_json_from_csv',
  '--build-json-from-csv cannot be combined',
  'CSV header missing required columns',
  'CSV header has duplicate columns',
  'Use pricing-input-intake.csv from the operator bundle',
  'CSV row ',
  'current_preflight',
  'operator_fill_required',
  'required_input_codes',
  'verification_commands',
  'operator_packet',
  'report:revenue-ai-ctrip-pricing-operator-packet',
  'export_operator_bundle',
  'export:revenue-ai-ctrip-operator-bundle',
  '--output-dir=<operator-bundle-dir>',
  'inspect_current_ota_evidence',
  'inspect:revenue-ai-ctrip-pricing-sources',
  'export_to_file',
  'build_from_csv',
  'build:revenue-ai-ctrip-pricing-input-from-csv',
  '--csv-file=<operator-intake-csv-path>',
  'lint_only',
  'validate_only',
  'pre_execute_gate',
  'gate_then_execute_and_generate_pending_review',
  'pending_review_packet',
  'report:revenue-ai-ctrip-pending-review-packet',
  'verify_pending_review_packet',
  'verify:revenue-ai-ctrip-pending-review-packet',
  'export_review_decision_template',
  'export:revenue-ai-ctrip-review-template',
  '--suggestion-id=<pending-suggestion-id>',
  '--output=<review-decision-json-path>',
  'validate_review_decision',
  'execute_review_decision_and_create_operation_intent',
  'verify_review_decision',
  'verify:revenue-ai-ctrip-review-decision',
  'run:revenue-ai-ctrip-review-decision',
  'run:revenue-ai-ctrip-pricing-file-to-pending-review',
  'verify:revenue-ai-ctrip-pricing-file',
  'Replace every <...> placeholder',
  'Input lint failed:',
  '--validate-only cannot be combined with --execute or --generate.',
  'operator_provided_ctrip_pricing_inputs_validate_only_rollback',
  'validate_only_keeps_generation_disabled',
  'demand_forecast_source',
  'operator_provided_ctrip_pricing_inputs_dry_run_rollback',
  'operator_provided_ctrip_pricing_inputs_execute',
  "'source_scope' => 'ctrip_ota_channel'",
  "'enabled_channels' => ['ctrip']",
  'source_scope must be ctrip_ota_channel',
  'platform must be ctrip',
  'competitor_price_samples.ota_platform must be ctrip',
  'operator_input_evidence is required before importing true Ctrip pricing inputs.',
  'ctrip_pricing_import_date',
  'analysis_date_invalid',
  'analysis_date_outside_recent_7d',
  'analysis_date must be within the 7-day window ending at business_date',
  'earliest_allowed_date',
  'latest_allowed_date',
  'new Agent($app)',
  'saveRoomType()',
  'createForecast()',
  'recordCompetitorPrice()',
  'generatePriceSuggestions()',
  'RevenueAiOverviewService',
  'pricing_preflight_has_candidate',
  'generation_keeps_manual_review_gate',
  "'auto_write_ota' => false",
  'manual_pricing_configuration',
  'operator_provided',
  'source_file_sha256',
  'import_mode',
  'RoomType::where',
  'DemandForecast::where',
  'CompetitorAnalysis::PLATFORM_CTRIP',
]);

{
  const file = 'scripts/import_revenue_ai_ctrip_pricing_inputs.php';
  const source = read(file);
  const commandStart = source.indexOf("'verification_commands' => [");
  const commandEnd = commandStart >= 0 ? source.indexOf('        ],\n    ];', commandStart) : -1;
  const commandBlock = commandStart >= 0 && commandEnd > commandStart
    ? source.slice(commandStart, commandEnd)
    : '';
  const commandLines = commandBlock
    .split('\n')
    .filter((line) => line.includes('npm.cmd run'));
  const unscopedCommands = commandLines.filter((line) => !line.includes('$hotelArg'));
  check(
    file,
    'Ctrip pricing input template keeps every verification command scoped to the resolved hotel',
    commandLines.length >= 19 && unscopedCommands.length === 0,
    unscopedCommands.join('\n')
  );
  const inputPlaceholderScope = "foreach (['operator_input_evidence', 'room_types', 'demand_forecasts', 'competitor_price_samples'] as $inputKey)";
  const placeholderScopeCount = source.split(inputPlaceholderScope).length - 1;
  check(
    file,
    'Ctrip pricing input placeholder checks scan real import input arrays and operator evidence at root',
    placeholderScopeCount >= 2
      && source.includes("ctrip_pricing_import_assert_no_placeholder($value[$inputKey], '$.' . $inputKey)")
      && source.includes("ctrip_pricing_import_placeholder_paths($value[$inputKey], '$.' . $inputKey)"),
    `placeholderScopeCount=${placeholderScopeCount}`
  );
}

includesAll('scripts/execute_revenue_ai_ctrip_pricing_file.php', 'Gated Ctrip pricing file runner enforces pre-execute gate before persistence', [
  'verify_revenue_ai_ctrip_pricing_input_pipeline.php',
  'operator_input_file_pre_execute_gate_rollback_only',
  'gate_rolled_back_without_ota_write',
  'pre_execute_gate_passed_no_persistence',
  'gate_failed_no_execute',
  'pre_execute_gate_then_explicit_execute',
  'import_revenue_ai_ctrip_pricing_inputs.php',
  '--execute=1',
  '--generate=1',
  'execute_committed_after_gate',
  'execute_keeps_ctrip_manual_review_gate',
  'verify_revenue_ai_ctrip_scope.php',
  'post_execute_scope_verifier_passes',
  'post_execute_pending_review_visible',
  'pending_review',
  'source_scope',
  'ctrip_ota_channel',
  'source_channels',
  'auto_write_ota',
  'operation_intake_allowed',
  'database_written',
  'If these are operator-verified real Ctrip values',
  'Review pending Ctrip AI price suggestions before creating any operation execution',
]);

includesAll('scripts/execute_revenue_ai_ctrip_review_decision.php', 'Ctrip review-decision runner gates manual review before operation intent', [
  'ctrip_review_decision_template',
  'ctrip_review_decision_template_for_pending',
  'ctrip_review_decision_pending_template_context',
  'ctrip_review_decision_write_json_output',
  'ctrip_review_decision_run',
  'ctrip_review_decision_build_manual_review',
  'ctrip_review_decision_operator_review_evidence',
  'ctrip_review_decision_operator_review_evidence_issues',
  'review_decision_template_from_pending_suggestion',
  'review_decision_template_without_pending_suggestion',
  'Output file already exists. Pass --force=1 to overwrite',
  'pending_suggestion',
  'post_approval_operation_evidence_handoff_preview',
  'output_file',
  'suggestion_id',
  'operator_review_decision_validate_only_rollback',
  'operator_review_decision_explicit_execute',
  'review_decision_lint_no_write',
  'review_decision_gate_no_write',
  'source_scope',
  'ctrip_ota_channel',
  "'platform' => 'ctrip'",
  "'auto_write_ota' => false",
  'PriceSuggestion::STATUS_PENDING',
  'PriceSuggestion::STATUS_APPROVED',
  'PriceSuggestion::STATUS_REJECTED',
  'approve_with_changes',
  'operator_review_evidence',
  'operator_review_evidence_missing',
  'operator_review_evidence_forbidden',
  'operator_review_evidence_date_invalid',
  'operator_review_evidence_present',
  'reject_does_not_create_intent',
  'operation_intent_keys_present',
  'suggestion_source_ctrip_only',
  'approved_price_within_guard',
  'manual_review_written_locally',
  'manual_review_evidence_attached',
  'manual_ctrip_ai_price_review',
  'review_keeps_no_ota_write',
  'execution_intent_policy_respected',
  'ctrip_review_decision_operation_evidence_handoff',
  'ctrip_review_decision_operation_evidence_handoff_preview',
  'ctrip_review_decision_roi_window',
  'operation_evidence_handoff',
  'operation_evidence_handoff_preview_not_execution_proof',
  'fill_after_manual_approval_only_not_execution_or_roi_proof',
  'previous_day',
  'next_day',
  'manual_execution_evidence_required',
  'manual_roi_evidence_required',
  'execution_payload_template',
  'roi_evidence_payload_template',
  'operator_execution_evidence',
  'operator_roi_evidence',
  'execution_receipt_or_screenshot_path',
  'roi_calculation_basis',
  'before_metric_source',
  'after_metric_source',
  'ctrip_ota_channel_execution_evidence',
  'do_not_promote_ctrip_ota_scope_to_whole_hotel_truth',
  'local_manual_roi_evidence_no_ota_write',
  'OperationManagementService',
  'buildPriceSuggestionExecutionIntentInput',
  'createExecutionIntent',
  'operation_execution_intents',
  'price_suggestions.factors.manual_review_versions',
  'Use approve_with_changes when the operator supplies an approved_price',
]);

includesAll('scripts/verify_revenue_ai_ctrip_review_decision.php', 'Ctrip review-decision verifier proves post-review operation-intent path with rollback', [
  'Db::startTrans()',
  'Db::rollback()',
  'transactional_review_decision_fixture_rollback_no_ota_write',
  'ctrip_review_decision_run',
  'ctrip_review_decision_verify_insert_fixture',
  'ctrip_review_decision_verify_payload',
  'review_template_output_written',
  'review_template_prefills_pending_suggestion',
  'review_template_exposes_post_approval_operation_evidence_preview',
  'review_template_output_overwrite_guarded',
  'review_decision_template_from_pending_suggestion',
  'Output file already exists',
  'force_overwrite',
  'output_file_written',
  'RoomType::STATUS_ENABLED',
  'PriceSuggestion::STATUS_PENDING',
  'PriceSuggestion::TYPE_COMPETITOR',
  "'source_scope' => 'ctrip_ota_channel'",
  "'source_channels' => ['ctrip']",
  'approve_with_changes',
  "'approved_price' => 335",
  "'evidence_status' => 'verifier_transaction_only'",
  "'operator_review_evidence' => [",
  "'create_execution_intent_after_approval' => true",
  "'manage_transaction' => false",
  'review_decision_runner_passed',
  'review_decision_scope_ctrip_only',
  'approve_with_changes_records_manual_review',
  'operator_review_evidence_present',
  'manual_review_evidence_attached',
  'post_approval_execution_intent_created',
  'operation_evidence_handoff_includes_roi_window',
  'post_approval_operation_evidence_handoff_preview',
  'operation_evidence_handoff_preview_not_execution_proof',
  'manual_execution_evidence_required',
  'manual_roi_evidence_required',
  'execution_payload_template',
  'roi_evidence_payload_template',
  'runner_checks_include_boundaries',
  'transaction_rolled_back',
  'meituan_not_present',
  'operation_execution_intents',
]);

includesAll('route/app.php', 'Revenue AI and operation routes are authenticated and complete', [
  "Route::group('api/revenue-ai'",
  "Route::get('/overview', 'RevenueAi/overview')",
  "Route::post('/price-suggestions/:id/review', 'RevenueAi/reviewPriceSuggestion')",
  "Route::post('/price-suggestions/:id/execution-intent', 'RevenueAi/createPriceSuggestionExecutionIntent')",
  "Route::post('/execution-intents/:id/approve', 'OperationManagement/approveExecutionIntent')",
  "Route::post('/execution-tasks/:id/execute', 'OperationManagement/executeExecutionTask')",
  "Route::post('/execution-tasks/:id/evidence', 'OperationManagement/executionTaskEvidence')",
  "Route::post('/execution-tasks/:id/review', 'OperationManagement/reviewExecutionTask')",
  '->middleware(\\app\\middleware\\Auth::class)',
]);

includesAll('app/controller/RevenueAi.php', 'Revenue AI review keeps versioned audit and no OTA write boundary', [
  'requestedEnabledChannels',
  "'enabled_channels'",
  "'platform'",
  'revenue_ai_channel_invalid',
  'recordPriceSuggestionManualReview(',
  'buildManualReviewState(',
  "'manual_review_versions'",
  "'manual_review'",
  "'status_after'",
  "'reviewed_by'",
  "'reviewed_at'",
  "'auto_write_ota' => false",
  "'local_price_updated' => false",
  "'ota_write' => false",
  "'forbidden_actions' => ['apply_price', 'ota_write', 'update_room_type_base_price']",
  'PriceSuggestion::STATUS_PENDING',
  'PriceSuggestion::STATUS_APPROVED',
  'OperationManagementService',
  'createExecutionIntent(',
]);

includesAll('app/controller/Agent.php', 'Agent price suggestion generation exposes blocked preconditions without fake success', [
  'buildPriceSuggestionGenerationBlockedResult',
  'buildPriceSuggestionGenerationRuntimeResult',
  'roomTypes(): Response',
  'saveRoomType(): Response',
  'normalizeRoomTypePayload',
  'normalizeDemandForecastPayload',
  'normalizeCtripCompetitorPricePayload',
  'manualCtripPricingInputMetadata',
  'parsePositiveRoomTypeMoney',
  "'status' => 'blocked'",
  "'reason' => $reason",
  "'source_scope' => 'ctrip_ota_channel'",
  "'source_channels' => ['ctrip']",
  "'review_endpoint_base' => '/api/revenue-ai/price-suggestions/{id}/review'",
  "'execution_intent_endpoint_base' => '/api/revenue-ai/price-suggestions/{id}/execution-intent'",
  "'ai_review_gate' => [",
  "'pending_manual_review'",
  "'auto_apply_ai_advice' => false",
  "'operation_intake_allowed' => false",
  "'can_generate_pending_suggestions' => false",
  "'manual_review_required' => true",
  "'auto_write_ota' => false",
  "'required_inputs' => $this->buildPriceSuggestionGenerationRequiredInputs($reason)",
  "'room_types_empty'",
  "'room_types_enabled'",
  "'floor_price_or_min_rate_guard'",
  "'demand_forecast'",
  "'competitor_price_samples'",
  "'pricing_candidate_signal'",
  "'price suggestion generation blocked'",
  "'input_scope' => 'manual_pricing_configuration'",
  "'target_workflow' => 'ctrip_revenue_ai_pricing_generation'",
  "'evidence_status' => 'operator_provided'",
  "'auto_write_ota' => false",
  "'source_scope' => 'ctrip_ota_channel'",
  "$result['input_type'] = $inputType;",
  "'manual_demand_forecast'",
  "'manual_ctrip_competitor_price_sample'",
  'CompetitorAnalysis::PLATFORM_CTRIP',
]);

includesAll('route/app.php', 'Agent exposes manual room type pricing guard routes for Ctrip Revenue AI preflight', [
  "Route::get('/room-types', 'Agent/roomTypes')",
  "Route::post('/room-types', 'Agent/saveRoomType')",
]);

includesAll('app/model/CompetitorAnalysis.php', 'competitor price matrix can display operator-provided Ctrip sample name', [
  '$operatorCompetitorName',
  "$competitorData['competitor_name']",
  "'competitor_data' => $competitorData",
]);

excludesAll('app/controller/RevenueAi.php', 'Revenue AI endpoints do not directly apply prices', [
  '->apply(',
  "Db::name('room_types')",
  '$roomType->base_price',
  'update_room_type_base_price(',
]);

includesAll('app/service/OperationManagementService.php', 'operation bridge carries approved suggestion into execution and ROI closure', [
  'buildPriceSuggestionExecutionIntentInput',
  'latestManualReviewFromFactors',
  'manualApprovedPriceFromReview',
  "'source_module' => 'price_suggestion'",
  "'manual_review_storage' =>",
  'createExecutionIntent(',
  'approveExecutionIntent(',
  'executeExecutionTask(',
  'addExecutionEvidence(',
  'reviewExecutionTask(',
  'buildExecutionRoi(',
  'buildExecutionOperatorEvidenceSummary',
  'summarizeExecutionOperatorEvidence',
  'operator_execution_evidence_summary',
  'operator_roi_evidence_summary',
  'after_revenue - before_revenue',
]);

includesAll('app/service/RevenueAiOverviewService.php', 'Revenue AI overview separates process progress, review input, and ROI truth', [
  'buildPriceSuggestionReviewQueue',
  'buildExecutionSummaryFromFlow',
  '$channels = $enabledChannels !== [] ? $enabledChannels : self::CHANNELS;',
  'foreach ($channels as $channel)',
  "'enabled_channels' => $enabledChannels",
  '$reviewQueue = $this->priceSuggestionReviewQueue($businessDate, $hotelId);',
  '$pricingGenerationPreflight = $this->pricingGenerationPreflight($businessDate, $hotelId, $hotelIds, $dataset, $channels);',
  '$agentActivity = $this->agentActivity($businessDate, $hotelId);',
  '$executionSummary = $this->executionSummary($businessDate, $hotelId, $hotelIds);',
  "'review_queue' => $reviewQueue",
  "'pricing_generation_preflight' => $pricingGenerationPreflight",
  "'agent_activity' => $agentActivity",
  "'execution_summary' => $executionSummary",
  "$context['p0_downstream_gate'] = $filters['p0_downstream_gate']",
  'sortExecutionEffectReviewInputs',
  'executionEffectReviewInputAction',
  'executionOperatorEvidenceSummary',
  'has_operator_execution_evidence',
  'has_operator_roi_evidence',
  'operator_execution_evidence_summary',
  'operator_roi_evidence_summary',
  "'input_action_key' =>",
  "'record_execution_evidence'",
  "'record_roi_evidence'",
  "'record_effect_review'",
  'operationFeedbackInputGate',
  "'operation_feedback_input'",
  "'next_day_input_ready'",
  'priceSuggestionExpectedRevparImpact',
  'expected_revpar_impact_missing',
  'pricingGenerationPreflight',
  'ctripTrafficDemandForecastSignal',
  'ctrip_traffic_demand_forecast_count',
  'demand_forecast_source',
  'ctrip_historical_traffic_trend',
  'CTRIP_COMPETITOR_PLATFORM_VALUES',
  "whereIn('ota_platform', self::CTRIP_COMPETITOR_PLATFORM_VALUES)",
  'room_types_empty',
  'pricing_candidate_signals_missing',
  'configure_enabled_room_types_and_floor_price_guards',
  'pricingAiDecisionResolutionPlan',
  'pricingAiDecisionReviewContract',
  'pricingAiToOperationHandoff',
  'pricingOperationIntakePreflightContract',
  "'ai_decision_review_contract'",
  "'ai_decision_resolution_plan'",
  "'ai_to_operation_handoff'",
  "'operation_intake_preflight_contract'",
  'OperationManagementService::buildExecutionIntentPayload',
  '/api/operation/execution-intents',
  'manual_review_requires_explicit_evidence_no_auto_apply',
  'operation_intake_requires_approved_ai_review_and_price_target_no_auto_create',
  'fill_missing_evidence_with_defaults',
  'provide_available_room_nights_or_mark_metric_unusable',
  'persist_or_attach_manual_review_record',
  'open_agent_pricing_suggestions_and_generate_pending_review_items',
  "'target_agent_tab'",
  "'target_revenue_tab'",
  'call_create_execution_intent_before_ai_review_approval',
  'auto_create_operation_execution_intent',
]);

includesAll('public/revenue-ai-static.js', 'Revenue AI helper exposes manual review and effect review actions without fake closure', [
  'buildRevenueAiOverviewQuery',
  "platform = 'ctrip'",
  "params.set('platform', platformText)",
  'buildRevenueAiReviewQueueItems',
  'canApproveWithChanges',
  'canCreateExecutionIntent',
  'actionEntry',
  'autoWriteOta',
  'buildRevenueAiResolutionPlanSummary',
  'buildRevenueAiPricingGenerationPreflightSummary',
  'buildRevenueAiPriceSuggestionGenerateResult',
  'targetAgentTab',
  'targetRevenueTab',
  'reviewQueueTarget',
  'reviewQueueCanOpenTarget',
  'pricingGenerationPreflightSummary',
  'pricingGenerationPreflightVisible',
  'resolutionPlanSummary',
  'resolutionPlanVisible',
  'buildRevenueAiExecutionRows',
  'buildRevenueAiEffectReviewRows',
  'inputActionKey: item.input_action_key ||',
  'nextActionKey: item.input_action_key || item.target_action ||',
  'revparImpactReason',
  'expected_revpar_impact_missing',
  'resolveRevenueAiReviewActionDraft',
  'const endpoint = revenueAiReviewEndpoint(item, normalizedAction);',
  "endpoint.startsWith('/revenue-ai/price-suggestions/')",
]);

includesAll('public/index.html', 'Revenue AI homepage can execute the manual closure path only through local evidence routes', [
  '@click="submitRevenueAiReviewAction(item, \'approve\')"',
  '@click="submitRevenueAiReviewAction(item, \'approve_with_changes\')"',
  '@click="submitRevenueAiReviewAction(item, \'reject\')"',
  '@click="submitRevenueAiReviewAction(item, \'execution_intent\')"',
  "if (normalizedAction === 'execution_intent') {",
  "const revenueAiResolveReviewActionDraft = requireRevenueAiStatic('resolveRevenueAiReviewActionDraft');",
  'const draft = revenueAiResolveReviewActionDraft({ item, action });',
  'const body = revenueAiBuildReviewRequestBody({',
  'openRevenueAiExecutionItem',
  "if (navigation.targetPage === 'agent-center') {",
  'navigation.targetAgentTab',
  'navigation.targetRevenueTab',
  'navigation.targetFilter',
  'loadPriceSuggestions()',
  'recordOperationExecutionEvidence(taskItem)',
  'recordOperationRoiEvidence(taskItem)',
  'reviewOperationExecutionTask(taskItem)',
  "`/operation/execution-tasks/${taskId}/execute`",
  "`/operation/execution-tasks/${taskId}/evidence`",
  "`/operation/execution-tasks/${taskId}/review`",
  "evidence_type: 'manual_price_execution'",
  "evidence_type: 'manual_roi_evidence'",
  "evidence_boundary: 'local_manual_evidence_no_ota_write'",
  "evidence_boundary: 'local_manual_roi_evidence_no_ota_write'",
  '{{ item.impactLine }}',
  'data-testid="revenue-ai-investment-precheck"',
  'data-testid="revenue-ai-resolution-plan"',
  'data-testid="revenue-ai-pricing-generation-preflight"',
  'data-testid="agent-pricing-generation-preflight-summary"',
  'data-testid="agent-pricing-generation-preflight-gaps"',
  'data-testid="agent-pricing-generation-hotel-checks"',
  'data-testid="agent-price-suggestion-generate-result"',
  'data-testid="agent-price-suggestion-skipped-items"',
  'data-testid="agent-room-type-pricing-guard"',
  'data-testid="agent-price-suggestion-ctrip-preflight-inputs"',
  'data-testid="agent-suggestion-demand-forecast-manual-input"',
  'data-testid="agent-suggestion-ctrip-competitor-price-manual-input"',
  'data-testid="agent-demand-forecast-manual-input"',
  'data-testid="agent-ctrip-competitor-price-manual-input"',
  "const revenueAiBuildPricingGenerationPreflightSummary = requireRevenueAiStatic('buildRevenueAiPricingGenerationPreflightSummary');",
  "const revenueAiBuildPriceSuggestionGenerateResult = requireRevenueAiStatic('buildRevenueAiPriceSuggestionGenerateResult');",
  'agentPricingGenerationPreflightSummary',
  'agentPricingGenerationPreflightSummary.autoWriteOta',
  'agentPricingGenerationPreflightSummary.requiredInputs',
  'agentPricingGenerationPreflightSummary.candidateSkipReasons',
  'agentPricingGenerationPreflightSummary.candidateDataGaps',
  'agentPricingGenerationPreflightSummary.hotelChecks',
  "const loadPriceSuggestionWorkbench = async () => {",
  'handlePriceSuggestionDateChange',
  'demandForecastForm.value.forecast_date = date',
  'competitorPriceForm.value.analysis_date = date',
  'loadDemandForecasts()',
  'loadCompetitorAnalysis()',
  "request(`/agent/room-types?${params}`)",
  "request('/agent/room-types'",
  "request('/agent/demand-forecasts'",
  "request('/agent/competitor-analysis'",
  'manualCtripPricingInputMeta',
  "source_scope: 'ctrip_ota_channel'",
  "target_workflow: 'ctrip_revenue_ai_pricing_generation'",
  "evidence_status: 'operator_provided'",
  'auto_write_ota: false',
  "input_type: 'manual_demand_forecast'",
  "input_type: 'manual_ctrip_competitor_price_sample'",
  'ota_platform: 1',
  "人工配置项，仅用于携程调价预检；不是 OTA 自动采集事实，不写 OTA。",
  'priceSuggestionGenerateResult.value = result',
  'priceSuggestionGenerateResult.autoWriteOta',
  'priceSuggestionGenerateResult.requiredInputs',
  'priceSuggestionGenerateResult.skippedItems',
  'item.primarySignalCount',
  'item.dataGaps',
  'item.reviewChecklist',
  "request(`/revenue-ai/price-suggestions/${id}/review`",
  'Agent 定价建议工作台人工',
  "request(`/revenue-ai/price-suggestions/${id}/execution-intent`",
  "source: 'agent_pricing_suggestions'",
  'action.reviewQueueCanOpenTarget',
  'action.pricingGenerationPreflightVisible',
  'openRevenueAiDecisionBasis(action.reviewQueueTarget)',
  'action.investmentPrecheckVisible',
  'action.resolutionPlanVisible',
  'action.investmentPrecheckSummary?.targetEntry',
  '只读',
]);

excludesAll('public/index.html', 'Agent pricing suggestion workbench no longer bypasses Revenue AI review bridge', [
  '/agent/price-suggestions/${id}/approve?action=${action}',
  '/agent/price-suggestions/${id}/execution-intent`',
]);

includesAll('tests/RevenueAiControllerTest.php', 'controller tests prove versioned manual review and no OTA write', [
  'testRequestedEnabledChannelsKeepsCtripScopeExplicit',
  'testRequestedEnabledChannelsRejectsUnknownScope',
  'revenue_ai_channel_invalid',
  'testManualReviewStateVersionsPlainApproveWithoutOtaWrite',
  'testManualReviewStateVersionsRejectWithoutApprovedPrice',
  'testExecutionIntentPayloadDoesNotClaimPriceApplication',
  "self::assertFalse($review['auto_write_ota']);",
  "self::assertFalse($payload['ota_write']);",
]);

includesAll('tests/AgentTest.php', 'Agent generation tests prove created suggestions keep Ctrip review gate', [
  'testPriceSuggestionGenerationCreatedResultKeepsCtripReviewGate',
  "self::assertSame('ctrip_ota_channel', $result['source_scope']);",
  "self::assertSame(['ctrip'], $result['source_channels']);",
  "self::assertSame('/api/revenue-ai/price-suggestions/{id}/review', $result['review_endpoint_base']);",
  "self::assertSame('pending_manual_review', $result['ai_review_gate']['status']);",
  "self::assertFalse($result['ai_review_gate']['auto_apply_ai_advice']);",
  "self::assertFalse($result['ai_review_gate']['operation_intake_allowed']);",
]);

includesAll('tests/RevenueAiOverviewServiceTest.php', 'overview tests prove review queue, RevPAR impact, and ROI input truth', [
  'testPriceSuggestionReviewQueueSummarizesManualReviewState',
  'testPriceSuggestionReviewQueueExposesExplicitExpectedRevparImpactOnly',
  'testExecutionSummarySeparatesProcessProgressFromEffectReview',
  'testExecutionSummaryPrioritizesEffectReviewInputsWithDataGaps',
  'testExecutionSummaryFiltersByBusinessDateAndMarksReviewedEffectReady',
  'ai_decision_review_contract',
  'ai_decision_resolution_plan',
  'ai_to_operation_handoff',
  'operation_intake_preflight_contract',
  'manual_review_requires_explicit_evidence_no_auto_apply',
  'operation_intake_requires_approved_ai_review_and_price_target_no_auto_create',
  'fill_missing_evidence_with_defaults',
  'provide_floor_price_or_min_rate_guard',
  'persist_or_attach_manual_review_record',
  'OperationManagementService::buildExecutionIntentPayload',
  'ctrip_ota_channel',
  "self::assertSame('record_roi_evidence'",
  "self::assertSame('record_execution_evidence'",
  "self::assertSame('use_next_day_input'",
]);

includesAll('tests/automation/revenue_ai_static.test.mjs', 'static helper tests prove homepage action contract', [
  'Revenue AI overview endpoint builder keeps query scope explicit',
  'platform=ctrip',
  "platform: ''",
  'Revenue AI action rows expose readonly price suggestion review queue',
  'Revenue AI action rows expose AI decision resolution plan as operator evidence checklist',
  'Revenue AI execution helpers keep process and effect review separate',
  'Revenue AI effect review rows expose next-day inputs without fake ROI',
  'buildRevenueAiResolutionPlanSummary',
  "assert.equal(summary.autoWriteOta, false)",
  "assert.equal(rows[0].reviewQueueItems[0].canApproveWithChanges, true)",
  "assert.equal(partialRows[0].inputActionKey, 'record_roi_evidence')",
]);

try {
  const context = { window: {} };
  vm.runInNewContext(read('public/revenue-ai-static.js'), context, {
    filename: 'public/revenue-ai-static.js',
  });
  const helpers = context.window.SUXI_REVENUE_AI_STATIC || {};
  const actionRows = helpers.buildRevenueAiActionRows({
    overview: {
      actions: [{
        key: 'pricing_review',
        title: '待人工审核调价建议',
        status: 'pending_review',
        review_queue: {
          status: 'pending_review',
          display: '待审核 1 / 已批准 1 / 已拒绝 0 / 已应用 0',
          pending_count: 1,
          pending_items: [{
            id: 11,
            room_type_id: 3,
            suggestion_type_label: '竞对跟价',
            status: 'pending_review',
            status_label: '待审核',
            suggestion_date: '2026-06-25',
            current_price: 280,
            current_price_display: '280元',
            suggested_price: 318,
            suggested_price_display: '318元',
            min_price: 220,
            min_price_display: '220元',
            expected_revpar_impact_display: '+12.5元',
            manual_review_required: true,
            auto_write_ota: false,
            can_review: true,
            action_entry: {
              allowed_endpoints: {
                review: '/api/revenue-ai/price-suggestions/11/review',
                execution_intent: '/api/revenue-ai/price-suggestions/11/execution-intent',
              },
              manual_actions: ['approve', 'approve_with_changes', 'reject'],
              forbidden_actions: ['apply_price', 'ota_write'],
            },
          }],
          recent_items: [{
            id: 12,
            room_type_id: 3,
            suggestion_type_label: '竞对跟价',
            status: 'approved',
            status_label: '已批准',
            current_price_display: '280元',
            suggested_price_display: '318元',
            min_price_display: '220元',
            manual_review_required: true,
            auto_write_ota: false,
            action_entry: {
              allowed_endpoint: '/api/revenue-ai/price-suggestions/12/execution-intent',
              allowed_endpoints: {
                execution_intent: '/api/revenue-ai/price-suggestions/12/execution-intent',
              },
              manual_actions: ['create_execution_intent'],
              forbidden_actions: ['apply_price', 'ota_write'],
            },
          }],
        },
      }],
    },
  });
  const pending = actionRows[0]?.reviewQueueItems?.[0] || {};
  const approved = actionRows[0]?.reviewQueueItems?.[1] || {};
  check(
    'public/revenue-ai-static.js',
    'runtime helper exposes approve/approve_with_changes/reject but no OTA write',
    pending.canApprove === true
      && pending.canApproveWithChanges === true
      && pending.canReject === true
      && pending.autoWriteOta === false
      && pending.allowedEndpoints.review === '/api/revenue-ai/price-suggestions/11/review'
      && pending.impactLine === '预计RevPAR影响 +12.5元',
    JSON.stringify(pending)
  );
  check(
    'public/revenue-ai-static.js',
    'runtime helper exposes approved suggestion only as execution intent',
    approved.canCreateExecutionIntent === true
      && approved.canApprove === false
      && approved.allowedEndpoint === '/api/revenue-ai/price-suggestions/12/execution-intent',
    JSON.stringify(approved)
  );

  const effectRows = helpers.buildRevenueAiEffectReviewRows({
    overview: {
      hotel_id: 7,
      execution_summary: {
        business_date: '2026-06-25',
        effect_review: {
          input_status: 'partial',
          input_reason: 'operation_roi_missing',
          inputs: [{
            id: 72,
            intent_id: 72,
            hotel_id: 7,
            task_id: 92,
            input_status: 'partial',
            input_reason: 'operation_roi_missing',
            input_action_key: 'record_roi_evidence',
            input_action_label: '补录ROI证据',
            input_next_action: '补齐执行前后收入、成本或平台回执后再判断效果。',
            platform: 'meituan',
            platform_label: '美团',
            action_type: 'price_adjust',
            date_start: '2026-06-25',
            date_end: '2026-06-25',
            roi_status: 'data_gap',
            roi_display: '--',
            target_page: 'ops-track',
            target_action: 'review_effect',
            target_id: 92,
            target_kind: 'task',
          }],
        },
      },
    },
  });
  check(
    'public/revenue-ai-static.js',
    'runtime helper routes missing ROI to local evidence capture',
    effectRows[0]?.nextActionKey === 'record_roi_evidence'
      && effectRows[0]?.canOpenExecution === true
      && effectRows[0]?.roiDisplay === '--',
    JSON.stringify(effectRows[0])
  );
} catch (error) {
  check('public/revenue-ai-static.js', 'runtime helper validation failed', false, error.message);
}

const failures = checks.filter((item) => !item.ok);
if (failures.length) {
  console.error('Revenue AI closure contract failed:');
  for (const failure of failures) {
    console.error(`- ${failure.file}: ${failure.label} (${failure.detail})`);
  }
  process.exit(1);
}

console.log(`Revenue AI closure contract passed (${checks.length} checks).`);
