import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const read = (path) => readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8');
const runner = read('scripts/run_cloud_ota_profile_collection.php');
const adapter = read('app/service/platform/TrustedCloudProfileDataSourceAdapter.php');
const service = read('deploy/systemd/suxios-cloud-ota-profile-collection.service');
const timer = read('deploy/systemd/suxios-cloud-ota-profile-collection.timer');
const batch = read('scripts/run_cloud_ota_profile_collection_batch.php');

test('cloud OTA runner binds one source/Profile/date and persists only after current capture proof', () => {
  assert.match(runner, /validateOtaDataSourceCollectionProfile/);
  assert.match(runner, /set_exception_handler/);
  assert.match(runner, /'collection_kind'\s*=>\s*'ota_channel_profile'/);
  assert.match(runner, /'data_source_id'\s*=>\s*\$sourceId/);
  assert.match(runner, /\(\$opened\['read_only_enforced'\] \?\? null\) !== true/);
  assert.match(runner, /'cdp_url'\s*=>\s*\$cdpUrl/);
  const capture = runner.indexOf('$captureAdapter->fetch(');
  const proof = runner.indexOf('recordCollectionPreflightVerified(');
  const sync = runner.indexOf('->syncDataSource(');
  assert.ok(capture >= 0);
  assert.ok(proof > capture);
  assert.ok(sync > proof);
  assert.match(runner, /isCurrentVerified\(\$proofSource\)/);
  assert.match(runner, /current_session_proof_readback_verified/);
  assert.match(runner, /BrowserProfileProcessOutputSanitizer::sanitizeMessage/);
  assert.match(runner, /\['capture_sections'\]\s*=\s*'traffic'/);
  assert.match(runner, /\['capture_mode'\]\s*=\s*'temporal_summary'/);
  assert.match(runner, /'require_current_run_session_probe'\s*=>\s*true/);
  assert.match(runner, /'ctrip_section_concurrency'\]\s*=\s*1/);
  assert.match(runner, /'sequential_sections'\]\s*=\s*true/);
  assert.match(runner, /'dispatcher-run-id::'/);
  assert.match(runner, /'daily_profile_reuse'/);
  assert.match(runner, /\$captureOptions\['dispatcher_run_id'\]\s*=\s*\$dispatcherRunId/);
  assert.match(runner, /\$failureOptions\['dispatcher_run_id'\]\s*=\s*\$dispatcherRunId/);
  assert.match(runner, /unset\(\$syncOptions\['cdp_url'\]\)/);
  assert.match(runner, /ota_request_or_own_response/);
  assert.match(runner, /\$readbackCount !== \$savedCount/);
  assert.match(runner, /'readback_verified'\s*=>\s*true/);
  assert.match(runner, /\(string\)\(\$syncResult\['status'\] \?\? ''\) !== 'success'/);
  assert.match(runner, /primary_quality_state/);
  assert.match(runner, /p0_status/);
  assert.match(runner, /field_fact_status/);
  assert.match(runner, /missing_traffic_metric_keys/);
  assert.doesNotMatch(runner, /\['success',\s*'partial_success'\]/);
  assert.match(runner, /recordCloudProfileCollectionFailure/);
  assert.match(runner, /failure_receipt_persisted/);
  assert.match(runner, /gatewayTransportFailureCode/);
  assert.match(runner, /gateway_connection_refused/);
  assert.match(runner, /gateway_connection_timeout/);
  const gatewayOpen = runner.indexOf("'/v1/collection/open'");
  const sessionClaim = runner.indexOf('$collectionSessionId = opaqueId(', gatewayOpen);
  const openVerification = runner.indexOf("if (($opened['status']", gatewayOpen);
  const close = runner.indexOf("'/v1/collection/close'");
  const abort = runner.indexOf("'/v1/collection/abort'");
  const gatewayReceipt = runner.indexOf("'/v1/collection/receipt'");
  const gatewayReceiptReadback = runner.indexOf('gatewayReadReceipt(');
  const finalOutput = runner.indexOf('echo json_encode($result');
  assert.ok(sessionClaim > gatewayOpen);
  assert.match(runner, /'access_mode'\s*=>\s*'read_only',\s*\], 90\)/);
  assert.match(runner, /int \$timeoutSeconds = 30/);
  assert.match(runner, /'timeout'\s*=>\s*\$timeoutSeconds/);
  assert.ok(openVerification > sessionClaim);
  assert.ok(close > sync);
  assert.ok(abort > close);
  assert.ok(gatewayReceipt > close);
  assert.ok(gatewayReceiptReadback > gatewayReceipt);
  assert.ok(finalOutput > gatewayReceiptReadback);
  assert.match(runner, /\$gatewayReceiptPayload\s*=\s*\$gatewayReceiptReadback\['payload'\] \?\? null/);
  assert.match(runner, /'collection_session_id'\s*=>\s*\$collectionSessionId/);
  assert.match(runner, /'data_source_id'\s*=>\s*\$sourceId/);
  assert.match(runner, /'owner_user_id'\s*=>\s*\$ownerUserId/);
  assert.match(runner, /'close_receipt_id'\s*=>\s*\$closeReceiptId/);
  assert.match(runner, /'close_receipt_hash'\s*=>\s*\$closeReceiptHash/);
  assert.match(runner, /\$result\['gateway_receipt_readback_verified'\]\s*=\s*true/);
  assert.match(runner, /\$gatewayOpenAccepted\s*&&\s*\$controlToken !== ''/);
  assert.match(runner, /function abortGatewayCollection\(/);
  assert.match(runner, /\['aborted',\s*'no_active_collection'\]/);
  assert.match(runner, /\(\$aborted\['cleanup_verified'\] \?\? null\) === true/);
  assert.match(runner, /profile_close_failed'_?\s*\)?/);
  assert.match(runner, /gateway_abort_unverified/);
  assert.match(runner, /'message_sent'\s*=>\s*false/);
  assert.doesNotMatch(runner, /dispatchVerifiedCapture|WeCom|webhook/i);
});

test('one-shot adapter refuses stale, mismatched, or reusable capture payloads', () => {
  assert.match(adapter, /final class TrustedCloudProfileDataSourceAdapter/);
  assert.match(adapter, /private bool \$consumed = false/);
  assert.match(adapter, /trusted_cloud_profile_adapter_reuse_blocked/);
  assert.match(adapter, /http_cache_disabled/);
  assert.match(adapter, /service_worker_bypassed/);
  assert.match(adapter, /ota_request_or_own_response/);
  assert.match(adapter, /validated_identifier/);
  assert.match(adapter, /hash_equals\(\$this->expectedPlatformHotelId/);
});

test('cloud OTA service serializes Ctrip then Meituan and cannot send messages', () => {
  const execStarts = service.split(/\r?\n/).filter((line) => line.startsWith('ExecStart='));
  assert.equal(execStarts.length, 1);
  assert.match(execStarts[0], /run_cloud_ota_profile_collection_batch\.php/);
  assert.ok(batch.indexOf("'platform' => 'ctrip'")
    < batch.indexOf("'platform' => 'meituan'"));
  assert.match(batch, /foreach \(\$scopes as \$scope\)/);
  assert.match(batch, /partial_or_blocked/);
  assert.match(batch, /stream_set_blocking\(\$pipes\[1\], false\)/);
  assert.match(batch, /stream_set_blocking\(\$pipes\[2\], false\)/);
  assert.match(batch, /OTA_BATCH_CHILD_DEADLINE_SECONDS/);
  assert.match(batch, /\(\$receipt\['business_data_persisted'\] \?\? null\) !== false/);
  assert.match(batch, /gateway_receipt_readback_verified/);
  assert.match(batch, /requires_explicit_no_persistence/);
  assert.match(batch, /exit\(\$allVerified \? 0 : 1\)/);
  assert.match(service, /LoadCredential=control-token:/);
  assert.match(service, /Requires=suxios-cloud-browser-gateway\.service/);
  assert.match(service, /RuntimeDirectory=suxios-cloud-ota-profile-collection/);
  assert.doesNotMatch(execStarts.join('\n') + batch, /WeCom|webhook|dispatch|push/i);
  assert.match(timer, /OnCalendar=\*-\*-\* \*:35:00 Asia\/Shanghai/);
  assert.match(timer, /Persistent=false/);
});
