import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const state = fs.mkdtempSync(path.join(os.tmpdir(), 'suxi-l05-browser-'));
const out = path.join(root, 'output/long-goal'); fs.mkdirSync(out, { recursive: true });
const probe = net.createServer(); await new Promise(resolve => probe.listen(0, '127.0.0.1', resolve));
const port = probe.address().port; await new Promise(resolve => probe.close(resolve));
const php = spawn('C:/xampp/php/php.exe', ['-S', `127.0.0.1:${port}`, path.join(root, 'tests/fixtures/revenue_forecast_http.php')], { cwd: root, windowsHide: true, env: { ...process.env, SUXI_L05_FIXTURE_STATE: state }, stdio: ['ignore', 'pipe', 'pipe'] });
let log = ''; php.stdout.on('data', data => log += data); php.stderr.on('data', data => log += data);
let browser;
try {
    const base = `http://127.0.0.1:${port}`;
    for (let i = 0; i < 50; i++) { try { if ((await fetch(base)).ok) break; } catch {} await new Promise(resolve => setTimeout(resolve, 100)); }
    browser = await chromium.launch({ headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(base);
    await page.getByTestId('forecast-platform_store_id').fill('synthetic-store');
    await page.getByTestId('forecast-room_scope').fill('synthetic-room');
    await page.getByTestId('forecast-sample').click();
    await page.waitForFunction(() => document.querySelector('[data-testid=forecast-evidence]').value.includes('synthetic-day-242'));
    for (const [key, value] of Object.entries({ current_price: '200', proposed_price: '220', elasticity: '-1', inventory_room_nights: '210' })) await page.getByTestId(`forecast-${key}`).fill(value);
    await page.getByTestId('forecast-run').click();
    await page.getByTestId('forecast-result').waitFor();
    assert.match(await page.getByTestId('forecast-result').innerText(), /未优于基线/);
    assert.match(await page.getByTestId('forecast-scenario').innerText(), /不代表因果增收/);
    await page.getByTestId('forecast-save').click();
    await page.getByTestId('forecast-saved').waitFor();
    const originalSaved = await page.getByTestId('forecast-saved').innerText();
    await page.getByTestId('forecast-proposed_price').fill('210');
    assert.equal(await page.getByTestId('forecast-result').count(), 0);
    assert.equal(await page.getByTestId('forecast-saved').count(), 0);
    await page.getByTestId('forecast-read').first().click();
    await page.getByTestId('forecast-saved').waitFor();
    assert.equal(await page.getByTestId('forecast-proposed_price').inputValue(), '220');
    assert.equal(await page.getByTestId('forecast-saved').innerText(), originalSaved);
    await page.screenshot({ path: path.join(out, 'L05-desktop-synthetic.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: path.join(out, 'L05-mobile-synthetic.png'), fullPage: true });
    await page.getByTestId('forecast-evidence').fill('{bad json');
    await page.getByTestId('forecast-run').click();
    await page.getByRole('alert').waitFor();
    assert.equal(await page.getByTestId('forecast-result').count(), 0);
    await page.getByTestId('forecast-sample').click();
    await page.waitForFunction(() => document.querySelector('[data-testid=forecast-evidence]').value.includes('synthetic-day-242'));
    await page.getByTestId('forecast-run').click(); await page.getByTestId('forecast-result').waitFor();
    await page.getByTestId('forecast-hotel').selectOption('90002');
    assert.equal(await page.getByTestId('forecast-result').count(), 0);
    await page.getByTestId('forecast-run').click(); await page.getByRole('alert').waitFor();
    assert.match(await page.getByRole('alert').innerText(), /无权/);
    const scope = 'hotel_id=90001&platform=ctrip&platform_store_id=synthetic-store&room_scope=synthetic-room';
    const anonymous = await fetch(`${base}/api/revenue-ai/forecast-workbench/plans?${scope}`, { headers: { 'X-Synthetic-Actor': 'anonymous' } });
    assert.equal(anonymous.status, 401);
    assert.deepEqual(errors, []);
    const receipt = { status: 'passed', evidence_tier: 'isolated_browser_real_controller_synthetic_sqlite', viewports: ['1440x1000', '390x844'], checks: ['7/14/30 forecasts and baseline comparison', 'explicit pricing assumptions', 'save and exact replay', 'input change invalidation', 'invalid JSON recovery', 'cross hotel rejection', 'anonymous rejection', 'no horizontal viewport overflow', 'no page errors'], screenshot_paths: ['output/long-goal/L05-desktop-synthetic.png', 'output/long-goal/L05-mobile-synthetic.png'] };
    fs.writeFileSync(path.join(out, 'browser-verification.json'), JSON.stringify(receipt, null, 2));
    console.log(JSON.stringify(receipt));
} finally {
    if (browser) await browser.close();
    php.kill(); await new Promise(resolve => php.exitCode !== null ? resolve() : php.once('exit', resolve));
    fs.writeFileSync(path.join(out, 'browser-server.log'), log);
    const resolved = fs.realpathSync(state);
    assert.ok(resolved.startsWith(fs.realpathSync(os.tmpdir()) + path.sep + 'suxi-l05-browser-'));
    fs.rmSync(resolved, { recursive: true, force: true });
}
